In [320]:
import polars as pl
import re

# citation-claims

In [321]:
claims = pl.read_parquet("output/curator_claims.parquet")
claims.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ sentence_ ┆ sentence_ ┆ cited_sen ┆ … ┆ anchors   ┆ publicati ┆ citation_ ┆ citation │
│ ---       ┆ markers   ┆ plain     ┆ tence_mar ┆   ┆ ---       ┆ on_ids    ┆ captions  ┆ _years   │
│ str       ┆ ---       ┆ ---       ┆ ked       ┆   ┆ list[stru ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ ---       ┆   ┆ ct[2]]    ┆ list[i64] ┆ list[str] ┆ list[i64 │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DDB_G0287 ┆ grlR      ┆ grlR      ┆ grlR      ┆ … ┆ [{126,[82 ┆ [827]     ┆ ["Prabu   ┆ [2006]   │
│ 681       ┆ encodes a ┆ encodes a ┆ encodes a ┆   ┆ 7]}]      ┆           ┆ and       ┆          │
│           ┆ member of ┆ member of ┆ member of ┆   ┆           ┆           ┆ Eichinger ┆          │
│           ┆ the e…    ┆ the e…    ┆ the e…    ┆   ┆           ┆           ┆ 2006)"]   ┆          │
│ DDB_G0290 ┆ The polyk ┆ The polyk ┆ The polyk ┆ … ┆ [{144,[95 ┆ [956,     ┆ ["(Austin ┆ [2006,   │
│ 825       ┆ etide     ┆ etide     ┆ etide     ┆   ┆ 6]}, {253 ┆ 2919]     ┆ et al.    ┆ 2000]    │
│           ┆ synthase  ┆ synthase  ┆ synthase  ┆   ┆ ,[2919]}] ┆           ┆ 2006)",   ┆          │
│           ┆ StlB (…   ┆ StlB (…   ┆ StlB (…   ┆   ┆           ┆           ┆ "(Tho…    ┆          │
│ DDB_G0285 ┆ There are ┆ There are ┆ There are ┆ … ┆ [{39,[403 ┆ [4032]    ┆ ["Bukenbe ┆ [1992]   │
│ 319       ┆ three     ┆ three     ┆ three     ┆   ┆ 2]}]      ┆           ┆ rger et   ┆          │
│           ┆ histone   ┆ histone   ┆ histone   ┆   ┆           ┆           ┆ al.       ┆          │
│           ┆ H3prot…   ┆ H3prot…   ┆ H3prot…   ┆   ┆           ┆           ┆ 1992"]    ┆          │
│ DDB_G0292 ┆ Analyses  ┆ Analyses  ┆ Analyses  ┆ … ┆ [{112,[99 ┆ [9912]    ┆ ["Dimond  ┆ [1976]   │
│ 810       ┆ of gluA   ┆ of gluA   ┆ of gluA   ┆   ┆ 12]}]     ┆           ┆ and       ┆          │
│           ┆ null      ┆ null      ┆ null      ┆   ┆           ┆           ┆ Loomis    ┆          │
│           ┆ mutants … ┆ mutants … ┆ mutants … ┆   ┆           ┆           ┆ 1976)"]   ┆          │
│ DDB_G0292 ┆ Expressio ┆ Expressio ┆ Expressio ┆ … ┆ [{126,[61 ┆ [6149]    ┆ ["Schatzl ┆ [1991]   │
│ 206       ┆ n is      ┆ n is      ┆ n is      ┆   ┆ 49]}]     ┆           ┆ e et al.  ┆          │
│           ┆ dependent ┆ dependent ┆ dependent ┆   ┆           ┆           ┆ 1991)"]   ┆          │
│           ┆ on a s…   ┆ on a s…   ┆ on a s…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [322]:
# look at a row closely
row = claims.row(1, named=True)
print(row)

{'gene_id': 'DDB_G0290825', 'sentence_markers': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [[PUB:956]] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [[PUB:2919]].', 'sentence_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) (Austin et al. 2006) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH (Thompson and Kay, 2000).', 'cited_sentence_marked': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [CITE:956] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [CITE:2919].', 'claim_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH.', 'anchors': [{'pos': 144, 'pub_ids': [956]}, {'pos': 253, 'pub_ids': [2919]}], 'publication_ids': [956, 2919], 'citation_captions': ['(Austin et al. 2006)', '(Thompson and Kay, 2000)'], 'citation_years': [2006, 2000]}

In [323]:
# get preferred column set (same as before)
df = claims.select([
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id",
])

In [324]:
# clean up parentheses in citation_captions
df = df.with_columns(
    pl.col("citation_captions")
    .list.eval(
        pl.element()
        .str.replace_all(r"[()]", "")   # remove parentheses
        .str.replace_all(r"\s+", " ")   # collapse whitespace
        .str.strip_chars()              # <-- instead of .str.strip()
    )
    .alias("citation_captions")
)
# clean up comma
df = df.with_columns(
    pl.col("citation_captions")
    .list.eval(
        pl.element()
        .str.replace_all(r"[()]", "")
        .str.replace_all(r"\bet al\b\.?", "et al.")
        .str.replace_all(r",\s*et al\.", " et al.")
        .str.replace_all(r"et al\.\s*,\s*", "et al. ")
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
    )
    .alias("citation_captions")
)

In [325]:
# clean up very short claims, it shall have at least 6
min_words = 6

df2 = df.with_columns(
    # Count "words" by matching non-space sequences
    pl.col("claim_plain")
      .str.count_matches(r"\S+")
      .alias("n_words")
)

# 1) summary
summary = df2.select([
    pl.len().alias("rows_total"),
    (pl.col("n_words") < min_words).sum().alias("rows_to_drop"),
    (pl.col("n_words") >= min_words).sum().alias("rows_to_keep"),
])
print(summary)
# 2) inspect what you'd drop (optional)
to_drop = (
    df2.filter(pl.col("n_words") < min_words)
       .select(["n_words", "claim_plain", "gene_id"])
       .sort(["n_words", "claim_plain"])
)
with pl.Config(fmt_str_lengths=300):
    display(to_drop.head(50))

# 3) actually filter
df_filtered = df2.filter(pl.col("n_words") >= min_words).drop("n_words")

shape: (1, 3)
┌────────────┬──────────────┬──────────────┐
│ rows_total ┆ rows_to_drop ┆ rows_to_keep │
│ ---        ┆ ---          ┆ ---          │
│ u32        ┆ u32          ┆ u32          │
╞════════════╪══════════════╪══════════════╡
│ 2677       ┆ 24           ┆ 2653         │
└────────────┴──────────────┴──────────────┘

shape: (24, 3)
┌─────────┬───────────────────────────────────────┬──────────────┐
│ n_words ┆ claim_plain                           ┆ gene_id      │
│ ---     ┆ ---                                   ┆ ---          │
│ u32     ┆ str                                   ┆ str          │
╞═════════╪═══════════════════════════════════════╪══════════════╡
│ 1       ┆ .                                     ┆ DDB_G0284845 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267444 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267630 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0279183 │
│ 2       ┆ (gskA) (..                            ┆ DDB_G0281385 │
│ …       ┆ …                                     ┆ …            │
│ 5       ┆ STATa is downregulated by PTP1.       ┆ DDB_G0281381 │
│ 5       ┆ Spores have lower cellulose levels.   ┆ DDB_G0281387 │
│ 5       ┆ at the tipped aggregate stage.        ┆ DDB_G0286185 │
│ 5       ┆ cerevisiae, plp2, is also essential.. ┆ DDB_G0285433 │
│ 5       ┆ discoideum by regulating ROS levels.  ┆ DDB_G0288247 │
└─────────┴───────────────────────────────────────┴──────────────┘

In [326]:
# let us examine the duplicated claims closely
# 1) merge duplicates by concatenating gene_id (unique + sorted)
merged = (
    df_filtered
    .group_by([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .agg(
        pl.col("gene_id")
          .unique()
          .sort()
          .str.join(",")
          .alias("gene_id")
    )
    .select([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions",
        "gene_id",
    ])
)

print("after merge:")
print("rows =", merged.height)
print("unique claim_plain =", merged.select(pl.col("claim_plain").n_unique()).item())

# 2) check if claim_plain is STILL duplicated (i.e., same claim text but different citation/anchors/etc.)
still_dups = (
    merged
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain"])
)

print("still duplicated claim_plain rows =", still_dups.height)

# show them grouped together if any remain
still_dups

after merge:
rows = 2107
unique claim_plain = 2103
still duplicated claim_plain rows = 8

shape: (8, 6)
┌──────────────────┬─────────────────┬─────────────────┬──────────────────┬──────────────────┬─────┐
│ claim_plain      ┆ anchors         ┆ publication_ids ┆ citation_caption ┆ gene_id          ┆ n   │
│ ---              ┆ ---             ┆ ---             ┆ s                ┆ ---              ┆ --- │
│ str              ┆ list[struct[2]] ┆ list[i64]       ┆ ---              ┆ str              ┆ u32 │
│                  ┆                 ┆                 ┆ list[str]        ┆                  ┆     │
╞══════════════════╪═════════════════╪═════════════════╪══════════════════╪══════════════════╪═════╡
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser et al.  ┆ DDB_G0267402,DDB ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ 1995"]           ┆ _G0270838,DDB_…  ┆     │
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser and     ┆ DDB_G0285319     ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ colleagues       ┆                  ┆     │
│                  ┆                 ┆                 ┆ 1995"]           ┆                  ┆     │
│ The 2C gene as   ┆ [{149,[10129]}] ┆ [10129]         ┆ ["Schilde et al. ┆ DDB_G0280871,DDB ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆ _G0280953,DDB_…  ┆     │
│ The 2C gene as   ┆ [{149,[1381]}]  ┆ [1381]          ┆ ["Schilde et al. ┆ DDB_G0280847     ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆                  ┆     │
│ These mutant     ┆ [{148,[2842]}]  ┆ [2842]          ┆ ["Wessels et al. ┆ DDB_G0284331     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2000"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ These mutant     ┆ [{148,[1548]}]  ┆ [1548]          ┆ ["Zhang et al.   ┆ DDB_G0279413     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2003"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ abcF1 and abcF4  ┆ [{115,[2279]}]  ┆ [2279]          ┆ ["Anjard and     ┆ DDB_G0285997     ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆                  ┆     │
│ abcF1 and abcF4  ┆ [{115,[8189]}]  ┆ [8189]          ┆ ["Anjard and     ┆ DDB_G0267436,DDB ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆ _G0275637,DDB_…  ┆     │
└──────────────────┴─────────────────┴─────────────────┴──────────────────┴──────────────────┴─────┘

In [327]:
# with pl.Config(fmt_str_lengths=60):
#     display(still_dups)

There are some duplicated claims.

Except the first one, the others are claims with inconsistant citations, let us remove those except the first one.

In [328]:
# 1) add a stable row id to merged
merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

# 2) recompute still_dups from merged_i (so it contains row_nr)
still_dups_i = (
    merged_i
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain", "row_nr"])
)

# 3) drop everything in still_dups except the first row of still_dups
drop_row_nrs = still_dups_i.slice(1).select("row_nr")   # everything after the first row

merged_clean = (
    merged_i
    .join(drop_row_nrs, on="row_nr", how="anti")  # remove those rows
    .drop(["row_nr", "n"], strict=False)
)

/var/folders/yr/ljjqmpj92wncw9wrv495wq300000gn/T/ipykernel_50959/3282369987.py:2: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

In [329]:
merged_clean

shape: (2_100, 5)
┌─────────────────────┬─────────────────────┬─────────────────┬─────────────────────┬──────────────┐
│ claim_plain         ┆ anchors             ┆ publication_ids ┆ citation_captions   ┆ gene_id      │
│ ---                 ┆ ---                 ┆ ---             ┆ ---                 ┆ ---          │
│ str                 ┆ list[struct[2]]     ┆ list[i64]       ┆ list[str]           ┆ str          │
╞═════════════════════╪═════════════════════╪═════════════════╪═════════════════════╪══════════════╡
│ It was shown that   ┆ [{147,[6393]}]      ┆ [6393]          ┆ ["Medley et al.     ┆ DDB_G0291231 │
│ MHCK A activ…       ┆                     ┆                 ┆ 1990"]              ┆              │
│ The combination of  ┆ [{197,[3083]}]      ┆ [3083]          ┆ ["Geissler et al.   ┆ DDB_G0292262 │
│ a myosin mo…        ┆                     ┆                 ┆ 2000"]              ┆              │
│ However, Nhe1 has   ┆ [{159,[13]}]        ┆ [13]            ┆ ["Lusche et al.     ┆ DDB_G0275711 │
│ been shown t…       ┆                     ┆                 ┆ 2011"]              ┆              │
│ RasG also regulates ┆ [{111,[824]},       ┆ [824, 1464, …   ┆ ["Bolourani et al.  ┆ DDB_G0293434 │
│ the plasma…         ┆ {114,[1464]}, … …   ┆ 17325]          ┆ 2006", "Sas…        ┆              │
│ These results       ┆ [{178,[286]}]       ┆ [286]           ┆ ["Parkinson et al.  ┆ DDB_G0282247 │
│ indicate that ra…   ┆                     ┆                 ┆ 2009"]              ┆              │
│ …                   ┆ …                   ┆ …               ┆ …                   ┆ …            │
│ This could explain  ┆ [{53,[1321]}]       ┆ [1321]          ┆ ["Ehrenman et al.   ┆ DDB_G0293850 │
│ why alrA - …        ┆                     ┆                 ┆ 2004"]              ┆              │
│ TagC is a composite ┆ [{90,[4883]}]       ┆ [4883]          ┆ ["Shaulsky et al.   ┆ DDB_G0286121 │
│ protein in…         ┆                     ┆                 ┆ 1995"]              ┆              │
│ Measurements of the ┆ [{225,[10645]}]     ┆ [10645]         ┆ ["Loomis et al.     ┆ DDB_G0287033 │
│ specific a…         ┆                     ┆                 ┆ 1969"]              ┆              │
│ In addition,        ┆ [{88,[213]}]        ┆ [213]           ┆ ["Kastner et al.    ┆ DDB_G0278457 │
│ several proteins …  ┆                     ┆                 ┆ 2011"]              ┆              │
│ rpkA is a member of ┆ [{250,[825]}]       ┆ [825]           ┆ ["Bakthavatsalam et ┆ DDB_G0283615 │
│ a characte…         ┆                     ┆                 ┆ al. 2006"]          ┆              │
└─────────────────────┴─────────────────────┴─────────────────┴─────────────────────┴──────────────┘

In [330]:
# give claim ID, and we want to explode the list columns together to get one row per (claim_id, publication_id)
m = merged_clean.with_columns(
    pl.col("claim_plain").rank(method="dense").cast(pl.Int64).alias("claim_id")
).select([
    "claim_id",
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id"
])

In [332]:
# 2) sanity check: list columns must be aligned per row before explode (len(citation_captions) == len(publication_ids))
bad_rows = (
    m
    .with_columns([
        pl.col("publication_ids").list.len().alias("n_pub"),
        pl.col("citation_captions").list.len().alias("n_cap")
    ])
    .filter(
        (pl.col("n_pub") != pl.col("n_cap")) 
    )
    .select([
        "claim_id",
        "gene_id",
        "n_pub", "n_cap", 
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .sort(["n_pub", "n_cap"], descending=True)
)

print("Number of misaligned rows:", bad_rows.height)

with pl.Config(fmt_str_lengths=1000):
    display(bad_rows)

Number of misaligned rows: 4

shape: (4, 8)
┌──────────┬──────────────┬───────┬───────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ claim_id ┆ gene_id      ┆ n_pub ┆ n_cap ┆ claim_plain  ┆ anchors     ┆ publication ┆ citation_ca │
│ ---      ┆ ---          ┆ ---   ┆ ---   ┆ ---          ┆ ---         ┆ _ids        ┆ ptions      │
│ i64      ┆ str          ┆ u32   ┆ u32   ┆ str          ┆ list[struct ┆ ---         ┆ ---         │
│          ┆              ┆       ┆       ┆              ┆ [2]]        ┆ list[i64]   ┆ list[str]   │
╞══════════╪══════════════╪═══════╪═══════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1469     ┆ DDB_G0293084 ┆ 2     ┆ 1     ┆ The zizB     ┆ [{147,[1209 ┆ [12098,     ┆ ["Pakes et  │
│          ┆              ┆       ┆       ┆ mutant       ┆ 8]}, {148,[ ┆ 12830]      ┆ al. 2012"]  │
│          ┆              ┆       ┆       ┆ phenotypes   ┆ 12830]}]    ┆             ┆             │
│          ┆              ┆       ┆       ┆ and ZizB     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ binding      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ partners     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ suggest a    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ central role ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ for ZizB in  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ actin        ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cytoskeletal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ organization ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and cortical ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ stabilizatio ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ n.,.         ┆             ┆             ┆             │
│ 471      ┆ DDB_G0268620 ┆ 2     ┆ 1     ┆ Fluid uptake ┆ [{113,[2428 ┆ [2428,      ┆ ["Rupper et │
│          ┆              ┆       ┆       ┆ by macropino ┆ ]}, {116,[2 ┆ 2634]       ┆ al. 2001"]  │
│          ┆              ┆       ┆       ┆ cytosis is   ┆ 634]}]      ┆             ┆             │
│          ┆              ┆       ┆       ┆ reduced      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ about 3 fold ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and          ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ phagosomes   ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ remain more  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ acidic in    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ pkbA - null  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cells (, (.  ┆             ┆             ┆             │
│ 1534     ┆ DDB_G0287031 ┆ 2     ┆ 1     ┆ These        ┆ [{92,[4035] ┆ [4035,      ┆ ["Brandon   │
│          ┆              ┆       ┆       ┆ results      ┆ }, {93,[403 ┆ 4034]       ┆ et al.      │
│          ┆              ┆       ┆       ┆ reveal that  ┆ 4]}]        ┆             ┆ 1997"]      │
│          ┆              ┆       ┆       ┆ gpaC         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ functions as ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ a regulator  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ of early     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ development  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ gene         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ expression,. ┆             ┆             ┆             │
│ 1195     ┆ DDB_G0286183 ┆ 2     ┆ 1     ┆ The Dictyost ┆ [{52,[712,  ┆ [712, 659]  ┆ ["Razeto et │
│          ┆              ┆       ┆       ┆ elium Agps   ┆ 659]}]      ┆             ┆ al. .,      │
│          ┆              ┆       ┆       ┆ protein has  ┆             ┆             ┆ 2007"]      │
│          ┆              ┆       ┆       ┆ been crystal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ lized.       ┆             ┆             ┆             │
└──────────┴──────────────┴───────┴───────┴──────────────┴─────────────┴─────────────┴─────────────┘

in the 4 cases here, len(publication_ids)>len(citation_captions), after closer look, it is the same author and same year, we manully make a patch here

In [333]:
m_fixed = (
    m.with_columns(
        pl.when(pl.col("claim_id") == 1534)
          .then(pl.lit(["Brandon et al. 1997a", "Brandon et al. 1997b"]))
        .when(pl.col("claim_id") == 471)
          .then(pl.lit(["Rupper et al. 2001a", "Rupper et al. 2001b"]))
        .when(pl.col("claim_id") == 1469)
          .then(pl.lit(["Pakes et al. 2012a", "Pakes et al. 2012b"]))
        .when(pl.col("claim_id") == 1195)
          .then(pl.lit(["Razeto et al. 2007a", "Razeto et al. 2007b"]))
        .otherwise(pl.col("citation_captions"))
        .alias("citation_captions")
    )
)

In [334]:
m_long = (
    m_fixed
    .explode(["publication_ids", "citation_captions"])
    .rename({"publication_ids": "publication_id"})
)

In [335]:
m_long

shape: (2_661, 6)
┌──────────┬──────────────────┬──────────────────┬────────────────┬─────────────────┬──────────────┐
│ claim_id ┆ claim_plain      ┆ anchors          ┆ publication_id ┆ citation_captio ┆ gene_id      │
│ ---      ┆ ---              ┆ ---              ┆ ---            ┆ ns              ┆ ---          │
│ i64      ┆ str              ┆ list[struct[2]]  ┆ i64            ┆ ---             ┆ str          │
│          ┆                  ┆                  ┆                ┆ str             ┆              │
╞══════════╪══════════════════╪══════════════════╪════════════════╪═════════════════╪══════════════╡
│ 793      ┆ It was shown     ┆ [{147,[6393]}]   ┆ 6393           ┆ Medley et al.   ┆ DDB_G0291231 │
│          ┆ that MHCK A      ┆                  ┆                ┆ 1990            ┆              │
│          ┆ activ…           ┆                  ┆                ┆                 ┆              │
│ 1276     ┆ The combination  ┆ [{197,[3083]}]   ┆ 3083           ┆ Geissler et al. ┆ DDB_G0292262 │
│          ┆ of a myosin mo…  ┆                  ┆                ┆ 2000            ┆              │
│ 578      ┆ However, Nhe1    ┆ [{159,[13]}]     ┆ 13             ┆ Lusche et al.   ┆ DDB_G0275711 │
│          ┆ has been shown   ┆                  ┆                ┆ 2011            ┆              │
│          ┆ t…               ┆                  ┆                ┆                 ┆              │
│ 1076     ┆ RasG also        ┆ [{111,[824]},    ┆ 824            ┆ Bolourani et    ┆ DDB_G0293434 │
│          ┆ regulates the    ┆ {114,[1464]}, …  ┆                ┆ al. 2006        ┆              │
│          ┆ plasma…          ┆ …                ┆                ┆                 ┆              │
│ 1076     ┆ RasG also        ┆ [{111,[824]},    ┆ 1464           ┆ Sasaki et al.   ┆ DDB_G0293434 │
│          ┆ regulates the    ┆ {114,[1464]}, …  ┆                ┆ 2004            ┆              │
│          ┆ plasma…          ┆ …                ┆                ┆                 ┆              │
│ …        ┆ …                ┆ …                ┆ …              ┆ …               ┆ …            │
│ 1587     ┆ This could       ┆ [{53,[1321]}]    ┆ 1321           ┆ Ehrenman et al. ┆ DDB_G0293850 │
│          ┆ explain why alrA ┆                  ┆                ┆ 2004            ┆              │
│          ┆ - …              ┆                  ┆                ┆                 ┆              │
│ 1149     ┆ TagC is a        ┆ [{90,[4883]}]    ┆ 4883           ┆ Shaulsky et al. ┆ DDB_G0286121 │
│          ┆ composite        ┆                  ┆                ┆ 1995            ┆              │
│          ┆ protein in…      ┆                  ┆                ┆                 ┆              │
│ 832      ┆ Measurements of  ┆ [{225,[10645]}]  ┆ 10645          ┆ Loomis et al.   ┆ DDB_G0287033 │
│          ┆ the specific a…  ┆                  ┆                ┆ 1969            ┆              │
│ 693      ┆ In addition,     ┆ [{88,[213]}]     ┆ 213            ┆ Kastner et al.  ┆ DDB_G0278457 │
│          ┆ several proteins ┆                  ┆                ┆ 2011            ┆              │
│          ┆ …                ┆                  ┆                ┆                 ┆              │
│ 2061     ┆ rpkA is a member ┆ [{250,[825]}]    ┆ 825            ┆ Bakthavatsalam  ┆ DDB_G0283615 │
│          ┆ of a characte…   ┆                  ┆                ┆ et al. 2006     ┆              │
└──────────┴──────────────────┴──────────────────┴────────────────┴─────────────────┴──────────────┘

In [336]:
# now we exlpode anchors
# 1) Build mapping: (claim_id, publication_id) -> anchor_pos
anchor_map = (
    m_fixed
    .select(["claim_id", "anchors"])
    .explode("anchors")  # now each row is one struct {pos, pub_ids}
    .with_columns([
        pl.col("anchors").struct.field("pos").alias("anchor_pos"),
        pl.col("anchors").struct.field("pub_ids").alias("publication_id"),
    ])
    .explode("publication_id")  # one row per pub_id
    .select(["claim_id", "publication_id", "anchor_pos"])
)

# If there can be multiple anchor_pos for the same (claim_id, publication_id), keep them all:
anchor_map = (
    anchor_map
    .group_by(["claim_id", "publication_id"])
    .agg(pl.col("anchor_pos").sort().alias("anchor_pos"))
)

# 2) Join onto m_long
m_long2 = m_long.join(anchor_map, on=["claim_id", "publication_id"], how="left")

# 3) If you want exactly one row per (claim_id, publication_id, anchor_pos), explode anchor_pos:
m_long3 = m_long2.explode("anchor_pos")

# Final columns (example)
m_long3.select([
    "claim_id",
    "claim_plain",
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
])

shape: (2_668, 6)
┌──────────┬─────────────────────┬────────────┬────────────────┬────────────────────┬──────────────┐
│ claim_id ┆ claim_plain         ┆ anchor_pos ┆ publication_id ┆ citation_captions  ┆ gene_id      │
│ ---      ┆ ---                 ┆ ---        ┆ ---            ┆ ---                ┆ ---          │
│ i64      ┆ str                 ┆ i64        ┆ i64            ┆ str                ┆ str          │
╞══════════╪═════════════════════╪════════════╪════════════════╪════════════════════╪══════════════╡
│ 793      ┆ It was shown that   ┆ 147        ┆ 6393           ┆ Medley et al. 1990 ┆ DDB_G0291231 │
│          ┆ MHCK A activ…       ┆            ┆                ┆                    ┆              │
│ 1276     ┆ The combination of  ┆ 197        ┆ 3083           ┆ Geissler et al.    ┆ DDB_G0292262 │
│          ┆ a myosin mo…        ┆            ┆                ┆ 2000               ┆              │
│ 578      ┆ However, Nhe1 has   ┆ 159        ┆ 13             ┆ Lusche et al. 2011 ┆ DDB_G0275711 │
│          ┆ been shown t…       ┆            ┆                ┆                    ┆              │
│ 1076     ┆ RasG also regulates ┆ 111        ┆ 824            ┆ Bolourani et al.   ┆ DDB_G0293434 │
│          ┆ the plasma…         ┆            ┆                ┆ 2006               ┆              │
│ 1076     ┆ RasG also regulates ┆ 114        ┆ 1464           ┆ Sasaki et al. 2004 ┆ DDB_G0293434 │
│          ┆ the plasma…         ┆            ┆                ┆                    ┆              │
│ …        ┆ …                   ┆ …          ┆ …              ┆ …                  ┆ …            │
│ 1587     ┆ This could explain  ┆ 53         ┆ 1321           ┆ Ehrenman et al.    ┆ DDB_G0293850 │
│          ┆ why alrA - …        ┆            ┆                ┆ 2004               ┆              │
│ 1149     ┆ TagC is a composite ┆ 90         ┆ 4883           ┆ Shaulsky et al.    ┆ DDB_G0286121 │
│          ┆ protein in…         ┆            ┆                ┆ 1995               ┆              │
│ 832      ┆ Measurements of the ┆ 225        ┆ 10645          ┆ Loomis et al. 1969 ┆ DDB_G0287033 │
│          ┆ specific a…         ┆            ┆                ┆                    ┆              │
│ 693      ┆ In addition,        ┆ 88         ┆ 213            ┆ Kastner et al.     ┆ DDB_G0278457 │
│          ┆ several proteins …  ┆            ┆                ┆ 2011               ┆              │
│ 2061     ┆ rpkA is a member of ┆ 250        ┆ 825            ┆ Bakthavatsalam et  ┆ DDB_G0283615 │
│          ┆ a characte…         ┆            ┆                ┆ al. 2006           ┆              │
└──────────┴─────────────────────┴────────────┴────────────────┴────────────────────┴──────────────┘

In [337]:
# now we get year from citation_captions
YEAR_RE = r"(18|19|20)\d{2}"

m_long3 = m_long3.with_columns(
    year=pl.col("citation_captions")
        .str.extract(YEAR_RE, 0)   # whole match
        .cast(pl.Int32)
)
m_long3

shape: (2_668, 8)
┌──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬──────┐
│ claim_id ┆ claim_plain ┆ anchors     ┆ publication ┆ citation_c ┆ gene_id    ┆ anchor_pos ┆ year │
│ ---      ┆ ---         ┆ ---         ┆ _id         ┆ aptions    ┆ ---        ┆ ---        ┆ ---  │
│ i64      ┆ str         ┆ list[struct ┆ ---         ┆ ---        ┆ str        ┆ i64        ┆ i32  │
│          ┆             ┆ [2]]        ┆ i64         ┆ str        ┆            ┆            ┆      │
╞══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪══════╡
│ 793      ┆ It was      ┆ [{147,[6393 ┆ 6393        ┆ Medley et  ┆ DDB_G02912 ┆ 147        ┆ 1990 │
│          ┆ shown that  ┆ ]}]         ┆             ┆ al. 1990   ┆ 31         ┆            ┆      │
│          ┆ MHCK A      ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ activ…      ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1276     ┆ The         ┆ [{197,[3083 ┆ 3083        ┆ Geissler   ┆ DDB_G02922 ┆ 197        ┆ 2000 │
│          ┆ combination ┆ ]}]         ┆             ┆ et al.     ┆ 62         ┆            ┆      │
│          ┆ of a myosin ┆             ┆             ┆ 2000       ┆            ┆            ┆      │
│          ┆ mo…         ┆             ┆             ┆            ┆            ┆            ┆      │
│ 578      ┆ However,    ┆ [{159,[13]} ┆ 13          ┆ Lusche et  ┆ DDB_G02757 ┆ 159        ┆ 2011 │
│          ┆ Nhe1 has    ┆ ]           ┆             ┆ al. 2011   ┆ 11         ┆            ┆      │
│          ┆ been shown  ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ t…          ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1076     ┆ RasG also   ┆ [{111,[824] ┆ 824         ┆ Bolourani  ┆ DDB_G02934 ┆ 111        ┆ 2006 │
│          ┆ regulates   ┆ }, {114,[14 ┆             ┆ et al.     ┆ 34         ┆            ┆      │
│          ┆ the plasma… ┆ 64]}, … …   ┆             ┆ 2006       ┆            ┆            ┆      │
│ 1076     ┆ RasG also   ┆ [{111,[824] ┆ 1464        ┆ Sasaki et  ┆ DDB_G02934 ┆ 114        ┆ 2004 │
│          ┆ regulates   ┆ }, {114,[14 ┆             ┆ al. 2004   ┆ 34         ┆            ┆      │
│          ┆ the plasma… ┆ 64]}, … …   ┆             ┆            ┆            ┆            ┆      │
│ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …    │
│ 1587     ┆ This could  ┆ [{53,[1321] ┆ 1321        ┆ Ehrenman   ┆ DDB_G02938 ┆ 53         ┆ 2004 │
│          ┆ explain why ┆ }]          ┆             ┆ et al.     ┆ 50         ┆            ┆      │
│          ┆ alrA - …    ┆             ┆             ┆ 2004       ┆            ┆            ┆      │
│ 1149     ┆ TagC is a   ┆ [{90,[4883] ┆ 4883        ┆ Shaulsky   ┆ DDB_G02861 ┆ 90         ┆ 1995 │
│          ┆ composite   ┆ }]          ┆             ┆ et al.     ┆ 21         ┆            ┆      │
│          ┆ protein in… ┆             ┆             ┆ 1995       ┆            ┆            ┆      │
│ 832      ┆ Measurement ┆ [{225,[1064 ┆ 10645       ┆ Loomis et  ┆ DDB_G02870 ┆ 225        ┆ 1969 │
│          ┆ s of the    ┆ 5]}]        ┆             ┆ al. 1969   ┆ 33         ┆            ┆      │
│          ┆ specific a… ┆             ┆             ┆            ┆            ┆            ┆      │
│ 693      ┆ In          ┆ [{88,[213]} ┆ 213         ┆ Kastner et ┆ DDB_G02784 ┆ 88         ┆ 2011 │
│          ┆ addition,   ┆ ]           ┆             ┆ al. 2011   ┆ 57         ┆            ┆      │
│          ┆ several     ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ proteins …  ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2061     ┆ rpkA is a   ┆ [{250,[825] ┆ 825         ┆ Bakthavats ┆ DDB_G02836 ┆ 250        ┆ 2006 │
│          ┆ member of a ┆ }]          ┆             ┆ alam et    ┆ 15         ┆            ┆      │
│          ┆ characte…   ┆             ┆             ┆ al. 2006   ┆            ┆            ┆      │
└──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴──────┘

In [338]:
m_long4 = m_long3.select([
    "claim_id",
    "claim_plain",
    "anchors",        # keep if you still want the original struct list
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
    "year",
])

i still see some claims needs cleaned up. They are almost identical with only dot diffrenece.

In [339]:
claim_key_expr = (
    pl.col("claim_plain")
    .str.to_lowercase()
    .str.replace_all(r"\.{2,}", ".")          # ".." / "..." -> "."
    .str.replace_all(r"[^a-z0-9\s]", " ")     # drop punctuation
    .str.replace_all(r"\s+", " ")             # collapse whitespace
    .str.strip_chars()
)

tmp = m_long4.with_columns(
    claim_key=claim_key_expr
)

# Optional: see groups where multiple raw claim_plain map to same key
near_same = (
    tmp.group_by("claim_key")
       .agg([
           pl.len().alias("n_rows"),
           pl.col("claim_plain").n_unique().alias("n_variants"),
           pl.col("claim_plain"),
       ])
       .filter(pl.col("n_variants") > 1)
       .sort("n_rows", descending=True)
)
near_same

shape: (28, 4)
┌─────────────────────────────────┬────────┬────────────┬─────────────────────────────────┐
│ claim_key                       ┆ n_rows ┆ n_variants ┆ claim_plain                     │
│ ---                             ┆ ---    ┆ ---        ┆ ---                             │
│ str                             ┆ u32    ┆ u32        ┆ list[str]                       │
╞═════════════════════════════════╪════════╪════════════╪═════════════════════════════════╡
│ at the trailing edge activated… ┆ 9      ┆ 2          ┆ ["At the trailing edge activat… │
│ the major spore coat proteins … ┆ 9      ┆ 2          ┆ ["The major spore coat protein… │
│ dictyostelium has three genes … ┆ 6      ┆ 3          ┆ ["Dictyostelium has three gene… │
│ expression of cota sp96 cotb s… ┆ 6      ┆ 2          ┆ ["Expression of cotA (SP96), c… │
│ about 100 different proteins c… ┆ 6      ┆ 6          ┆ ["About 100 different proteins… │
│ …                               ┆ …      ┆ …          ┆ …                               │
│ these results suggest the exis… ┆ 2      ┆ 2          ┆ ["These results suggest the ex… │
│ the sevencalcium up regulated … ┆ 2      ┆ 2          ┆ ["The sevencalcium up-regulate… │
│ an increase in ubiquitin posit… ┆ 2      ┆ 2          ┆ ["An increase in ubiquitin-pos… │
│ differential expression of ecm… ┆ 2      ┆ 2          ┆ ["Differential expression of e… │
│ the myb motif has been well co… ┆ 2      ┆ 2          ┆ ["The Myb motif has been well … │
└─────────────────────────────────┴────────┴────────────┴─────────────────────────────────┘

yes, there are actually quite many near duplicates. shall be also merged

In [340]:
# 2) Create a new merged claim_id based on claim_key
tmp = tmp.with_columns(
    claim_id_new=pl.col("claim_key").rank(method="dense").cast(pl.Int64)
)

# 3) Merge rows safely and keep your column order
#    - choose a canonical claim_plain (first seen)
#    - merge gene_id as union joined by ","
claim_cleaned = (
    tmp
    .group_by([
        "claim_id_new",
        "publication_id",
        "citation_captions",
        "anchor_pos",
        "year",
    ])
    .agg([
        pl.first("claim_plain").alias("claim_plain"),
        pl.first("anchors").alias("anchors"),
        pl.col("gene_id").unique().sort().str.join(",").alias("gene_id"),
    ])
    .select([
        pl.col("claim_id_new").alias("claim_id"),
        "claim_plain",
        "anchors",
        "publication_id",
        "citation_captions",
        "gene_id",
        "anchor_pos",
        "year",
    ])
    .sort(["claim_id", "publication_id", "anchor_pos"])
)

claim_cleaned

shape: (2_636, 8)
┌──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬──────┐
│ claim_id ┆ claim_plain ┆ anchors     ┆ publication ┆ citation_c ┆ gene_id    ┆ anchor_pos ┆ year │
│ ---      ┆ ---         ┆ ---         ┆ _id         ┆ aptions    ┆ ---        ┆ ---        ┆ ---  │
│ i64      ┆ str         ┆ list[struct ┆ ---         ┆ ---        ┆ str        ┆ i64        ┆ i32  │
│          ┆             ┆ [2]]        ┆ i64         ┆ str        ┆            ┆            ┆      │
╞══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪══════╡
│ 1        ┆ A basic     ┆ [{94,[13954 ┆ 13954       ┆ Brzeska et ┆ DDB_G02891 ┆ 94         ┆ 2014 │
│          ┆ region in   ┆ ]}]         ┆             ┆ al. 2014   ┆ 17         ┆            ┆      │
│          ┆ the tail is ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ …           ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2        ┆ A cDNA      ┆ [{102,[8316 ┆ 8316        ┆ Barklis    ┆ DDB_G02768 ┆ 102        ┆ 1983 │
│          ┆ clone       ┆ ]}]         ┆             ┆ and Lodish ┆ 69         ┆            ┆      │
│          ┆ derived     ┆             ┆             ┆ 1983       ┆            ┆            ┆      │
│          ┆ from psvA…  ┆             ┆             ┆            ┆            ┆            ┆      │
│ 3        ┆ A cDNA      ┆ [{89,[8283] ┆ 8283        ┆ Chisholm   ┆ DDB_G02674 ┆ 89         ┆ 1984 │
│          ┆ clone of    ┆ }]          ┆             ┆ et al.     ┆ 12         ┆            ┆      │
│          ┆ this gene,  ┆             ┆             ┆ 1984       ┆            ┆            ┆      │
│          ┆ D19…        ┆             ┆             ┆            ┆            ┆            ┆      │
│ 4        ┆ A co-immuno ┆ [{158,[1972 ┆ 19729       ┆ Li et al.  ┆ DDB_G02746 ┆ 158        ┆ 2020 │
│          ┆ precipitati ┆ 9]}]        ┆             ┆ 2020       ┆ 07         ┆            ┆      │
│          ┆ on assay…   ┆             ┆             ┆            ┆            ┆            ┆      │
│ 5        ┆ A           ┆ [{185,[1315 ┆ 13151       ┆ Galardi-Ca ┆ DDB_G02689 ┆ 185        ┆ 2013 │
│          ┆ comparison  ┆ 1]}]        ┆             ┆ stilla et  ┆ 20         ┆            ┆      │
│          ┆ of the      ┆             ┆             ┆ al. 2013   ┆            ┆            ┆      │
│          ┆ genes tran… ┆             ┆             ┆            ┆            ┆            ┆      │
│ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …    │
│ 2059     ┆ Yet another ┆ [{131,[4899 ┆ 4899        ┆ Sonnemann  ┆ DDB_G02730 ┆ 131        ┆ 1995 │
│          ┆ role for    ┆ ]}]         ┆             ┆ and Mutzel ┆ 69,DDB_G02 ┆            ┆      │
│          ┆ NDP kinas…  ┆             ┆             ┆ 1995       ┆ 73805      ┆            ┆      │
│ 2060     ┆ zizA null   ┆ [{72,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02750 ┆ 72         ┆ 2012 │
│          ┆ mutant      ┆ ]}]         ┆             ┆ al. 2012   ┆ 35         ┆            ┆      │
│          ┆ cells do    ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ not …       ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2061     ┆ ZizB also   ┆ [{106,[1209 ┆ 12098       ┆ Pakes et   ┆ DDB_G02673 ┆ 106        ┆ 2012 │
│          ┆ interacts   ┆ 8]}]        ┆             ┆ al. 2012   ┆ 74,DDB_G02 ┆            ┆      │
│          ┆ with sever… ┆             ┆             ┆            ┆ 72104      ┆            ┆      │
│ 2062     ┆ zizC is     ┆ [{51,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02752 ┆ 51         ┆ 2012 │
│          ┆ expressed   ┆ ]}]         ┆             ┆ al. 2012   ┆ 39         ┆            ┆      │
│          ┆ throughout  ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ g…          ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2063     ┆ zizD is     ┆ [{51,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02688 ┆ 51         ┆ 2012 │
│          ┆ expressed   ┆ ]}]         ┆             ┆ al. 2012   ┆ 88         ┆            ┆      │
│          ┆ throughout  ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ g…          ┆             ┆             ┆            ┆            ┆            ┆      │
└──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴──────┘

In [341]:
year_summary = (
    claim_cleaned
    .with_columns(pl.col("year").fill_null(-1).alias("year2"))
    .group_by("year2")
    .agg(pl.len().alias("n"))
    .sort("year2")
    .with_columns(
        pl.when(pl.col("year2") == -1).then(None).otherwise(pl.col("year2")).alias("year")
    )
    .select(["year", "n"])
)

year_summary

shape: (55, 2)
┌──────┬─────┐
│ year ┆ n   │
│ ---  ┆ --- │
│ i32  ┆ u32 │
╞══════╪═════╡
│ null ┆ 7   │
│ 1956 ┆ 1   │
│ 1965 ┆ 1   │
│ 1967 ┆ 3   │
│ 1968 ┆ 1   │
│ …    ┆ …   │
│ 2016 ┆ 76  │
│ 2017 ┆ 58  │
│ 2018 ┆ 81  │
│ 2019 ┆ 85  │
│ 2020 ┆ 34  │
└──────┴─────┘

In [342]:
claim_cleaned.write_parquet("output/cleaned/claim_cleaned_long.parquet")

In [343]:
claim_cleaned.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2063              │
└───────────────────┘

In [344]:
(
    claim_cleaned
    .drop("anchors")
    .write_csv("output/cleaned/claim_cleaned_long.tsv", separator="\t")
)

I still see some duplicated claims. There are still a few edge cases. But at this point, I am not gonna trying to “perfectly” clean. I will try to pick up a golden set out of it.

In [319]:
# manual inspection, will pick some golden set maunally later
claim_cleaned_manual = claim_cleaned.filter(pl.col("anchor_pos") != 1)
# claim_cleaned_gold=...

# match pmid

In [345]:
pub_pmid = pl.read_csv("output/publication_id_pmid.csv")
pub_pmid

shape: (4_341, 2)
┌────────────────┬──────────┐
│ publication_id ┆ pmid     │
│ ---            ┆ ---      │
│ i64            ┆ i64      │
╞════════════════╪══════════╡
│ 12             ┆ 21243421 │
│ 13             ┆ 21239624 │
│ 15             ┆ 21235525 │
│ 17             ┆ 20950684 │
│ 20             ┆ 21150268 │
│ …              ┆ …        │
│ 19689          ┆ 32769116 │
│ 19708          ┆ 21551065 │
│ 19728          ┆ 32821814 │
│ 19729          ┆ 32818671 │
│ 19748          ┆ 32850852 │
└────────────────┴──────────┘

In [346]:
# check if all publcation id can be mapped to pmid

# pick the right df names
a = claim_cleaned
b = pub_pmid

# make sure both publication_id columns are the same type (I recommend Int64)
a_ids = a.select(pl.col("publication_id").cast(pl.Int64)).unique()
b_ids = b.select(pl.col("publication_id").cast(pl.Int64)).unique()

# overlap + only-in sets
overlap = a_ids.join(b_ids, on="publication_id", how="inner")
only_a  = a_ids.join(b_ids, on="publication_id", how="anti")
only_b  = b_ids.join(a_ids, on="publication_id", how="anti")

summary = pl.DataFrame({
    "set": ["claim_cleaned", "pub_pmid", "overlap", "only_claim_cleaned", "only_pub_pmid"],
    "unique_count": [a_ids.height, b_ids.height, overlap.height, only_a.height, only_b.height],
})

summary

shape: (5, 2)
┌────────────────────┬──────────────┐
│ set                ┆ unique_count │
│ ---                ┆ ---          │
│ str                ┆ i64          │
╞════════════════════╪══════════════╡
│ claim_cleaned      ┆ 1400         │
│ pub_pmid           ┆ 4341         │
│ overlap            ┆ 1373         │
│ only_claim_cleaned ┆ 27           │
│ only_pub_pmid      ┆ 2968         │
└────────────────────┴──────────────┘

27 ids are not mapped.

In [347]:
claim_cleaned_pmid = (
    claim_cleaned
    .with_columns(pl.col("publication_id").cast(pl.Int64))
    .join(pub_pmid, on="publication_id", how="left")
    .with_columns(
        pl.col("pmid").fill_null("NA")  # or keep as null if you prefer
    )
)

claim_cleaned_pmid

shape: (2_636, 9)
┌──────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ gene_id    ┆ anchor_pos ┆ year ┆ pmid     │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---        ┆ ---        ┆ ---  ┆ ---      │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ str        ┆ i64        ┆ i32  ┆ str      │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆            ┆            ┆      ┆          │
╞══════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 1        ┆ A basic     ┆ [{94,[1395 ┆ 13954      ┆ … ┆ DDB_G02891 ┆ 94         ┆ 2014 ┆ 24747353 │
│          ┆ region in   ┆ 4]}]       ┆            ┆   ┆ 17         ┆            ┆      ┆          │
│          ┆ the tail is ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2        ┆ A cDNA      ┆ [{102,[831 ┆ 8316       ┆ … ┆ DDB_G02768 ┆ 102        ┆ 1983 ┆ 6301681  │
│          ┆ clone       ┆ 6]}]       ┆            ┆   ┆ 69         ┆            ┆      ┆          │
│          ┆ derived     ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ from psvA…  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 3        ┆ A cDNA      ┆ [{89,[8283 ┆ 8283       ┆ … ┆ DDB_G02674 ┆ 89         ┆ 1984 ┆ 6429548  │
│          ┆ clone of    ┆ ]}]        ┆            ┆   ┆ 12         ┆            ┆      ┆          │
│          ┆ this gene,  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ D19…        ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 4        ┆ A co-immuno ┆ [{158,[197 ┆ 19729      ┆ … ┆ DDB_G02746 ┆ 158        ┆ 2020 ┆ 32818671 │
│          ┆ precipitati ┆ 29]}]      ┆            ┆   ┆ 07         ┆            ┆      ┆          │
│          ┆ on assay…   ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 5        ┆ A           ┆ [{185,[131 ┆ 13151      ┆ … ┆ DDB_G02689 ┆ 185        ┆ 2013 ┆ 23577638 │
│          ┆ comparison  ┆ 51]}]      ┆            ┆   ┆ 20         ┆            ┆      ┆          │
│          ┆ of the      ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ genes tran… ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …        │
│ 2059     ┆ Yet another ┆ [{131,[489 ┆ 4899       ┆ … ┆ DDB_G02730 ┆ 131        ┆ 1995 ┆ 7733916  │
│          ┆ role for    ┆ 9]}]       ┆            ┆   ┆ 69,DDB_G02 ┆            ┆      ┆          │
│          ┆ NDP kinas…  ┆            ┆            ┆   ┆ 73805      ┆            ┆      ┆          │
│ 2060     ┆ zizA null   ┆ [{72,[1209 ┆ 12098      ┆ … ┆ DDB_G02750 ┆ 72         ┆ 2012 ┆ 22366457 │
│          ┆ mutant      ┆ 8]}]       ┆            ┆   ┆ 35         ┆            ┆      ┆          │
│          ┆ cells do    ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ not …       ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2061     ┆ ZizB also   ┆ [{106,[120 ┆ 12098      ┆ … ┆ DDB_G02673 ┆ 106        ┆ 2012 ┆ 22366457 │
│          ┆ interacts   ┆ 98]}]      ┆            ┆   ┆ 74,DDB_G02 ┆            ┆      ┆          │
│          ┆ with sever… ┆            ┆            ┆   ┆ 72104      ┆            ┆      ┆          │
│ 2062     ┆ zizC is     ┆ [{51,[1209 ┆ 12098      ┆ … ┆ DDB_G02752 ┆ 51         ┆ 2012 ┆ 22366457 │
│          ┆ expressed   ┆ 8]}]       ┆            ┆   ┆ 39         ┆            ┆      ┆          │
│          ┆ throughout  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ g…          ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2063     ┆ zizD is     ┆ [{51,[1209 ┆ 12098      ┆ … ┆ DDB_G02688 ┆ 51         ┆ 2012 ┆ 22366457 │
│          ┆ expressed   ┆ 8]}]       ┆            ┆   ┆ 88         ┆            ┆      ┆          │
│          ┆ throughout  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ g…          ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
└──────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

In [348]:
claim_cleaned_pmid.write_parquet("output/cleaned/claim_cleaned_long_pmids.parquet")

claim_cleaned_pmid_nonNA = claim_cleaned_pmid.filter(
    pl.col("pmid").is_not_null() & (pl.col("pmid") != "NA")
)

claim_cleaned_pmid_nonNA.write_parquet("output/cleaned/claim_cleaned_long_pmids_nonNA.parquet")

In [349]:
claim_cleaned_pmid_nonNA.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2040              │
└───────────────────┘

# how many we claims having abstracts on EPMC

In [350]:
EPMC = pl.read_parquet("output/cleaned/articles_all_cleaned_abstract.parquet")

In [351]:
EPMC

shape: (20_447, 9)
┌──────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ pmid     ┆ pmcid      ┆ doi        ┆ year ┆ … ┆ journal    ┆ authors    ┆ abstract_c ┆ file      │
│ ---      ┆ ---        ┆ ---        ┆ ---  ┆   ┆ ---        ┆ ---        ┆ lean       ┆ ---       │
│ str      ┆ str        ┆ str        ┆ str  ┆   ┆ str        ┆ str        ┆ ---        ┆ str       │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ str        ┆           │
╞══════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2654141  ┆ PMC2115546 ┆ 10.1083/jc ┆ 1989 ┆ … ┆ The        ┆ Sanders    ┆ Chlamydomo ┆ article_f │
│          ┆            ┆ b.108.5.17 ┆      ┆   ┆ Journal of ┆ MA,        ┆ nas cells  ┆ etching/o │
│          ┆            ┆ 51         ┆      ┆   ┆ cell       ┆ Salisbury  ┆ excise     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ biology    ┆ JL.        ┆ the…       ┆ _cl…      │
│ 39528565 ┆ PMC1155504 ┆ 10.1038/s4 ┆ 2024 ┆ … ┆ Nature com ┆ Lim YJ,    ┆ Plant      ┆ article_f │
│          ┆ 5          ┆ 1467-024-5 ┆      ┆   ┆ munication ┆ Yoon YJ,   ┆ pathogens  ┆ etching/o │
│          ┆            ┆ 4272-4     ┆      ┆   ┆ s          ┆ Lee H,     ┆ secrete    ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Choi G…    ┆ nuclea…    ┆ _cl…      │
│ 6319129  ┆ null       ┆ 10.1111/j. ┆ 1984 ┆ … ┆ European   ┆ Scholübber ┆ The        ┆ article_f │
│          ┆            ┆ 1432-1033. ┆      ┆   ┆ journal of ┆ s HG, van  ┆ ability of ┆ etching/o │
│          ┆            ┆ 1984.tb078 ┆      ┆   ┆ biochemist ┆ Knippenber ┆ 24 systema ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆ …          ┆ …          ┆ tical…     ┆ _cl…      │
│ 28740830 ┆ PMC5502327 ┆ 10.3389/fo ┆ 2017 ┆ … ┆ Frontiers  ┆ Mammucari  ┆ Mitochondr ┆ article_f │
│          ┆            ┆ nc.2017.00 ┆      ┆   ┆ in         ┆ C,         ┆ ial Ca2+   ┆ etching/o │
│          ┆            ┆ 139        ┆      ┆   ┆ oncology   ┆ Gherardi   ┆ uptake     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ G, Rizzu…  ┆ play…      ┆ _cl…      │
│ 18814278 ┆ null       ┆ 10.1002/cm ┆ 2008 ┆ … ┆ Cell       ┆ Asano Y,   ┆ Chemotaxis ┆ article_f │
│          ┆            ┆ .20314     ┆      ┆   ┆ motility   ┆ Nagasaki   ┆ -deficient ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆ and the    ┆ A, Uyeda   ┆ amiB-null… ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ cytoskel…  ┆ TQ.        ┆            ┆ _cl…      │
│ …        ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 36543032 ┆ PMC9889102 ┆ 10.1016/j. ┆ 2023 ┆ … ┆ European   ┆ Smith JD,  ┆ Muscle     ┆ article_f │
│          ┆            ┆ ejmech.202 ┆      ┆   ┆ journal of ┆ Brawley J, ┆ myosin     ┆ etching/o │
│          ┆            ┆ 2.115008   ┆      ┆   ┆ medicinal  ┆ Bordenave… ┆ inhibition ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ …          ┆            ┆ could…     ┆ _cl…      │
│ 20023070 ┆ PMC2823002 ┆ 10.1128/ec ┆ 2010 ┆ … ┆ Eukaryotic ┆ Schilde C, ┆ We have    ┆ article_f │
│          ┆            ┆ .00220-09  ┆      ┆   ┆ cell       ┆ Schönemann ┆ identified ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆            ┆ B, Sehri…  ┆ new        ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ synapto…   ┆ _cl…      │
│ 10706824 ┆ null       ┆ 10.1006/sc ┆ 1999 ┆ … ┆ Seminars   ┆ Mohanty S, ┆ The        ┆ article_f │
│          ┆            ┆ db.1999.03 ┆      ┆   ┆ in cell &  ┆ Firtel RA. ┆ spatial    ┆ etching/o │
│          ┆            ┆ 43         ┆      ┆   ┆ developmen ┆            ┆ patterning ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ t…         ┆            ┆ of pres…   ┆ _cl…      │
│ 39396247 ┆ PMC1148569 ┆ 10.1080/19 ┆ 2024 ┆ … ┆ Gut        ┆ Roy M,     ┆ Metabolic  ┆ article_f │
│          ┆ 4          ┆ 490976.202 ┆      ┆   ┆ microbes   ┆ Dumay A,   ┆ syndrome   ┆ etching/o │
│          ┆            ┆ 4.2409210  ┆      ┆   ┆            ┆ Adiba S,   ┆ (MetS) is  ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Rozes…     ┆ a…         ┆ _cl…      │
│ 18460092 ┆ PMC2666851 ┆ 10.1111/j. ┆ 2008 ┆ … ┆ Evolution  ┆ Okoruwa    ┆ Prestin    ┆ article_f │
│          ┆            ┆ 1525-142x. ┆      ┆   ┆ & developm ┆ OE, Weston ┆ (SLC26A5)  ┆ etching/o │
│          ┆            ┆ 2008.00239 ┆      ┆   ┆ ent        ┆ MD,        ┆ is the     ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆            ┆ Sanjeev…   ┆ molec…     ┆ _cl…      │
└──────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [352]:
a = claim_cleaned_pmid_nonNA.select(pl.col("pmid").cast(pl.Utf8).alias("pmid")).unique()
b = EPMC.select(pl.col("pmid").cast(pl.Utf8).alias("pmid")).unique()

overlap = a.join(b, on="pmid", how="inner")
only_a  = a.join(b, on="pmid", how="anti")
only_b  = b.join(a, on="pmid", how="anti")

summary = pl.DataFrame({
    "set": ["claim_cleaned_pmid_nonNA", "epmc_df", "overlap", "only_claim_cleaned_pmid", "only_epmc_df"],
    "unique_count": [a.height, b.height, overlap.height, only_a.height, only_b.height],
})

summary

shape: (5, 2)
┌──────────────────────────┬──────────────┐
│ set                      ┆ unique_count │
│ ---                      ┆ ---          │
│ str                      ┆ i64          │
╞══════════════════════════╪══════════════╡
│ claim_cleaned_pmid_nonNA ┆ 1372         │
│ epmc_df                  ┆ 20447        │
│ overlap                  ┆ 1340         │
│ only_claim_cleaned_pmid  ┆ 32           │
│ only_epmc_df             ┆ 19107        │
└──────────────────────────┴──────────────┘

In [353]:
only_claim_pmids = only_a.get_column("pmid")

rows_only_claim = claim_cleaned_pmid.filter(
    pl.col("pmid").cast(pl.Utf8).is_in(only_claim_pmids)
)

rows_only_claim

/var/folders/yr/ljjqmpj92wncw9wrv495wq300000gn/T/ipykernel_50959/496506703.py:3: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  rows_only_claim = claim_cleaned_pmid.filter(

shape: (43, 9)
┌──────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ gene_id    ┆ anchor_pos ┆ year ┆ pmid     │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---        ┆ ---        ┆ ---  ┆ ---      │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ str        ┆ i64        ┆ i32  ┆ str      │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆            ┆            ┆      ┆          │
╞══════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 98       ┆ Adenylyl    ┆ [{133,[978 ┆ 9781       ┆ … ┆ DDB_G02815 ┆ 133        ┆ 1977 ┆ 191758   │
│          ┆ cyclase     ┆ 1]}, {136, ┆            ┆   ┆ 45         ┆            ┆      ┆          │
│          ┆ increases   ┆ [10027]},  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ mor…        ┆ …          ┆            ┆   ┆            ┆            ┆      ┆          │
│ 98       ┆ Adenylyl    ┆ [{133,[978 ┆ 10027      ┆ … ┆ DDB_G02815 ┆ 136        ┆ 1976 ┆ 183985   │
│          ┆ cyclase     ┆ 1]}, {136, ┆            ┆   ┆ 45         ┆            ┆      ┆          │
│          ┆ increases   ┆ [10027]},  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ mor…        ┆ …          ┆            ┆   ┆            ┆            ┆      ┆          │
│ 200      ┆ axeB was    ┆ [{139,[102 ┆ 10264      ┆ … ┆ DDB_G03506 ┆ 139        ┆ 1974 ┆ 4474353  │
│          ┆ identified  ┆ 64]}, {142 ┆            ┆   ┆ 52         ┆            ┆      ┆          │
│          ┆ as a mutan… ┆ ,[7409]}]  ┆            ┆   ┆            ┆            ┆      ┆          │
│ 206      ┆ Biochemical ┆ [{114,[107 ┆ 10751      ┆ … ┆ DDB_G02898 ┆ 114        ┆ 1967 ┆ 6067273  │
│          ┆ assays      ┆ 51]}]      ┆            ┆   ┆ 75         ┆            ┆      ┆          │
│          ┆ found a 10  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 207      ┆ Biochemical ┆ [{126,[107 ┆ 10751      ┆ … ┆ DDB_G02778 ┆ 126        ┆ 1967 ┆ 6067273  │
│          ┆ assays      ┆ 51]}]      ┆            ┆   ┆ 79         ┆            ┆      ┆          │
│          ┆ found a 10  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …        │
│ 1661     ┆ The major   ┆ [{172,[938 ┆ 6653       ┆ … ┆ DDB_G02769 ┆ 175        ┆ 1989 ┆ 2587278  │
│          ┆ spore coat  ┆ 7]}, {173, ┆            ┆   ┆ 41         ┆            ┆      ┆          │
│          ┆ proteins,…  ┆ [8541]},   ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆             ┆ ……         ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1661     ┆ The major   ┆ [{172,[938 ┆ 9387       ┆ … ┆ DDB_G02767 ┆ 172        ┆ 1979 ┆ 499661   │
│          ┆ spore coat  ┆ 7]}, {173, ┆            ┆   ┆ 61,DDB_G02 ┆            ┆      ┆          │
│          ┆ proteins,…  ┆ [8541]},   ┆            ┆   ┆ 77141,DDB_ ┆            ┆      ┆          │
│          ┆             ┆ ……         ┆            ┆   ┆ …          ┆            ┆      ┆          │
│ 1783     ┆ The         ┆ [{201,[107 ┆ 10721      ┆ … ┆ DDB_G02676 ┆ 201        ┆ 1967 ┆ 6069170  │
│          ┆ specific    ┆ 21]}, {202 ┆            ┆   ┆ 74         ┆            ┆      ┆          │
│          ┆ activity of ┆ ,[9996]}]  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ glyco…      ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1787     ┆ The         ┆ [{117,[666 ┆ 6662       ┆ … ┆ DDB_G02762 ┆ 117        ┆ 1989 ┆ 2546676  │
│          ┆ subunits    ┆ 2]}, {118, ┆            ┆   ┆ 67         ┆            ┆      ┆          │
│          ┆ interact    ┆ [5414]},   ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ with dow…   ┆ ……         ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1801     ┆ The WASH    ┆ [{36,[1772 ┆ 17728      ┆ … ┆ DDB_G02885 ┆ 36         ┆ 2013 ┆ 23993425 │
│          ┆ complex is  ┆ 8]}]       ┆            ┆   ┆ 69         ┆            ┆      ┆          │
│          ┆ highly con… ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
└──────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

Some claims are not covered. It seems that most of them are old paper that there are no abstract available. So I remove those and merge title and abstract to the claim table

In [354]:
epmc_small = EPMC.select([
    pl.col("pmid").cast(pl.Utf8).alias("pmid"),
    pl.col("title").alias("title"),
    pl.col("abstract_clean").alias("abstract_clean"),
])

claim_small = claim_cleaned_pmid_nonNA.with_columns(
    pl.col("pmid").cast(pl.Utf8).alias("pmid")
)

# inner join = ignore only-claim PMIDs
claim_cleaned_pmid_nonNA_abstract = claim_small.join(epmc_small, on="pmid", how="inner")

claim_cleaned_pmid_nonNA_abstract

shape: (2_561, 11)
┌──────────┬─────────────┬────────────┬────────────┬───┬──────┬──────────┬────────────┬────────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ year ┆ pmid     ┆ title      ┆ abstract_c │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---  ┆ ---      ┆ ---        ┆ lean       │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ i32  ┆ str      ┆ str        ┆ ---        │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆      ┆          ┆            ┆ str        │
╞══════════╪═════════════╪════════════╪════════════╪═══╪══════╪══════════╪════════════╪════════════╡
│ 1878     ┆ These       ┆ [{175,[162 ┆ 16288      ┆ … ┆ 2017 ┆ 28413119 ┆ The two    ┆ Autophagy  │
│          ┆ results     ┆ 88]}]      ┆            ┆   ┆      ┆          ┆ Dictyostel ┆ is a       │
│          ┆ suggest     ┆            ┆            ┆   ┆      ┆          ┆ ium        ┆ highly     │
│          ┆ that Atg…   ┆            ┆            ┆   ┆      ┆          ┆ discoide…  ┆ conserve…  │
│ 403      ┆ Disruption  ┆ [{103,[663 ┆ 6630       ┆ … ┆ 1989 ┆ 2515990  ┆ Selective  ┆ The        │
│          ┆ of csaA     ┆ 0]}]       ┆            ┆   ┆      ┆          ┆ eliminatio ┆ contact    │
│          ┆ results in  ┆            ┆            ┆   ┆      ┆          ┆ n of the   ┆ site A gly │
│          ┆ …           ┆            ┆            ┆   ┆      ┆          ┆ c…         ┆ coprotei…  │
│ 1105     ┆ MyoB is non ┆ [{163,[660 ┆ 12097      ┆ … ┆ 2012 ┆ 22367211 ┆ Molecular  ┆ Class I    │
│          ┆ -filamentou ┆ 8]}, {164, ┆            ┆   ┆      ┆          ┆ basis of   ┆ myosins    │
│          ┆ s and co…   ┆ [6857]},   ┆            ┆   ┆      ┆          ┆ dynamic    ┆ have a     │
│          ┆             ┆ {…         ┆            ┆   ┆      ┆          ┆ rel…       ┆ single …   │
│ 1196     ┆ pestis      ┆ [{235,[171 ┆ 17146      ┆ … ┆ 2018 ┆ 29350155 ┆ Yersinia   ┆ Plague     │
│          ┆ recruits    ┆ 46]}]      ┆            ┆   ┆      ┆          ┆ pestis     ┆ ecology is │
│          ┆ host Rab1B  ┆            ┆            ┆   ┆      ┆          ┆ Survival   ┆ characteri │
│          ┆ pro…        ┆            ┆            ┆   ┆      ┆          ┆ and R…     ┆ ze…        │
│ 582      ┆ FspA        ┆ [{122,[135 ┆ 13550      ┆ … ┆ 2013 ┆ 24128258 ┆ Two        ┆ Recognitio │
│          ┆ protein is  ┆ 50]}]      ┆            ┆   ┆      ┆          ┆ distinct   ┆ n of       │
│          ┆ an          ┆            ┆            ┆   ┆      ┆          ┆ sensing    ┆ bacteria   │
│          ┆ essential   ┆            ┆            ┆   ┆      ┆          ┆ pathways … ┆ by met…    │
│          ┆ c…          ┆            ┆            ┆   ┆      ┆          ┆            ┆            │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …    ┆ …        ┆ …          ┆ …          │
│ 439      ┆ Dominant    ┆ [{174,[174 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ negative    ┆ 91]}]      ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ rabS cells  ┆            ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆ d…          ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 1309     ┆ Rab2A is    ┆ [{83,[1542 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ associated  ┆ 2]}, {136, ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ with both … ┆ [17491]}]  ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 516      ┆ Expression  ┆ [{169,[116 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ of cotE is  ┆ 02]}]      ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ dependen…   ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 536      ┆ extended    ┆ [{0,[11602 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ these       ┆ ]}]        ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ findings    ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆ and de…     ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 2040     ┆ When        ┆ [{155,[107 ┆ 1071       ┆ … ┆ 2005 ┆ 15689527 ┆ Evolutiona ┆ In eukaryo │
│          ┆ activity is ┆ 1]}]       ┆            ┆   ┆      ┆          ┆ ry diversi ┆ tes, C5-cy │
│          ┆ observed,   ┆            ┆            ┆   ┆      ┆          ┆ fication   ┆ tosine     │
│          ┆ it …        ┆            ┆            ┆   ┆      ┆          ┆ o…         ┆ met…       │
└──────────┴─────────────┴────────────┴────────────┴───┴──────┴──────────┴────────────┴────────────┘

In [357]:
claim_cleaned_pmid_nonNA_abstract.write_parquet("output/cleaned/claim_cleaned_long_pmids_nonNA_abstract.parquet")