In [180]:
import polars as pl
import re

# citation-claims

In [181]:
claims = pl.read_parquet("output/curator_claims.parquet")
claims.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ sentence_ ┆ sentence_ ┆ cited_sen ┆ … ┆ anchors   ┆ publicati ┆ citation_ ┆ citation │
│ ---       ┆ markers   ┆ plain     ┆ tence_mar ┆   ┆ ---       ┆ on_ids    ┆ captions  ┆ _years   │
│ str       ┆ ---       ┆ ---       ┆ ked       ┆   ┆ list[stru ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ ---       ┆   ┆ ct[2]]    ┆ list[i64] ┆ list[str] ┆ list[i64 │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DDB_G0287 ┆ grlR      ┆ grlR      ┆ grlR      ┆ … ┆ [{126,[82 ┆ [827]     ┆ ["Prabu   ┆ [2006]   │
│ 681       ┆ encodes a ┆ encodes a ┆ encodes a ┆   ┆ 7]}]      ┆           ┆ and       ┆          │
│           ┆ member of ┆ member of ┆ member of ┆   ┆           ┆           ┆ Eichinger ┆          │
│           ┆ the e…    ┆ the e…    ┆ the e…    ┆   ┆           ┆           ┆ 2006)"]   ┆          │
│ DDB_G0290 ┆ The polyk ┆ The polyk ┆ The polyk ┆ … ┆ [{144,[95 ┆ [956,     ┆ ["(Austin ┆ [2006,   │
│ 825       ┆ etide     ┆ etide     ┆ etide     ┆   ┆ 6]}, {253 ┆ 2919]     ┆ et al.    ┆ 2000]    │
│           ┆ synthase  ┆ synthase  ┆ synthase  ┆   ┆ ,[2919]}] ┆           ┆ 2006)",   ┆          │
│           ┆ StlB (…   ┆ StlB (…   ┆ StlB (…   ┆   ┆           ┆           ┆ "(Tho…    ┆          │
│ DDB_G0285 ┆ There are ┆ There are ┆ There are ┆ … ┆ [{39,[403 ┆ [4032]    ┆ ["Bukenbe ┆ [1992]   │
│ 319       ┆ three     ┆ three     ┆ three     ┆   ┆ 2]}]      ┆           ┆ rger et   ┆          │
│           ┆ histone   ┆ histone   ┆ histone   ┆   ┆           ┆           ┆ al.       ┆          │
│           ┆ H3prot…   ┆ H3prot…   ┆ H3prot…   ┆   ┆           ┆           ┆ 1992"]    ┆          │
│ DDB_G0292 ┆ Analyses  ┆ Analyses  ┆ Analyses  ┆ … ┆ [{112,[99 ┆ [9912]    ┆ ["Dimond  ┆ [1976]   │
│ 810       ┆ of gluA   ┆ of gluA   ┆ of gluA   ┆   ┆ 12]}]     ┆           ┆ and       ┆          │
│           ┆ null      ┆ null      ┆ null      ┆   ┆           ┆           ┆ Loomis    ┆          │
│           ┆ mutants … ┆ mutants … ┆ mutants … ┆   ┆           ┆           ┆ 1976)"]   ┆          │
│ DDB_G0292 ┆ Expressio ┆ Expressio ┆ Expressio ┆ … ┆ [{126,[61 ┆ [6149]    ┆ ["Schatzl ┆ [1991]   │
│ 206       ┆ n is      ┆ n is      ┆ n is      ┆   ┆ 49]}]     ┆           ┆ e et al.  ┆          │
│           ┆ dependent ┆ dependent ┆ dependent ┆   ┆           ┆           ┆ 1991)"]   ┆          │
│           ┆ on a s…   ┆ on a s…   ┆ on a s…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [182]:
# look at a row closely
row = claims.row(1, named=True)
print(row)

{'gene_id': 'DDB_G0290825', 'sentence_markers': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [[PUB:956]] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [[PUB:2919]].', 'sentence_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) (Austin et al. 2006) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH (Thompson and Kay, 2000).', 'cited_sentence_marked': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [CITE:956] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [CITE:2919].', 'claim_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH.', 'anchors': [{'pos': 144, 'pub_ids': [956]}, {'pos': 253, 'pub_ids': [2919]}], 'publication_ids': [956, 2919], 'citation_captions': ['(Austin et al. 2006)', '(Thompson and Kay, 2000)'], 'citation_years': [2006, 2000]}

In [183]:
# get preferred column set (same as before)
df = claims.select([
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id",
])

In [184]:
# clean up parentheses in citation_captions
df = df.with_columns(
    pl.col("citation_captions")
    .list.eval(
        pl.element()
        .str.replace_all(r"[()]", "")   # remove parentheses
        .str.replace_all(r"\s+", " ")   # collapse whitespace
        .str.strip_chars()              # <-- instead of .str.strip()
    )
    .alias("citation_captions")
)

In [185]:
# clean up very short claims, it shall have at least 6
min_words = 6

df2 = df.with_columns(
    # Count "words" by matching non-space sequences
    pl.col("claim_plain")
      .str.count_matches(r"\S+")
      .alias("n_words")
)

# 1) summary
summary = df2.select([
    pl.len().alias("rows_total"),
    (pl.col("n_words") < min_words).sum().alias("rows_to_drop"),
    (pl.col("n_words") >= min_words).sum().alias("rows_to_keep"),
])
print(summary)
# 2) inspect what you'd drop (optional)
to_drop = (
    df2.filter(pl.col("n_words") < min_words)
       .select(["n_words", "claim_plain", "gene_id"])
       .sort(["n_words", "claim_plain"])
)
with pl.Config(fmt_str_lengths=300):
    display(to_drop.head(50))

# 3) actually filter
df_filtered = df2.filter(pl.col("n_words") >= min_words).drop("n_words")

shape: (1, 3)
┌────────────┬──────────────┬──────────────┐
│ rows_total ┆ rows_to_drop ┆ rows_to_keep │
│ ---        ┆ ---          ┆ ---          │
│ u32        ┆ u32          ┆ u32          │
╞════════════╪══════════════╪══════════════╡
│ 2677       ┆ 24           ┆ 2653         │
└────────────┴──────────────┴──────────────┘

shape: (24, 3)
┌─────────┬───────────────────────────────────────┬──────────────┐
│ n_words ┆ claim_plain                           ┆ gene_id      │
│ ---     ┆ ---                                   ┆ ---          │
│ u32     ┆ str                                   ┆ str          │
╞═════════╪═══════════════════════════════════════╪══════════════╡
│ 1       ┆ .                                     ┆ DDB_G0284845 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267444 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267630 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0279183 │
│ 2       ┆ (gskA) (..                            ┆ DDB_G0281385 │
│ …       ┆ …                                     ┆ …            │
│ 5       ┆ STATa is downregulated by PTP1.       ┆ DDB_G0281381 │
│ 5       ┆ Spores have lower cellulose levels.   ┆ DDB_G0281387 │
│ 5       ┆ at the tipped aggregate stage.        ┆ DDB_G0286185 │
│ 5       ┆ cerevisiae, plp2, is also essential.. ┆ DDB_G0285433 │
│ 5       ┆ discoideum by regulating ROS levels.  ┆ DDB_G0288247 │
└─────────┴───────────────────────────────────────┴──────────────┘

In [186]:
# let us examine the duplicated claims closely
# 1) merge duplicates by concatenating gene_id (unique + sorted)
merged = (
    df_filtered
    .group_by([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .agg(
        pl.col("gene_id")
          .unique()
          .sort()
          .str.join(",")
          .alias("gene_id")
    )
    .select([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions",
        "gene_id",
    ])
)

print("after merge:")
print("rows =", merged.height)
print("unique claim_plain =", merged.select(pl.col("claim_plain").n_unique()).item())

# 2) check if claim_plain is STILL duplicated (i.e., same claim text but different citation/anchors/etc.)
still_dups = (
    merged
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain"])
)

print("still duplicated claim_plain rows =", still_dups.height)

# show them grouped together if any remain
still_dups

after merge:
rows = 2107
unique claim_plain = 2103
still duplicated claim_plain rows = 8

shape: (8, 6)
┌──────────────────┬─────────────────┬─────────────────┬──────────────────┬──────────────────┬─────┐
│ claim_plain      ┆ anchors         ┆ publication_ids ┆ citation_caption ┆ gene_id          ┆ n   │
│ ---              ┆ ---             ┆ ---             ┆ s                ┆ ---              ┆ --- │
│ str              ┆ list[struct[2]] ┆ list[i64]       ┆ ---              ┆ str              ┆ u32 │
│                  ┆                 ┆                 ┆ list[str]        ┆                  ┆     │
╞══════════════════╪═════════════════╪═════════════════╪══════════════════╪══════════════════╪═════╡
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser et al.  ┆ DDB_G0267402,DDB ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ 1995"]           ┆ _G0270838,DDB_…  ┆     │
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser and     ┆ DDB_G0285319     ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ colleagues       ┆                  ┆     │
│                  ┆                 ┆                 ┆ 1995"]           ┆                  ┆     │
│ The 2C gene as   ┆ [{149,[1381]}]  ┆ [1381]          ┆ ["Schilde et al. ┆ DDB_G0280847     ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆                  ┆     │
│ The 2C gene as   ┆ [{149,[10129]}] ┆ [10129]         ┆ ["Schilde et al. ┆ DDB_G0280871,DDB ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆ _G0280953,DDB_…  ┆     │
│ These mutant     ┆ [{148,[1548]}]  ┆ [1548]          ┆ ["Zhang et al.   ┆ DDB_G0279413     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2003"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ These mutant     ┆ [{148,[2842]}]  ┆ [2842]          ┆ ["Wessels et al. ┆ DDB_G0284331     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2000"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ abcF1 and abcF4  ┆ [{115,[8189]}]  ┆ [8189]          ┆ ["Anjard and     ┆ DDB_G0267436,DDB ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆ _G0275637,DDB_…  ┆     │
│ abcF1 and abcF4  ┆ [{115,[2279]}]  ┆ [2279]          ┆ ["Anjard and     ┆ DDB_G0285997     ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆                  ┆     │
└──────────────────┴─────────────────┴─────────────────┴──────────────────┴──────────────────┴─────┘

In [187]:
# with pl.Config(fmt_str_lengths=60):
#     display(still_dups)

There are some duplicated claims.

Except the first one, the others are claims with inconsistant citations, let us remove those except the first one.

In [188]:
# 1) add a stable row id to merged
merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

# 2) recompute still_dups from merged_i (so it contains row_nr)
still_dups_i = (
    merged_i
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain", "row_nr"])
)

# 3) drop everything in still_dups except the first row of still_dups
drop_row_nrs = still_dups_i.slice(1).select("row_nr")   # everything after the first row

merged_clean = (
    merged_i
    .join(drop_row_nrs, on="row_nr", how="anti")  # remove those rows
    .drop(["row_nr", "n"], strict=False)
)

/var/folders/yr/ljjqmpj92wncw9wrv495wq300000gn/T/ipykernel_50959/3282369987.py:2: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

In [189]:
merged_clean

shape: (2_100, 5)
┌────────────────────┬───────────────────┬─────────────────┬───────────────────┬───────────────────┐
│ claim_plain        ┆ anchors           ┆ publication_ids ┆ citation_captions ┆ gene_id           │
│ ---                ┆ ---               ┆ ---             ┆ ---               ┆ ---               │
│ str                ┆ list[struct[2]]   ┆ list[i64]       ┆ list[str]         ┆ str               │
╞════════════════════╪═══════════════════╪═════════════════╪═══════════════════╪═══════════════════╡
│ PKA is also part   ┆ [{178,[3792]}]    ┆ [3792]          ┆ ["Souza et al.    ┆ DDB_G0283907      │
│ of the signal…     ┆                   ┆                 ┆ 1998"]            ┆                   │
│ The heavy chain    ┆ [{166,[12110]}]   ┆ [12110]         ┆ ["Kon et al.      ┆ DDB_G0276355      │
│ has a stem at …    ┆                   ┆                 ┆ 2012"]            ┆                   │
│ RegA is part of    ┆ [{93,[3726]},     ┆ [3726, 1420]    ┆ ["Laub et al.     ┆ DDB_G0284331      │
│ the circuit th…    ┆ {94,[1420]}]      ┆                 ┆ 1998", "Maeda et… ┆                   │
│ rasD mutants       ┆ [{189,[17969]}]   ┆ [17969]         ┆ ["Gruenheit et    ┆ DDB_G0269252      │
│ exhibit similar p… ┆                   ┆                 ┆ al. 2018"]        ┆                   │
│ In vitro, profilin ┆ [{143,[6071]}]    ┆ [6071]          ┆ ["Haugwitz et al. ┆ DDB_G0287125      │
│ I raises th…       ┆                   ┆                 ┆ 1991"]            ┆                   │
│ …                  ┆ …                 ┆ …               ┆ …                 ┆ …                 │
│ EGF repeats are    ┆ [{196,[2172]}]    ┆ [2172]          ┆ ["Fey et al.      ┆ DDB_G0288511      │
│ found in prote…    ┆                   ┆                 ┆ 2002"]            ┆                   │
│ The sevencalcium   ┆ [{100,[1293]}]    ┆ [1293]          ┆ ["Coukell et al.  ┆ DDB_G0267466,DDB_ │
│ up-regulated …     ┆                   ┆                 ┆ 2004"]            ┆ G0272242,DDB_…    │
│ Protein-tyrosine   ┆ [{119,[6479]},    ┆ [6479, 4724]    ┆ ["Tan and         ┆ DDB_G0283385      │
│ kinase genes …     ┆ {120,[4724]}]     ┆                 ┆ Spudich, 1990",   ┆                   │
│                    ┆                   ┆                 ┆ "Adl…             ┆                   │
│ The adaptor        ┆ [{77,[14016]}]    ┆ [14016]         ┆ ["Kolsch et al.   ┆ DDB_G0268620      │
│ protein,           ┆                   ┆                 ┆ 2013"]            ┆                   │
│ Daydreame…         ┆                   ┆                 ┆                   ┆                   │
│ pkcA is involved   ┆ [{105,[17928]}]   ┆ [17928]         ┆ ["Rijal et al.    ┆ DDB_G0288147      │
│ in the signal…     ┆                   ┆                 ┆ 2018"]            ┆                   │
└────────────────────┴───────────────────┴─────────────────┴───────────────────┴───────────────────┘

In [190]:
# give claim ID, and we want to explode the list columns together to get one row per (claim_id, publication_id)
m = merged_clean.with_columns(
    pl.col("claim_plain").rank(method="dense").cast(pl.Int64).alias("claim_id")
).select([
    "claim_id",
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id"
])

In [191]:
# 2) sanity check: list columns must be aligned per row before explode (len(citation_captions) == len(publication_ids))
bad_rows = (
    m
    .with_columns([
        pl.col("publication_ids").list.len().alias("n_pub"),
        pl.col("citation_captions").list.len().alias("n_cap")
    ])
    .filter(
        (pl.col("n_pub") != pl.col("n_cap")) 
    )
    .select([
        "claim_id",
        "gene_id",
        "n_pub", "n_cap", 
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .sort(["n_pub", "n_cap"], descending=True)
)

print("Number of misaligned rows:", bad_rows.height)

with pl.Config(fmt_str_lengths=1000):
    display(bad_rows)

Number of misaligned rows: 4

shape: (4, 8)
┌──────────┬──────────────┬───────┬───────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ claim_id ┆ gene_id      ┆ n_pub ┆ n_cap ┆ claim_plain  ┆ anchors     ┆ publication ┆ citation_ca │
│ ---      ┆ ---          ┆ ---   ┆ ---   ┆ ---          ┆ ---         ┆ _ids        ┆ ptions      │
│ i64      ┆ str          ┆ u32   ┆ u32   ┆ str          ┆ list[struct ┆ ---         ┆ ---         │
│          ┆              ┆       ┆       ┆              ┆ [2]]        ┆ list[i64]   ┆ list[str]   │
╞══════════╪══════════════╪═══════╪═══════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1534     ┆ DDB_G0287031 ┆ 2     ┆ 1     ┆ These        ┆ [{92,[4035] ┆ [4035,      ┆ ["Brandon   │
│          ┆              ┆       ┆       ┆ results      ┆ }, {93,[403 ┆ 4034]       ┆ et al.      │
│          ┆              ┆       ┆       ┆ reveal that  ┆ 4]}]        ┆             ┆ 1997"]      │
│          ┆              ┆       ┆       ┆ gpaC         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ functions as ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ a regulator  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ of early     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ development  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ gene         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ expression,. ┆             ┆             ┆             │
│ 1469     ┆ DDB_G0293084 ┆ 2     ┆ 1     ┆ The zizB     ┆ [{147,[1209 ┆ [12098,     ┆ ["Pakes et  │
│          ┆              ┆       ┆       ┆ mutant       ┆ 8]}, {148,[ ┆ 12830]      ┆ al. 2012"]  │
│          ┆              ┆       ┆       ┆ phenotypes   ┆ 12830]}]    ┆             ┆             │
│          ┆              ┆       ┆       ┆ and ZizB     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ binding      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ partners     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ suggest a    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ central role ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ for ZizB in  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ actin        ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cytoskeletal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ organization ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and cortical ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ stabilizatio ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ n.,.         ┆             ┆             ┆             │
│ 1195     ┆ DDB_G0286183 ┆ 2     ┆ 1     ┆ The Dictyost ┆ [{52,[712,  ┆ [712, 659]  ┆ ["Razeto et │
│          ┆              ┆       ┆       ┆ elium Agps   ┆ 659]}]      ┆             ┆ al .,       │
│          ┆              ┆       ┆       ┆ protein has  ┆             ┆             ┆ 2007"]      │
│          ┆              ┆       ┆       ┆ been crystal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ lized.       ┆             ┆             ┆             │
│ 471      ┆ DDB_G0268620 ┆ 2     ┆ 1     ┆ Fluid uptake ┆ [{113,[2428 ┆ [2428,      ┆ ["Rupper et │
│          ┆              ┆       ┆       ┆ by macropino ┆ ]}, {116,[2 ┆ 2634]       ┆ al. 2001"]  │
│          ┆              ┆       ┆       ┆ cytosis is   ┆ 634]}]      ┆             ┆             │
│          ┆              ┆       ┆       ┆ reduced      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ about 3 fold ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and          ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ phagosomes   ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ remain more  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ acidic in    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ pkbA - null  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cells (, (.  ┆             ┆             ┆             │
└──────────┴──────────────┴───────┴───────┴──────────────┴─────────────┴─────────────┴─────────────┘

in the 4 cases here, len(publication_ids)>len(citation_captions), after closer look, it is the same author and same year, we manully make a patch here

In [194]:
m_fixed = (
    m.with_columns(
        pl.when(pl.col("claim_id") == 1534)
          .then(pl.lit(["Brandon et al. 1997a", "Brandon et al. 1997b"]))
        .when(pl.col("claim_id") == 471)
          .then(pl.lit(["Rupper et al. 2001a", "Rupper et al. 2001b"]))
        .when(pl.col("claim_id") == 1469)
          .then(pl.lit(["Pakes et al. 2012a", "Pakes et al. 2012b"]))
        .when(pl.col("claim_id") == 1195)
          .then(pl.lit(["Razeto et al. 2007a", "Razeto et al. 2007b"]))
        .otherwise(pl.col("citation_captions"))
        .alias("citation_captions")
    )
)

In [195]:
m_long = (
    m_fixed
    .explode(["publication_ids", "citation_captions"])
    .rename({"publication_ids": "publication_id"})
)

In [196]:
m_long

shape: (2_661, 6)
┌──────────┬─────────────────┬─────────────────┬────────────────┬─────────────────┬────────────────┐
│ claim_id ┆ claim_plain     ┆ anchors         ┆ publication_id ┆ citation_captio ┆ gene_id        │
│ ---      ┆ ---             ┆ ---             ┆ ---            ┆ ns              ┆ ---            │
│ i64      ┆ str             ┆ list[struct[2]] ┆ i64            ┆ ---             ┆ str            │
│          ┆                 ┆                 ┆                ┆ str             ┆                │
╞══════════╪═════════════════╪═════════════════╪════════════════╪═════════════════╪════════════════╡
│ 947      ┆ PKA is also     ┆ [{178,[3792]}]  ┆ 3792           ┆ Souza et al.    ┆ DDB_G0283907   │
│          ┆ part of the     ┆                 ┆                ┆ 1998            ┆                │
│          ┆ signal…         ┆                 ┆                ┆                 ┆                │
│ 1327     ┆ The heavy chain ┆ [{166,[12110]}] ┆ 12110          ┆ Kon et al. 2012 ┆ DDB_G0276355   │
│          ┆ has a stem at … ┆                 ┆                ┆                 ┆                │
│ 1083     ┆ RegA is part of ┆ [{93,[3726]},   ┆ 3726           ┆ Laub et al.     ┆ DDB_G0284331   │
│          ┆ the circuit th… ┆ {94,[1420]}]    ┆                ┆ 1998            ┆                │
│ 1083     ┆ RegA is part of ┆ [{93,[3726]},   ┆ 1420           ┆ Maeda et al.    ┆ DDB_G0284331   │
│          ┆ the circuit th… ┆ {94,[1420]}]    ┆                ┆ 2004            ┆                │
│ 2043     ┆ rasD mutants    ┆ [{189,[17969]}] ┆ 17969          ┆ Gruenheit et    ┆ DDB_G0269252   │
│          ┆ exhibit similar ┆                 ┆                ┆ al. 2018        ┆                │
│          ┆ p…              ┆                 ┆                ┆                 ┆                │
│ …        ┆ …               ┆ …               ┆ …              ┆ …               ┆ …              │
│ 1446     ┆ The             ┆ [{100,[1293]}]  ┆ 1293           ┆ Coukell et al.  ┆ DDB_G0267466,D │
│          ┆ sevencalcium    ┆                 ┆                ┆ 2004            ┆ DB_G0272242,DD │
│          ┆ up-regulated …  ┆                 ┆                ┆                 ┆ B_…            │
│ 999      ┆ Protein-tyrosin ┆ [{119,[6479]},  ┆ 6479           ┆ Tan and         ┆ DDB_G0283385   │
│          ┆ e kinase genes  ┆ {120,[4724]}]   ┆                ┆ Spudich, 1990   ┆                │
│          ┆ …               ┆                 ┆                ┆                 ┆                │
│ 999      ┆ Protein-tyrosin ┆ [{119,[6479]},  ┆ 4724           ┆ Adler et al.    ┆ DDB_G0283385   │
│          ┆ e kinase genes  ┆ {120,[4724]}]   ┆                ┆ 1996            ┆                │
│          ┆ …               ┆                 ┆                ┆                 ┆                │
│ 1247     ┆ The adaptor     ┆ [{77,[14016]}]  ┆ 14016          ┆ Kolsch et al.   ┆ DDB_G0268620   │
│          ┆ protein,        ┆                 ┆                ┆ 2013            ┆                │
│          ┆ Daydreame…      ┆                 ┆                ┆                 ┆                │
│ 1988     ┆ pkcA is         ┆ [{105,[17928]}] ┆ 17928          ┆ Rijal et al.    ┆ DDB_G0288147   │
│          ┆ involved in the ┆                 ┆                ┆ 2018            ┆                │
│          ┆ signal…         ┆                 ┆                ┆                 ┆                │
└──────────┴─────────────────┴─────────────────┴────────────────┴─────────────────┴────────────────┘

In [197]:
# now we exlpode anchors
# 1) Build mapping: (claim_id, publication_id) -> anchor_pos
anchor_map = (
    m_fixed
    .select(["claim_id", "anchors"])
    .explode("anchors")  # now each row is one struct {pos, pub_ids}
    .with_columns([
        pl.col("anchors").struct.field("pos").alias("anchor_pos"),
        pl.col("anchors").struct.field("pub_ids").alias("publication_id"),
    ])
    .explode("publication_id")  # one row per pub_id
    .select(["claim_id", "publication_id", "anchor_pos"])
)

# If there can be multiple anchor_pos for the same (claim_id, publication_id), keep them all:
anchor_map = (
    anchor_map
    .group_by(["claim_id", "publication_id"])
    .agg(pl.col("anchor_pos").sort().alias("anchor_pos"))
)

# 2) Join onto m_long
m_long2 = m_long.join(anchor_map, on=["claim_id", "publication_id"], how="left")

# 3) If you want exactly one row per (claim_id, publication_id, anchor_pos), explode anchor_pos:
m_long3 = m_long2.explode("anchor_pos")

# Final columns (example)
m_long3.select([
    "claim_id",
    "claim_plain",
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
])

shape: (2_668, 6)
┌──────────┬───────────────────┬────────────┬────────────────┬──────────────────┬──────────────────┐
│ claim_id ┆ claim_plain       ┆ anchor_pos ┆ publication_id ┆ citation_caption ┆ gene_id          │
│ ---      ┆ ---               ┆ ---        ┆ ---            ┆ s                ┆ ---              │
│ i64      ┆ str               ┆ i64        ┆ i64            ┆ ---              ┆ str              │
│          ┆                   ┆            ┆                ┆ str              ┆                  │
╞══════════╪═══════════════════╪════════════╪════════════════╪══════════════════╪══════════════════╡
│ 947      ┆ PKA is also part  ┆ 178        ┆ 3792           ┆ Souza et al.     ┆ DDB_G0283907     │
│          ┆ of the signal…    ┆            ┆                ┆ 1998             ┆                  │
│ 1327     ┆ The heavy chain   ┆ 166        ┆ 12110          ┆ Kon et al. 2012  ┆ DDB_G0276355     │
│          ┆ has a stem at …   ┆            ┆                ┆                  ┆                  │
│ 1083     ┆ RegA is part of   ┆ 93         ┆ 3726           ┆ Laub et al. 1998 ┆ DDB_G0284331     │
│          ┆ the circuit th…   ┆            ┆                ┆                  ┆                  │
│ 1083     ┆ RegA is part of   ┆ 94         ┆ 1420           ┆ Maeda et al.     ┆ DDB_G0284331     │
│          ┆ the circuit th…   ┆            ┆                ┆ 2004             ┆                  │
│ 2043     ┆ rasD mutants      ┆ 189        ┆ 17969          ┆ Gruenheit et al. ┆ DDB_G0269252     │
│          ┆ exhibit similar   ┆            ┆                ┆ 2018             ┆                  │
│          ┆ p…                ┆            ┆                ┆                  ┆                  │
│ …        ┆ …                 ┆ …          ┆ …              ┆ …                ┆ …                │
│ 1446     ┆ The sevencalcium  ┆ 100        ┆ 1293           ┆ Coukell et al.   ┆ DDB_G0267466,DDB │
│          ┆ up-regulated …    ┆            ┆                ┆ 2004             ┆ _G0272242,DDB_…  │
│ 999      ┆ Protein-tyrosine  ┆ 119        ┆ 6479           ┆ Tan and Spudich, ┆ DDB_G0283385     │
│          ┆ kinase genes …    ┆            ┆                ┆ 1990             ┆                  │
│ 999      ┆ Protein-tyrosine  ┆ 120        ┆ 4724           ┆ Adler et al.     ┆ DDB_G0283385     │
│          ┆ kinase genes …    ┆            ┆                ┆ 1996             ┆                  │
│ 1247     ┆ The adaptor       ┆ 77         ┆ 14016          ┆ Kolsch et al.    ┆ DDB_G0268620     │
│          ┆ protein,          ┆            ┆                ┆ 2013             ┆                  │
│          ┆ Daydreame…        ┆            ┆                ┆                  ┆                  │
│ 1988     ┆ pkcA is involved  ┆ 105        ┆ 17928          ┆ Rijal et al.     ┆ DDB_G0288147     │
│          ┆ in the signal…    ┆            ┆                ┆ 2018             ┆                  │
└──────────┴───────────────────┴────────────┴────────────────┴──────────────────┴──────────────────┘

In [198]:
# now we get year from citation_captions
YEAR_RE = r"(18|19|20)\d{2}"

m_long3 = m_long3.with_columns(
    year=pl.col("citation_captions")
        .str.extract(YEAR_RE, 0)   # whole match
        .cast(pl.Int32)
)
m_long3

shape: (2_668, 8)
┌──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬──────┐
│ claim_id ┆ claim_plain ┆ anchors     ┆ publication ┆ citation_c ┆ gene_id    ┆ anchor_pos ┆ year │
│ ---      ┆ ---         ┆ ---         ┆ _id         ┆ aptions    ┆ ---        ┆ ---        ┆ ---  │
│ i64      ┆ str         ┆ list[struct ┆ ---         ┆ ---        ┆ str        ┆ i64        ┆ i32  │
│          ┆             ┆ [2]]        ┆ i64         ┆ str        ┆            ┆            ┆      │
╞══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪══════╡
│ 947      ┆ PKA is also ┆ [{178,[3792 ┆ 3792        ┆ Souza et   ┆ DDB_G02839 ┆ 178        ┆ 1998 │
│          ┆ part of the ┆ ]}]         ┆             ┆ al. 1998   ┆ 07         ┆            ┆      │
│          ┆ signal…     ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1327     ┆ The heavy   ┆ [{166,[1211 ┆ 12110       ┆ Kon et al. ┆ DDB_G02763 ┆ 166        ┆ 2012 │
│          ┆ chain has a ┆ 0]}]        ┆             ┆ 2012       ┆ 55         ┆            ┆      │
│          ┆ stem at …   ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1083     ┆ RegA is     ┆ [{93,[3726] ┆ 3726        ┆ Laub et    ┆ DDB_G02843 ┆ 93         ┆ 1998 │
│          ┆ part of the ┆ }, {94,[142 ┆             ┆ al. 1998   ┆ 31         ┆            ┆      │
│          ┆ circuit th… ┆ 0]}]        ┆             ┆            ┆            ┆            ┆      │
│ 1083     ┆ RegA is     ┆ [{93,[3726] ┆ 1420        ┆ Maeda et   ┆ DDB_G02843 ┆ 94         ┆ 2004 │
│          ┆ part of the ┆ }, {94,[142 ┆             ┆ al. 2004   ┆ 31         ┆            ┆      │
│          ┆ circuit th… ┆ 0]}]        ┆             ┆            ┆            ┆            ┆      │
│ 2043     ┆ rasD        ┆ [{189,[1796 ┆ 17969       ┆ Gruenheit  ┆ DDB_G02692 ┆ 189        ┆ 2018 │
│          ┆ mutants     ┆ 9]}]        ┆             ┆ et al.     ┆ 52         ┆            ┆      │
│          ┆ exhibit     ┆             ┆             ┆ 2018       ┆            ┆            ┆      │
│          ┆ similar p…  ┆             ┆             ┆            ┆            ┆            ┆      │
│ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …    │
│ 1446     ┆ The sevenca ┆ [{100,[1293 ┆ 1293        ┆ Coukell et ┆ DDB_G02674 ┆ 100        ┆ 2004 │
│          ┆ lcium up-re ┆ ]}]         ┆             ┆ al. 2004   ┆ 66,DDB_G02 ┆            ┆      │
│          ┆ gulated …   ┆             ┆             ┆            ┆ 72242,DDB_ ┆            ┆      │
│          ┆             ┆             ┆             ┆            ┆ …          ┆            ┆      │
│ 999      ┆ Protein-tyr ┆ [{119,[6479 ┆ 6479        ┆ Tan and    ┆ DDB_G02833 ┆ 119        ┆ 1990 │
│          ┆ osine       ┆ ]}, {120,[4 ┆             ┆ Spudich,   ┆ 85         ┆            ┆      │
│          ┆ kinase      ┆ 724]}]      ┆             ┆ 1990       ┆            ┆            ┆      │
│          ┆ genes …     ┆             ┆             ┆            ┆            ┆            ┆      │
│ 999      ┆ Protein-tyr ┆ [{119,[6479 ┆ 4724        ┆ Adler et   ┆ DDB_G02833 ┆ 120        ┆ 1996 │
│          ┆ osine       ┆ ]}, {120,[4 ┆             ┆ al. 1996   ┆ 85         ┆            ┆      │
│          ┆ kinase      ┆ 724]}]      ┆             ┆            ┆            ┆            ┆      │
│          ┆ genes …     ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1247     ┆ The adaptor ┆ [{77,[14016 ┆ 14016       ┆ Kolsch et  ┆ DDB_G02686 ┆ 77         ┆ 2013 │
│          ┆ protein,    ┆ ]}]         ┆             ┆ al. 2013   ┆ 20         ┆            ┆      │
│          ┆ Daydreame…  ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1988     ┆ pkcA is     ┆ [{105,[1792 ┆ 17928       ┆ Rijal et   ┆ DDB_G02881 ┆ 105        ┆ 2018 │
│          ┆ involved in ┆ 8]}]        ┆             ┆ al. 2018   ┆ 47         ┆            ┆      │
│          ┆ the signal… ┆             ┆             ┆            ┆            ┆            ┆      │
└──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴──────┘

In [199]:
year_summary = (
    m_long3
    .with_columns(pl.col("year").fill_null(-1).alias("year2"))
    .group_by("year2")
    .agg(pl.len().alias("n"))
    .sort("year2")
    .with_columns(
        pl.when(pl.col("year2") == -1).then(None).otherwise(pl.col("year2")).alias("year")
    )
    .select(["year", "n"])
)

year_summary

shape: (55, 2)
┌──────┬─────┐
│ year ┆ n   │
│ ---  ┆ --- │
│ i32  ┆ u32 │
╞══════╪═════╡
│ null ┆ 7   │
│ 1956 ┆ 1   │
│ 1965 ┆ 1   │
│ 1967 ┆ 3   │
│ 1968 ┆ 1   │
│ …    ┆ …   │
│ 2016 ┆ 77  │
│ 2017 ┆ 60  │
│ 2018 ┆ 81  │
│ 2019 ┆ 87  │
│ 2020 ┆ 35  │
└──────┴─────┘

In [200]:
claim_cleaned = m_long3.select([
    "claim_id",
    "claim_plain",
    "anchors",        # keep if you still want the original struct list
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
    "year",
])

In [209]:
claim_cleaned.write_parquet("output/cleaned/claim_cleaned_long.parquet")

In [210]:
claim_cleaned.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2100              │
└───────────────────┘

In [211]:
# to_save = claim_cleaned.with_columns(
#     pl.col("anchors").cast(pl.Utf8)   # converts list/struct to a string representation
# ).select([
#     "claim_id","claim_plain","anchors","anchor_pos",
#     "publication_id","citation_captions","gene_id","year"
# ])

# to_save.write_csv("output/cleaned/claim_cleaned_long.tsv", separator="\t")

I will certainly need to still manually check out the datasets later. So far we have 2100 unique claims.

In [208]:
# manual inspection, will pick some golden set maunally later
claim_cleaned_manual = claim_cleaned.filter(pl.col("anchor_pos") != 1)

# match pmid

In [213]:
pub_pmid = pl.read_csv("output/publication_id_pmid.csv")
pub_pmid

shape: (4_341, 2)
┌────────────────┬──────────┐
│ publication_id ┆ pmid     │
│ ---            ┆ ---      │
│ i64            ┆ i64      │
╞════════════════╪══════════╡
│ 12             ┆ 21243421 │
│ 13             ┆ 21239624 │
│ 15             ┆ 21235525 │
│ 17             ┆ 20950684 │
│ 20             ┆ 21150268 │
│ …              ┆ …        │
│ 19689          ┆ 32769116 │
│ 19708          ┆ 21551065 │
│ 19728          ┆ 32821814 │
│ 19729          ┆ 32818671 │
│ 19748          ┆ 32850852 │
└────────────────┴──────────┘

In [217]:
# check if all publcation id can be mapped to pmid

# pick the right df names
a = claim_cleaned
b = pub_pmid

# make sure both publication_id columns are the same type (I recommend Int64)
a_ids = a.select(pl.col("publication_id").cast(pl.Int64)).unique()
b_ids = b.select(pl.col("publication_id").cast(pl.Int64)).unique()

# overlap + only-in sets
overlap = a_ids.join(b_ids, on="publication_id", how="inner")
only_a  = a_ids.join(b_ids, on="publication_id", how="anti")
only_b  = b_ids.join(a_ids, on="publication_id", how="anti")

summary = pl.DataFrame({
    "set": ["claim_cleaned", "pub_pmid", "overlap", "only_claim_cleaned", "only_pub_pmid"],
    "unique_count": [a_ids.height, b_ids.height, overlap.height, only_a.height, only_b.height],
})

summary

shape: (5, 2)
┌────────────────────┬──────────────┐
│ set                ┆ unique_count │
│ ---                ┆ ---          │
│ str                ┆ i64          │
╞════════════════════╪══════════════╡
│ claim_cleaned      ┆ 1400         │
│ pub_pmid           ┆ 4341         │
│ overlap            ┆ 1373         │
│ only_claim_cleaned ┆ 27           │
│ only_pub_pmid      ┆ 2968         │
└────────────────────┴──────────────┘

25 ids are not mapped.

In [219]:
claim_cleaned_pmid = (
    claim_cleaned
    .with_columns(pl.col("publication_id").cast(pl.Int64))
    .join(pub_pmid, on="publication_id", how="left")
    .with_columns(
        pl.col("pmid").fill_null("NA")  # or keep as null if you prefer
    )
)

claim_cleaned_pmid

shape: (2_668, 9)
┌──────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ anchor_pos ┆ … ┆ citation_c ┆ gene_id    ┆ year ┆ pmid     │
│ ---      ┆ ---         ┆ ---        ┆ ---        ┆   ┆ aptions    ┆ ---        ┆ ---  ┆ ---      │
│ i64      ┆ str         ┆ list[struc ┆ i64        ┆   ┆ ---        ┆ str        ┆ i32  ┆ str      │
│          ┆             ┆ t[2]]      ┆            ┆   ┆ str        ┆            ┆      ┆          │
╞══════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 947      ┆ PKA is also ┆ [{178,[379 ┆ 178        ┆ … ┆ Souza et   ┆ DDB_G02839 ┆ 1998 ┆ 9584128  │
│          ┆ part of the ┆ 2]}]       ┆            ┆   ┆ al. 1998   ┆ 07         ┆      ┆          │
│          ┆ signal…     ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1327     ┆ The heavy   ┆ [{166,[121 ┆ 166        ┆ … ┆ Kon et al. ┆ DDB_G02763 ┆ 2012 ┆ 22398446 │
│          ┆ chain has a ┆ 10]}]      ┆            ┆   ┆ 2012       ┆ 55         ┆      ┆          │
│          ┆ stem at …   ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1083     ┆ RegA is     ┆ [{93,[3726 ┆ 93         ┆ … ┆ Laub et    ┆ DDB_G02843 ┆ 1998 ┆ 9843585  │
│          ┆ part of the ┆ ]}, {94,[1 ┆            ┆   ┆ al. 1998   ┆ 31         ┆      ┆          │
│          ┆ circuit th… ┆ 420]}]     ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1083     ┆ RegA is     ┆ [{93,[3726 ┆ 94         ┆ … ┆ Maeda et   ┆ DDB_G02843 ┆ 2004 ┆ 15131307 │
│          ┆ part of the ┆ ]}, {94,[1 ┆            ┆   ┆ al. 2004   ┆ 31         ┆      ┆          │
│          ┆ circuit th… ┆ 420]}]     ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2043     ┆ rasD        ┆ [{189,[179 ┆ 189        ┆ … ┆ Gruenheit  ┆ DDB_G02692 ┆ 2018 ┆ 30473004 │
│          ┆ mutants     ┆ 69]}]      ┆            ┆   ┆ et al.     ┆ 52         ┆      ┆          │
│          ┆ exhibit     ┆            ┆            ┆   ┆ 2018       ┆            ┆      ┆          │
│          ┆ similar p…  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …        │
│ 1446     ┆ The sevenca ┆ [{100,[129 ┆ 100        ┆ … ┆ Coukell et ┆ DDB_G02674 ┆ 2004 ┆ 14871937 │
│          ┆ lcium up-re ┆ 3]}]       ┆            ┆   ┆ al. 2004   ┆ 66,DDB_G02 ┆      ┆          │
│          ┆ gulated …   ┆            ┆            ┆   ┆            ┆ 72242,DDB_ ┆      ┆          │
│          ┆             ┆            ┆            ┆   ┆            ┆ …          ┆      ┆          │
│ 999      ┆ Protein-tyr ┆ [{119,[647 ┆ 119        ┆ … ┆ Tan and    ┆ DDB_G02833 ┆ 1990 ┆ 1972546  │
│          ┆ osine       ┆ 9]}, {120, ┆            ┆   ┆ Spudich,   ┆ 85         ┆      ┆          │
│          ┆ kinase      ┆ [4724]}]   ┆            ┆   ┆ 1990       ┆            ┆      ┆          │
│          ┆ genes …     ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 999      ┆ Protein-tyr ┆ [{119,[647 ┆ 120        ┆ … ┆ Adler et   ┆ DDB_G02833 ┆ 1996 ┆ 8898113  │
│          ┆ osine       ┆ 9]}, {120, ┆            ┆   ┆ al. 1996   ┆ 85         ┆      ┆          │
│          ┆ kinase      ┆ [4724]}]   ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ genes …     ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1247     ┆ The adaptor ┆ [{77,[1401 ┆ 77         ┆ … ┆ Kolsch et  ┆ DDB_G02686 ┆ 2013 ┆ 23135995 │
│          ┆ protein,    ┆ 6]}]       ┆            ┆   ┆ al. 2013   ┆ 20         ┆      ┆          │
│          ┆ Daydreame…  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1988     ┆ pkcA is     ┆ [{105,[179 ┆ 105        ┆ … ┆ Rijal et   ┆ DDB_G02881 ┆ 2018 ┆ 30462573 │
│          ┆ involved in ┆ 28]}]      ┆            ┆   ┆ al. 2018   ┆ 47         ┆      ┆          │
│          ┆ the signal… ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
└──────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

In [220]:
claim_cleaned_pmid.write_parquet("output/cleaned/claim_cleaned_long_pmids.parquet")

claim_cleaned_pmid_nonNA = claim_cleaned_pmid.filter(
    pl.col("pmid").is_not_null() & (pl.col("pmid") != "NA")
)

claim_cleaned_pmid_nonNA.write_parquet("output/cleaned/claim_cleaned_long_pmids_nonNA.parquet")

In [222]:
claim_cleaned_pmid_nonNA.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2077              │
└───────────────────┘

# how many we have abstracts on EPMC

In [226]:
EPMC = pl.read_parquet("output/cleaned/articles_all_cleaned_abstract.parquet")

In [227]:
EPMC

shape: (20_951, 9)
┌──────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ pmid     ┆ pmcid      ┆ doi        ┆ year ┆ … ┆ journal    ┆ authors    ┆ abstract_c ┆ file      │
│ ---      ┆ ---        ┆ ---        ┆ ---  ┆   ┆ ---        ┆ ---        ┆ lean       ┆ ---       │
│ str      ┆ str        ┆ str        ┆ str  ┆   ┆ str        ┆ str        ┆ ---        ┆ str       │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ str        ┆           │
╞══════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2654141  ┆ PMC2115546 ┆ 10.1083/jc ┆ 1989 ┆ … ┆ The        ┆ Sanders    ┆ Chlamydomo ┆ article_f │
│          ┆            ┆ b.108.5.17 ┆      ┆   ┆ Journal of ┆ MA,        ┆ nas cells  ┆ etching/o │
│          ┆            ┆ 51         ┆      ┆   ┆ cell       ┆ Salisbury  ┆ excise     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ biology    ┆ JL.        ┆ the…       ┆ _cl…      │
│ 39528565 ┆ PMC1155504 ┆ 10.1038/s4 ┆ 2024 ┆ … ┆ Nature com ┆ Lim YJ,    ┆ Plant      ┆ article_f │
│          ┆ 5          ┆ 1467-024-5 ┆      ┆   ┆ munication ┆ Yoon YJ,   ┆ pathogens  ┆ etching/o │
│          ┆            ┆ 4272-4     ┆      ┆   ┆ s          ┆ Lee H,     ┆ secrete    ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Choi G…    ┆ nuclea…    ┆ _cl…      │
│ 6319129  ┆ null       ┆ 10.1111/j. ┆ 1984 ┆ … ┆ European   ┆ Scholübber ┆ The        ┆ article_f │
│          ┆            ┆ 1432-1033. ┆      ┆   ┆ journal of ┆ s HG, van  ┆ ability of ┆ etching/o │
│          ┆            ┆ 1984.tb078 ┆      ┆   ┆ biochemist ┆ Knippenber ┆ 24 systema ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆ …          ┆ …          ┆ tical…     ┆ _cl…      │
│ 28740830 ┆ PMC5502327 ┆ 10.3389/fo ┆ 2017 ┆ … ┆ Frontiers  ┆ Mammucari  ┆ Mitochondr ┆ article_f │
│          ┆            ┆ nc.2017.00 ┆      ┆   ┆ in         ┆ C,         ┆ ial Ca2+   ┆ etching/o │
│          ┆            ┆ 139        ┆      ┆   ┆ oncology   ┆ Gherardi   ┆ uptake     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ G, Rizzu…  ┆ play…      ┆ _cl…      │
│ 18814278 ┆ null       ┆ 10.1002/cm ┆ 2008 ┆ … ┆ Cell       ┆ Asano Y,   ┆ Chemotaxis ┆ article_f │
│          ┆            ┆ .20314     ┆      ┆   ┆ motility   ┆ Nagasaki   ┆ -deficient ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆ and the    ┆ A, Uyeda   ┆ amiB-null… ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ cytoskel…  ┆ TQ.        ┆            ┆ _cl…      │
│ …        ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 20023070 ┆ PMC2823002 ┆ 10.1128/ec ┆ 2010 ┆ … ┆ Eukaryotic ┆ Schilde C, ┆ We have    ┆ article_f │
│          ┆            ┆ .00220-09  ┆      ┆   ┆ cell       ┆ Schönemann ┆ identified ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆            ┆ B, Sehri…  ┆ new        ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ synapto…   ┆ _cl…      │
│ 10706824 ┆ null       ┆ 10.1006/sc ┆ 1999 ┆ … ┆ Seminars   ┆ Mohanty S, ┆ The        ┆ article_f │
│          ┆            ┆ db.1999.03 ┆      ┆   ┆ in cell &  ┆ Firtel RA. ┆ spatial    ┆ etching/o │
│          ┆            ┆ 43         ┆      ┆   ┆ developmen ┆            ┆ patterning ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ t…         ┆            ┆ of pres…   ┆ _cl…      │
│ null     ┆ null       ┆ 10.1101/20 ┆ 2022 ┆ … ┆ null       ┆ Walker LM, ┆ Aggregativ ┆ article_f │
│          ┆            ┆ 22.10.21.5 ┆      ┆   ┆            ┆ Sherpa RN, ┆ e multicel ┆ etching/o │
│          ┆            ┆ 13250      ┆      ┆   ┆            ┆ Ivaturi …  ┆ lularity   ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ r…         ┆ _cl…      │
│ 39396247 ┆ PMC1148569 ┆ 10.1080/19 ┆ 2024 ┆ … ┆ Gut        ┆ Roy M,     ┆ Metabolic  ┆ article_f │
│          ┆ 4          ┆ 490976.202 ┆      ┆   ┆ microbes   ┆ Dumay A,   ┆ syndrome   ┆ etching/o │
│          ┆            ┆ 4.2409210  ┆      ┆   ┆            ┆ Adiba S,   ┆ (MetS) is  ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Rozes…     ┆ a…         ┆ _cl…      │
│ 18460092 ┆ PMC2666851 ┆ 10.1111/j. ┆ 2008 ┆ … ┆ Evolution  ┆ Okoruwa    ┆ Prestin    ┆ article_f │
│          ┆            ┆ 1525-142x. ┆      ┆   ┆ & developm ┆ OE, Weston ┆ (SLC26A5)  ┆ etching/o │
│          ┆            ┆ 2008.00239 ┆      ┆   ┆ ent        ┆ MD,        ┆ is the     ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆            ┆ Sanjeev…   ┆ molec…     ┆ _cl…      │
└──────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘