In [3]:
import polars as pl
import re
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors
import json
import os
from pathlib import Path


def _repo_root() -> Path:
    env = os.environ.get("DICTYCITE_ROOT", "").strip()
    if env:
        return Path(env).expanduser().resolve()

    starts: list[Path] = []
    try:
        starts.append(Path(__file__).resolve().parent)
    except NameError:
        pass
    starts.append(Path.cwd().resolve())

    for start in starts:
        p = start
        while True:
            if (p / ".git").exists():
                return p
            if p.parent == p:
                break
            p = p.parent

    cwd = Path.cwd().resolve()
    for base in (cwd, cwd.parent, *cwd.parents):
        marker = base / "output" / "dicty_gold_build" / "1_curator_claims.parquet"
        if marker.is_file():
            return base
    if cwd.name == "notebooks":
        return cwd.parent
    return cwd


def _output_gold_build() -> Path:
    return _repo_root() / "output" / "dicty_gold_build"


OUTPUT_GOLD_BUILD = _output_gold_build()

# citation-claims

In [4]:
claims = pl.read_parquet(OUTPUT_GOLD_BUILD / "1_curator_claims.parquet")
claims.head()

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ gene_id   ┆ sentence_ ┆ sentence_ ┆ cited_sen ┆ … ┆ anchors   ┆ publicati ┆ citation_ ┆ citation │
│ ---       ┆ markers   ┆ plain     ┆ tence_mar ┆   ┆ ---       ┆ on_ids    ┆ captions  ┆ _years   │
│ str       ┆ ---       ┆ ---       ┆ ked       ┆   ┆ list[stru ┆ ---       ┆ ---       ┆ ---      │
│           ┆ str       ┆ str       ┆ ---       ┆   ┆ ct[2]]    ┆ list[i64] ┆ list[str] ┆ list[i64 │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ DDB_G0287 ┆ grlR      ┆ grlR      ┆ grlR      ┆ … ┆ [{126,[82 ┆ [827]     ┆ ["Prabu   ┆ [2006]   │
│ 681       ┆ encodes a ┆ encodes a ┆ encodes a ┆   ┆ 7]}]      ┆           ┆ and       ┆          │
│           ┆ member of ┆ member of ┆ member of ┆   ┆           ┆           ┆ Eichinger ┆          │
│           ┆ the e…    ┆ the e…    ┆ the e…    ┆   ┆           ┆           ┆ 2006)"]   ┆          │
│ DDB_G0290 ┆ The polyk ┆ The polyk ┆ The polyk ┆ … ┆ [{144,[95 ┆ [956,     ┆ ["(Austin ┆ [2006,   │
│ 825       ┆ etide     ┆ etide     ┆ etide     ┆   ┆ 6]}, {253 ┆ 2919]     ┆ et al.    ┆ 2000]    │
│           ┆ synthase  ┆ synthase  ┆ synthase  ┆   ┆ ,[2919]}] ┆           ┆ 2006)",   ┆          │
│           ┆ StlB (…   ┆ StlB (…   ┆ StlB (…   ┆   ┆           ┆           ┆ "(Tho…    ┆          │
│ DDB_G0285 ┆ There are ┆ There are ┆ There are ┆ … ┆ [{39,[403 ┆ [4032]    ┆ ["Bukenbe ┆ [1992]   │
│ 319       ┆ three     ┆ three     ┆ three     ┆   ┆ 2]}]      ┆           ┆ rger et   ┆          │
│           ┆ histone   ┆ histone   ┆ histone   ┆   ┆           ┆           ┆ al.       ┆          │
│           ┆ H3prot…   ┆ H3prot…   ┆ H3prot…   ┆   ┆           ┆           ┆ 1992"]    ┆          │
│ DDB_G0292 ┆ Analyses  ┆ Analyses  ┆ Analyses  ┆ … ┆ [{112,[99 ┆ [9912]    ┆ ["Dimond  ┆ [1976]   │
│ 810       ┆ of gluA   ┆ of gluA   ┆ of gluA   ┆   ┆ 12]}]     ┆           ┆ and       ┆          │
│           ┆ null      ┆ null      ┆ null      ┆   ┆           ┆           ┆ Loomis    ┆          │
│           ┆ mutants … ┆ mutants … ┆ mutants … ┆   ┆           ┆           ┆ 1976)"]   ┆          │
│ DDB_G0292 ┆ Expressio ┆ Expressio ┆ Expressio ┆ … ┆ [{126,[61 ┆ [6149]    ┆ ["Schatzl ┆ [1991]   │
│ 206       ┆ n is      ┆ n is      ┆ n is      ┆   ┆ 49]}]     ┆           ┆ e et al.  ┆          │
│           ┆ dependent ┆ dependent ┆ dependent ┆   ┆           ┆           ┆ 1991)"]   ┆          │
│           ┆ on a s…   ┆ on a s…   ┆ on a s…   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
# look at a row closely
row = claims.row(1, named=True)
print(row)

{'gene_id': 'DDB_G0290825', 'sentence_markers': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [[PUB:956]] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [[PUB:2919]].', 'sentence_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) (Austin et al. 2006) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH (Thompson and Kay, 2000).', 'cited_sentence_marked': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) [CITE:956] and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH [CITE:2919].', 'claim_plain': 'The polyketide synthase StlB (stlB) catalyzes the first step, the formation of the core polyketide (2,4,6-trihydroxyphenyl)-1-hexan-1-one (THPH) and des-methyl-DIF-1 methyltransferase DmtA (dmtA) catalyzes the last step, the methylation of dichloro-THPH.', 'anchors': [{'pos': 144, 'pub_ids': [956]}, {'pos': 253, 'pub_ids': [2919]}], 'publication_ids': [956, 2919], 'citation_captions': ['(Austin et al. 2006)', '(Thompson and Kay, 2000)'], 'citation_years': [2006, 2000]}

In [6]:
# get preferred column set (same as before)
df = claims.select([
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id",
])

In [7]:
# clean up parentheses in citation_captions
df = df.with_columns(
    pl.col("citation_captions")
    .list.eval(
        pl.element()
        .str.replace_all(r"[()]", "")   # remove parentheses
        .str.replace_all(r"\s+", " ")   # collapse whitespace
        .str.strip_chars()              # <-- instead of .str.strip()
    )
    .alias("citation_captions")
)
# clean up comma
df = df.with_columns(
    pl.col("citation_captions")
    .list.eval(
        pl.element()
        .str.replace_all(r"[()]", "")
        .str.replace_all(r"\bet al\b\.?", "et al.")
        .str.replace_all(r",\s*et al\.", " et al.")
        .str.replace_all(r"et al\.\s*,\s*", "et al. ")
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
    )
    .alias("citation_captions")
)

In [8]:
# clean up very short claims, it shall have at least 6
min_words = 6

df2 = df.with_columns(
    # Count "words" by matching non-space sequences
    pl.col("claim_plain")
      .str.count_matches(r"\S+")
      .alias("n_words")
)

# 1) summary
summary = df2.select([
    pl.len().alias("rows_total"),
    (pl.col("n_words") < min_words).sum().alias("rows_to_drop"),
    (pl.col("n_words") >= min_words).sum().alias("rows_to_keep"),
])
print(summary)
# 2) inspect what you'd drop (optional)
to_drop = (
    df2.filter(pl.col("n_words") < min_words)
       .select(["n_words", "claim_plain", "gene_id"])
       .sort(["n_words", "claim_plain"])
)
with pl.Config(fmt_str_lengths=300):
    display(to_drop.head(50))

# 3) actually filter
df_filtered = df2.filter(pl.col("n_words") >= min_words).drop("n_words")

shape: (1, 3)
┌────────────┬──────────────┬──────────────┐
│ rows_total ┆ rows_to_drop ┆ rows_to_keep │
│ ---        ┆ ---          ┆ ---          │
│ u32        ┆ u32          ┆ u32          │
╞════════════╪══════════════╪══════════════╡
│ 2677       ┆ 24           ┆ 2653         │
└────────────┴──────────────┴──────────────┘

shape: (24, 3)
┌─────────┬───────────────────────────────────────┬──────────────┐
│ n_words ┆ claim_plain                           ┆ gene_id      │
│ ---     ┆ ---                                   ┆ ---          │
│ u32     ┆ str                                   ┆ str          │
╞═════════╪═══════════════════════════════════════╪══════════════╡
│ 1       ┆ .                                     ┆ DDB_G0284845 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267444 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0267630 │
│ 1       ┆ pneumoniae.                           ┆ DDB_G0279183 │
│ 2       ┆ (gskA) (..                            ┆ DDB_G0281385 │
│ …       ┆ …                                     ┆ …            │
│ 5       ┆ STATa is downregulated by PTP1.       ┆ DDB_G0281381 │
│ 5       ┆ Spores have lower cellulose levels.   ┆ DDB_G0281387 │
│ 5       ┆ at the tipped aggregate stage.        ┆ DDB_G0286185 │
│ 5       ┆ cerevisiae, plp2, is also essential.. ┆ DDB_G0285433 │
│ 5       ┆ discoideum by regulating ROS levels.  ┆ DDB_G0288247 │
└─────────┴───────────────────────────────────────┴──────────────┘

In [9]:
# let us examine the duplicated claims closely
# 1) merge duplicates by concatenating gene_id (unique + sorted)
merged = (
    df_filtered
    .group_by([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .agg(
        pl.col("gene_id")
          .unique()
          .sort()
          .str.join(",")
          .alias("gene_id")
    )
    .select([
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions",
        "gene_id",
    ])
)

print("after merge:")
print("rows =", merged.height)
print("unique claim_plain =", merged.select(pl.col("claim_plain").n_unique()).item())

# 2) check if claim_plain is STILL duplicated (i.e., same claim text but different citation/anchors/etc.)
still_dups = (
    merged
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain"])
)

print("still duplicated claim_plain rows =", still_dups.height)

# show them grouped together if any remain
still_dups

after merge:
rows = 2107
unique claim_plain = 2103
still duplicated claim_plain rows = 8

shape: (8, 6)
┌──────────────────┬─────────────────┬─────────────────┬──────────────────┬──────────────────┬─────┐
│ claim_plain      ┆ anchors         ┆ publication_ids ┆ citation_caption ┆ gene_id          ┆ n   │
│ ---              ┆ ---             ┆ ---             ┆ s                ┆ ---              ┆ --- │
│ str              ┆ list[struct[2]] ┆ list[i64]       ┆ ---              ┆ str              ┆ u32 │
│                  ┆                 ┆                 ┆ list[str]        ┆                  ┆     │
╞══════════════════╪═════════════════╪═════════════════╪══════════════════╪══════════════════╪═════╡
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser et al.  ┆ DDB_G0267402,DDB ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ 1995"]           ┆ _G0270838,DDB_…  ┆     │
│ In Dictyostelium ┆ [{183,[5046]}]  ┆ [5046]          ┆ ["Hauser and     ┆ DDB_G0285319     ┆ 2   │
│ discoideum an…   ┆                 ┆                 ┆ colleagues       ┆                  ┆     │
│                  ┆                 ┆                 ┆ 1995"]           ┆                  ┆     │
│ The 2C gene as   ┆ [{149,[10129]}] ┆ [10129]         ┆ ["Schilde et al. ┆ DDB_G0280871,DDB ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆ _G0280953,DDB_…  ┆     │
│ The 2C gene as   ┆ [{149,[1381]}]  ┆ [1381]          ┆ ["Schilde et al. ┆ DDB_G0280847     ┆ 2   │
│ well as 5 relat… ┆                 ┆                 ┆ 2004"]           ┆                  ┆     │
│ These mutant     ┆ [{148,[1548]}]  ┆ [1548]          ┆ ["Zhang et al.   ┆ DDB_G0279413     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2003"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ These mutant     ┆ [{148,[2842]}]  ┆ [2842]          ┆ ["Wessels et al. ┆ DDB_G0284331     ┆ 2   │
│ cells are also   ┆                 ┆                 ┆ 2000"]           ┆                  ┆     │
│ im…              ┆                 ┆                 ┆                  ┆                  ┆     │
│ abcF1 and abcF4  ┆ [{115,[8189]}]  ┆ [8189]          ┆ ["Anjard and     ┆ DDB_G0267436,DDB ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆ _G0275637,DDB_…  ┆     │
│ abcF1 and abcF4  ┆ [{115,[2279]}]  ┆ [2279]          ┆ ["Anjard and     ┆ DDB_G0285997     ┆ 2   │
│ are the most c…  ┆                 ┆                 ┆ Loomis 2002"]    ┆                  ┆     │
└──────────────────┴─────────────────┴─────────────────┴──────────────────┴──────────────────┴─────┘

In [10]:
# with pl.Config(fmt_str_lengths=60):
#     display(still_dups)

There are some duplicated claims.

Except the first one, the others are claims with inconsistant citations, let us remove those except the first one.

In [11]:
# 1) add a stable row id to merged
merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

# 2) recompute still_dups from merged_i (so it contains row_nr)
still_dups_i = (
    merged_i
    .with_columns(pl.len().over("claim_plain").alias("n"))
    .filter(pl.col("n") > 1)
    .sort(["claim_plain", "row_nr"])
)

# 3) drop everything in still_dups except the first row of still_dups
drop_row_nrs = still_dups_i.slice(1).select("row_nr")   # everything after the first row

merged_clean = (
    merged_i
    .join(drop_row_nrs, on="row_nr", how="anti")  # remove those rows
    .drop(["row_nr", "n"], strict=False)
)

/var/folders/yr/ljjqmpj92wncw9wrv495wq300000gn/T/ipykernel_22397/3282369987.py:2: DeprecationWarning: `DataFrame.with_row_count` is deprecated; use `with_row_index` instead. Note that the default column name has changed from 'row_nr' to 'index'.
  merged_i = merged.with_row_count("row_nr")   # if this errors on your Polars, use: .with_row_index("row_nr")

In [12]:
merged_clean

shape: (2_100, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ claim_plain       ┆ anchors           ┆ publication_ids   ┆ citation_captions ┆ gene_id          │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ str               ┆ list[struct[2]]   ┆ list[i64]         ┆ list[str]         ┆ str              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ pkaC encodes the  ┆ [{77,[5939]},     ┆ [5939, 5469]      ┆ ["Mann et al.     ┆ DDB_G0283907     │
│ catalytic sub…    ┆ {78,[5469]}]      ┆                   ┆ 1992", "Anjard e… ┆                  │
│ These results     ┆ [{145,[11775]}]   ┆ [11775]           ┆ ["Gopaldass et    ┆ DDB_G0277849     │
│ suggest an inter… ┆                   ┆                   ┆ al. 2011"]        ┆                  │
│ In addition, sodC ┆ [{374,[587]}]     ┆ [587]             ┆ ["Veeranki et al. ┆ DDB_G0282993     │
│ null cells h…     ┆                   ┆                   ┆ 2008"]            ┆                  │
│ Additionally,     ┆ [{127,[1640]}]    ┆ [1640]            ┆ ["Aubry et al.    ┆ DDB_G0289555     │
│ yeast two-hybrid… ┆                   ┆                   ┆ 2003"]            ┆                  │
│ arpB encodes the  ┆ [{67,[2417]}]     ┆ [2417]            ┆ ["Insall et al.   ┆ DDB_G0272106     │
│ 44 kDa actin-…    ┆                   ┆                   ┆ 2001"]            ┆                  │
│ …                 ┆ …                 ┆ …                 ┆ …                 ┆ …                │
│ Furthermore NMR   ┆ [{178,[16786,     ┆ [16786, 17089,    ┆ ["Sheikh et al.   ┆ DDB_G0269230,DDB │
│ and mass spec …   ┆ 17089, 18528]}]   ┆ 18528]            ┆ 2017", "Xu et …   ┆ _G0273251,DDB_…  │
│ In addition, gapA ┆ [{235,[12093]}]   ┆ [12093]           ┆ ["Kee et al.      ┆ DDB_G0269140     │
│ null cells h…     ┆                   ┆                   ┆ 2012"]            ┆                  │
│ An fhbA / fhbB    ┆ [{235,[3038]}]    ┆ [3038]            ┆ ["Iijima et al.   ┆ DDB_G0292378     │
│ double null mut…  ┆                   ┆                   ┆ 2000"]            ┆                  │
│ Thus rheb GTPase  ┆ [{109,[11991]}]   ┆ [11991]           ┆ ["Rosel et al.    ┆ DDB_G0277041     │
│ regulates pha…    ┆                   ┆                   ┆ 2012"]            ┆                  │
│ When activity is  ┆ [{155,[1071]}]    ┆ [1071]            ┆ ["Ponger and Li,  ┆ DDB_G0288047     │
│ observed, it …    ┆                   ┆                   ┆ 2005"]            ┆                  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [13]:
# give claim ID, and we want to explode the list columns together to get one row per (claim_id, publication_id)
m = merged_clean.with_columns(
    pl.col("claim_plain").rank(method="dense").cast(pl.Int64).alias("claim_id")
).select([
    "claim_id",
    "claim_plain",
    "anchors",
    "publication_ids",
    "citation_captions",
    "gene_id"
])

In [14]:
# 2) sanity check: list columns must be aligned per row before explode (len(citation_captions) == len(publication_ids))
bad_rows = (
    m
    .with_columns([
        pl.col("publication_ids").list.len().alias("n_pub"),
        pl.col("citation_captions").list.len().alias("n_cap")
    ])
    .filter(
        (pl.col("n_pub") != pl.col("n_cap")) 
    )
    .select([
        "claim_id",
        "gene_id",
        "n_pub", "n_cap", 
        "claim_plain",
        "anchors",
        "publication_ids",
        "citation_captions"
    ])
    .sort(["n_pub", "n_cap"], descending=True)
)

print("Number of misaligned rows:", bad_rows.height)

with pl.Config(fmt_str_lengths=1000):
    display(bad_rows)

Number of misaligned rows: 4

shape: (4, 8)
┌──────────┬──────────────┬───────┬───────┬──────────────┬─────────────┬─────────────┬─────────────┐
│ claim_id ┆ gene_id      ┆ n_pub ┆ n_cap ┆ claim_plain  ┆ anchors     ┆ publication ┆ citation_ca │
│ ---      ┆ ---          ┆ ---   ┆ ---   ┆ ---          ┆ ---         ┆ _ids        ┆ ptions      │
│ i64      ┆ str          ┆ u32   ┆ u32   ┆ str          ┆ list[struct ┆ ---         ┆ ---         │
│          ┆              ┆       ┆       ┆              ┆ [2]]        ┆ list[i64]   ┆ list[str]   │
╞══════════╪══════════════╪═══════╪═══════╪══════════════╪═════════════╪═════════════╪═════════════╡
│ 1195     ┆ DDB_G0286183 ┆ 2     ┆ 1     ┆ The Dictyost ┆ [{52,[712,  ┆ [712, 659]  ┆ ["Razeto et │
│          ┆              ┆       ┆       ┆ elium Agps   ┆ 659]}]      ┆             ┆ al. .,      │
│          ┆              ┆       ┆       ┆ protein has  ┆             ┆             ┆ 2007"]      │
│          ┆              ┆       ┆       ┆ been crystal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ lized.       ┆             ┆             ┆             │
│ 1534     ┆ DDB_G0287031 ┆ 2     ┆ 1     ┆ These        ┆ [{92,[4035] ┆ [4035,      ┆ ["Brandon   │
│          ┆              ┆       ┆       ┆ results      ┆ }, {93,[403 ┆ 4034]       ┆ et al.      │
│          ┆              ┆       ┆       ┆ reveal that  ┆ 4]}]        ┆             ┆ 1997"]      │
│          ┆              ┆       ┆       ┆ gpaC         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ functions as ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ a regulator  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ of early     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ development  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ gene         ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ expression,. ┆             ┆             ┆             │
│ 1469     ┆ DDB_G0293084 ┆ 2     ┆ 1     ┆ The zizB     ┆ [{147,[1209 ┆ [12098,     ┆ ["Pakes et  │
│          ┆              ┆       ┆       ┆ mutant       ┆ 8]}, {148,[ ┆ 12830]      ┆ al. 2012"]  │
│          ┆              ┆       ┆       ┆ phenotypes   ┆ 12830]}]    ┆             ┆             │
│          ┆              ┆       ┆       ┆ and ZizB     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ binding      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ partners     ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ suggest a    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ central role ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ for ZizB in  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ actin        ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cytoskeletal ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ organization ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and cortical ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ stabilizatio ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ n.,.         ┆             ┆             ┆             │
│ 471      ┆ DDB_G0268620 ┆ 2     ┆ 1     ┆ Fluid uptake ┆ [{113,[2428 ┆ [2428,      ┆ ["Rupper et │
│          ┆              ┆       ┆       ┆ by macropino ┆ ]}, {116,[2 ┆ 2634]       ┆ al. 2001"]  │
│          ┆              ┆       ┆       ┆ cytosis is   ┆ 634]}]      ┆             ┆             │
│          ┆              ┆       ┆       ┆ reduced      ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ about 3 fold ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ and          ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ phagosomes   ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ remain more  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ acidic in    ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ pkbA - null  ┆             ┆             ┆             │
│          ┆              ┆       ┆       ┆ cells (, (.  ┆             ┆             ┆             │
└──────────┴──────────────┴───────┴───────┴──────────────┴─────────────┴─────────────┴─────────────┘

in the 4 cases here, len(publication_ids)>len(citation_captions), after closer look, it is the same author and same year, we manully make a patch here

In [15]:
m_fixed = (
    m.with_columns(
        pl.when(pl.col("claim_id") == 1534)
          .then(pl.lit(["Brandon et al. 1997a", "Brandon et al. 1997b"]))
        .when(pl.col("claim_id") == 471)
          .then(pl.lit(["Rupper et al. 2001a", "Rupper et al. 2001b"]))
        .when(pl.col("claim_id") == 1469)
          .then(pl.lit(["Pakes et al. 2012a", "Pakes et al. 2012b"]))
        .when(pl.col("claim_id") == 1195)
          .then(pl.lit(["Razeto et al. 2007a", "Razeto et al. 2007b"]))
        .otherwise(pl.col("citation_captions"))
        .alias("citation_captions")
    )
)

In [16]:
m_long = (
    m_fixed
    .explode(["publication_ids", "citation_captions"])
    .rename({"publication_ids": "publication_id"})
)

In [17]:
m_long

shape: (2_661, 6)
┌──────────┬─────────────────┬─────────────────┬────────────────┬─────────────────┬────────────────┐
│ claim_id ┆ claim_plain     ┆ anchors         ┆ publication_id ┆ citation_captio ┆ gene_id        │
│ ---      ┆ ---             ┆ ---             ┆ ---            ┆ ns              ┆ ---            │
│ i64      ┆ str             ┆ list[struct[2]] ┆ i64            ┆ ---             ┆ str            │
│          ┆                 ┆                 ┆                ┆ str             ┆                │
╞══════════╪═════════════════╪═════════════════╪════════════════╪═════════════════╪════════════════╡
│ 1985     ┆ pkaC encodes    ┆ [{77,[5939]},   ┆ 5939           ┆ Mann et al.     ┆ DDB_G0283907   │
│          ┆ the catalytic   ┆ {78,[5469]}]    ┆                ┆ 1992            ┆                │
│          ┆ sub…            ┆                 ┆                ┆                 ┆                │
│ 1985     ┆ pkaC encodes    ┆ [{77,[5939]},   ┆ 5469           ┆ Anjard et al.   ┆ DDB_G0283907   │
│          ┆ the catalytic   ┆ {78,[5469]}]    ┆                ┆ 1993            ┆                │
│          ┆ sub…            ┆                 ┆                ┆                 ┆                │
│ 1539     ┆ These results   ┆ [{145,[11775]}] ┆ 11775          ┆ Gopaldass et    ┆ DDB_G0277849   │
│          ┆ suggest an      ┆                 ┆                ┆ al. 2011        ┆                │
│          ┆ inter…          ┆                 ┆                ┆                 ┆                │
│ 694      ┆ In addition,    ┆ [{374,[587]}]   ┆ 587            ┆ Veeranki et al. ┆ DDB_G0282993   │
│          ┆ sodC null cells ┆                 ┆                ┆ 2008            ┆                │
│          ┆ h…              ┆                 ┆                ┆                 ┆                │
│ 101      ┆ Additionally,   ┆ [{127,[1640]}]  ┆ 1640           ┆ Aubry et al.    ┆ DDB_G0289555   │
│          ┆ yeast           ┆                 ┆                ┆ 2003            ┆                │
│          ┆ two-hybrid…     ┆                 ┆                ┆                 ┆                │
│ …        ┆ …               ┆ …               ┆ …              ┆ …               ┆ …              │
│ 498      ┆ Furthermore NMR ┆ [{178,[16786,   ┆ 18528          ┆ West and Kim    ┆ DDB_G0269230,D │
│          ┆ and mass spec … ┆ 17089, 18528]}] ┆                ┆ 2019            ┆ DB_G0273251,DD │
│          ┆                 ┆                 ┆                ┆                 ┆ B_…            │
│ 671      ┆ In addition,    ┆ [{235,[12093]}] ┆ 12093          ┆ Kee et al. 2012 ┆ DDB_G0269140   │
│          ┆ gapA null cells ┆                 ┆                ┆                 ┆                │
│          ┆ h…              ┆                 ┆                ┆                 ┆                │
│ 140      ┆ An fhbA / fhbB  ┆ [{235,[3038]}]  ┆ 3038           ┆ Iijima et al.   ┆ DDB_G0292378   │
│          ┆ double null     ┆                 ┆                ┆ 2000            ┆                │
│          ┆ mut…            ┆                 ┆                ┆                 ┆                │
│ 1643     ┆ Thus rheb       ┆ [{109,[11991]}] ┆ 11991          ┆ Rosel et al.    ┆ DDB_G0277041   │
│          ┆ GTPase          ┆                 ┆                ┆ 2012            ┆                │
│          ┆ regulates pha…  ┆                 ┆                ┆                 ┆                │
│ 1696     ┆ When activity   ┆ [{155,[1071]}]  ┆ 1071           ┆ Ponger and Li,  ┆ DDB_G0288047   │
│          ┆ is observed, it ┆                 ┆                ┆ 2005            ┆                │
│          ┆ …               ┆                 ┆                ┆                 ┆                │
└──────────┴─────────────────┴─────────────────┴────────────────┴─────────────────┴────────────────┘

In [18]:
# now we exlpode anchors
# 1) Build mapping: (claim_id, publication_id) -> anchor_pos
anchor_map = (
    m_fixed
    .select(["claim_id", "anchors"])
    .explode("anchors")  # now each row is one struct {pos, pub_ids}
    .with_columns([
        pl.col("anchors").struct.field("pos").alias("anchor_pos"),
        pl.col("anchors").struct.field("pub_ids").alias("publication_id"),
    ])
    .explode("publication_id")  # one row per pub_id
    .select(["claim_id", "publication_id", "anchor_pos"])
)

# If there can be multiple anchor_pos for the same (claim_id, publication_id), keep them all:
anchor_map = (
    anchor_map
    .group_by(["claim_id", "publication_id"])
    .agg(pl.col("anchor_pos").sort().alias("anchor_pos"))
)

# 2) Join onto m_long
m_long2 = m_long.join(anchor_map, on=["claim_id", "publication_id"], how="left")

# 3) If you want exactly one row per (claim_id, publication_id, anchor_pos), explode anchor_pos:
m_long3 = m_long2.explode("anchor_pos")

# Final columns (example)
m_long3.select([
    "claim_id",
    "claim_plain",
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
])

shape: (2_668, 6)
┌──────────┬───────────────────┬────────────┬────────────────┬──────────────────┬──────────────────┐
│ claim_id ┆ claim_plain       ┆ anchor_pos ┆ publication_id ┆ citation_caption ┆ gene_id          │
│ ---      ┆ ---               ┆ ---        ┆ ---            ┆ s                ┆ ---              │
│ i64      ┆ str               ┆ i64        ┆ i64            ┆ ---              ┆ str              │
│          ┆                   ┆            ┆                ┆ str              ┆                  │
╞══════════╪═══════════════════╪════════════╪════════════════╪══════════════════╪══════════════════╡
│ 1985     ┆ pkaC encodes the  ┆ 77         ┆ 5939           ┆ Mann et al. 1992 ┆ DDB_G0283907     │
│          ┆ catalytic sub…    ┆            ┆                ┆                  ┆                  │
│ 1985     ┆ pkaC encodes the  ┆ 78         ┆ 5469           ┆ Anjard et al.    ┆ DDB_G0283907     │
│          ┆ catalytic sub…    ┆            ┆                ┆ 1993             ┆                  │
│ 1539     ┆ These results     ┆ 145        ┆ 11775          ┆ Gopaldass et al. ┆ DDB_G0277849     │
│          ┆ suggest an inter… ┆            ┆                ┆ 2011             ┆                  │
│ 694      ┆ In addition, sodC ┆ 374        ┆ 587            ┆ Veeranki et al.  ┆ DDB_G0282993     │
│          ┆ null cells h…     ┆            ┆                ┆ 2008             ┆                  │
│ 101      ┆ Additionally,     ┆ 127        ┆ 1640           ┆ Aubry et al.     ┆ DDB_G0289555     │
│          ┆ yeast two-hybrid… ┆            ┆                ┆ 2003             ┆                  │
│ …        ┆ …                 ┆ …          ┆ …              ┆ …                ┆ …                │
│ 498      ┆ Furthermore NMR   ┆ 178        ┆ 18528          ┆ West and Kim     ┆ DDB_G0269230,DDB │
│          ┆ and mass spec …   ┆            ┆                ┆ 2019             ┆ _G0273251,DDB_…  │
│ 671      ┆ In addition, gapA ┆ 235        ┆ 12093          ┆ Kee et al. 2012  ┆ DDB_G0269140     │
│          ┆ null cells h…     ┆            ┆                ┆                  ┆                  │
│ 140      ┆ An fhbA / fhbB    ┆ 235        ┆ 3038           ┆ Iijima et al.    ┆ DDB_G0292378     │
│          ┆ double null mut…  ┆            ┆                ┆ 2000             ┆                  │
│ 1643     ┆ Thus rheb GTPase  ┆ 109        ┆ 11991          ┆ Rosel et al.     ┆ DDB_G0277041     │
│          ┆ regulates pha…    ┆            ┆                ┆ 2012             ┆                  │
│ 1696     ┆ When activity is  ┆ 155        ┆ 1071           ┆ Ponger and Li,   ┆ DDB_G0288047     │
│          ┆ observed, it …    ┆            ┆                ┆ 2005             ┆                  │
└──────────┴───────────────────┴────────────┴────────────────┴──────────────────┴──────────────────┘

In [19]:
# now we get year from citation_captions
YEAR_RE = r"(18|19|20)\d{2}"

m_long3 = m_long3.with_columns(
    year=pl.col("citation_captions")
        .str.extract(YEAR_RE, 0)   # whole match
        .cast(pl.Int32)
)
m_long3

shape: (2_668, 8)
┌──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬──────┐
│ claim_id ┆ claim_plain ┆ anchors     ┆ publication ┆ citation_c ┆ gene_id    ┆ anchor_pos ┆ year │
│ ---      ┆ ---         ┆ ---         ┆ _id         ┆ aptions    ┆ ---        ┆ ---        ┆ ---  │
│ i64      ┆ str         ┆ list[struct ┆ ---         ┆ ---        ┆ str        ┆ i64        ┆ i32  │
│          ┆             ┆ [2]]        ┆ i64         ┆ str        ┆            ┆            ┆      │
╞══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪══════╡
│ 1985     ┆ pkaC        ┆ [{77,[5939] ┆ 5939        ┆ Mann et    ┆ DDB_G02839 ┆ 77         ┆ 1992 │
│          ┆ encodes the ┆ }, {78,[546 ┆             ┆ al. 1992   ┆ 07         ┆            ┆      │
│          ┆ catalytic   ┆ 9]}]        ┆             ┆            ┆            ┆            ┆      │
│          ┆ sub…        ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1985     ┆ pkaC        ┆ [{77,[5939] ┆ 5469        ┆ Anjard et  ┆ DDB_G02839 ┆ 78         ┆ 1993 │
│          ┆ encodes the ┆ }, {78,[546 ┆             ┆ al. 1993   ┆ 07         ┆            ┆      │
│          ┆ catalytic   ┆ 9]}]        ┆             ┆            ┆            ┆            ┆      │
│          ┆ sub…        ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1539     ┆ These       ┆ [{145,[1177 ┆ 11775       ┆ Gopaldass  ┆ DDB_G02778 ┆ 145        ┆ 2011 │
│          ┆ results     ┆ 5]}]        ┆             ┆ et al.     ┆ 49         ┆            ┆      │
│          ┆ suggest an  ┆             ┆             ┆ 2011       ┆            ┆            ┆      │
│          ┆ inter…      ┆             ┆             ┆            ┆            ┆            ┆      │
│ 694      ┆ In          ┆ [{374,[587] ┆ 587         ┆ Veeranki   ┆ DDB_G02829 ┆ 374        ┆ 2008 │
│          ┆ addition,   ┆ }]          ┆             ┆ et al.     ┆ 93         ┆            ┆      │
│          ┆ sodC null   ┆             ┆             ┆ 2008       ┆            ┆            ┆      │
│          ┆ cells h…    ┆             ┆             ┆            ┆            ┆            ┆      │
│ 101      ┆ Additionall ┆ [{127,[1640 ┆ 1640        ┆ Aubry et   ┆ DDB_G02895 ┆ 127        ┆ 2003 │
│          ┆ y, yeast    ┆ ]}]         ┆             ┆ al. 2003   ┆ 55         ┆            ┆      │
│          ┆ two-hybrid… ┆             ┆             ┆            ┆            ┆            ┆      │
│ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …    │
│ 498      ┆ Furthermore ┆ [{178,[1678 ┆ 18528       ┆ West and   ┆ DDB_G02692 ┆ 178        ┆ 2019 │
│          ┆ NMR and     ┆ 6, 17089,   ┆             ┆ Kim 2019   ┆ 30,DDB_G02 ┆            ┆      │
│          ┆ mass spec … ┆ 18528]}]    ┆             ┆            ┆ 73251,DDB_ ┆            ┆      │
│          ┆             ┆             ┆             ┆            ┆ …          ┆            ┆      │
│ 671      ┆ In          ┆ [{235,[1209 ┆ 12093       ┆ Kee et al. ┆ DDB_G02691 ┆ 235        ┆ 2012 │
│          ┆ addition,   ┆ 3]}]        ┆             ┆ 2012       ┆ 40         ┆            ┆      │
│          ┆ gapA null   ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ cells h…    ┆             ┆             ┆            ┆            ┆            ┆      │
│ 140      ┆ An fhbA /   ┆ [{235,[3038 ┆ 3038        ┆ Iijima et  ┆ DDB_G02923 ┆ 235        ┆ 2000 │
│          ┆ fhbB double ┆ ]}]         ┆             ┆ al. 2000   ┆ 78         ┆            ┆      │
│          ┆ null mut…   ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1643     ┆ Thus rheb   ┆ [{109,[1199 ┆ 11991       ┆ Rosel et   ┆ DDB_G02770 ┆ 109        ┆ 2012 │
│          ┆ GTPase      ┆ 1]}]        ┆             ┆ al. 2012   ┆ 41         ┆            ┆      │
│          ┆ regulates   ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ pha…        ┆             ┆             ┆            ┆            ┆            ┆      │
│ 1696     ┆ When        ┆ [{155,[1071 ┆ 1071        ┆ Ponger and ┆ DDB_G02880 ┆ 155        ┆ 2005 │
│          ┆ activity is ┆ ]}]         ┆             ┆ Li, 2005   ┆ 47         ┆            ┆      │
│          ┆ observed,   ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ it …        ┆             ┆             ┆            ┆            ┆            ┆      │
└──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴──────┘

In [20]:
m_long4 = m_long3.select([
    "claim_id",
    "claim_plain",
    "anchors",        # keep if you still want the original struct list
    "anchor_pos",
    "publication_id",
    "citation_captions",
    "gene_id",
    "year",
])

i still see some claims needs cleaned up. They are almost identical with only dot diffrenece.

In [21]:
claim_key_expr = (
    pl.col("claim_plain")
    .str.to_lowercase()
    .str.replace_all(r"\.{2,}", ".")          # ".." / "..." -> "."
    .str.replace_all(r"[^a-z0-9\s]", " ")     # drop punctuation
    .str.replace_all(r"\s+", " ")             # collapse whitespace
    .str.strip_chars()
)

tmp = m_long4.with_columns(
    claim_key=claim_key_expr
)

# Optional: see groups where multiple raw claim_plain map to same key
near_same = (
    tmp.group_by("claim_key")
       .agg([
           pl.len().alias("n_rows"),
           pl.col("claim_plain").n_unique().alias("n_variants"),
           pl.col("claim_plain"),
       ])
       .filter(pl.col("n_variants") > 1)
       .sort("n_rows", descending=True)
)
near_same

shape: (28, 4)
┌─────────────────────────────────┬────────┬────────────┬─────────────────────────────────┐
│ claim_key                       ┆ n_rows ┆ n_variants ┆ claim_plain                     │
│ ---                             ┆ ---    ┆ ---        ┆ ---                             │
│ str                             ┆ u32    ┆ u32        ┆ list[str]                       │
╞═════════════════════════════════╪════════╪════════════╪═════════════════════════════════╡
│ at the trailing edge activated… ┆ 9      ┆ 2          ┆ ["At the trailing edge activat… │
│ the major spore coat proteins … ┆ 9      ┆ 2          ┆ ["The major spore coat protein… │
│ expression of cota sp96 cotb s… ┆ 6      ┆ 2          ┆ ["Expression of cotA (SP96), c… │
│ dictyostelium has three genes … ┆ 6      ┆ 3          ┆ ["Dictyostelium has three gene… │
│ about 100 different proteins c… ┆ 6      ┆ 6          ┆ ["About 100 different proteins… │
│ …                               ┆ …      ┆ …          ┆ …                               │
│ dictyostelium and arabidopsis … ┆ 2      ┆ 2          ┆ ["Dictyostelium and Arabidopsi… │
│ these results suggest the exis… ┆ 2      ┆ 2          ┆ ["These results suggest the ex… │
│ tandem duplications on chromos… ┆ 2      ┆ 2          ┆ ["Tandem duplications on chrom… │
│ the scar wave complex localize… ┆ 2      ┆ 2          ┆ ["The Scar/WAVE complex locali… │
│ these results suggest that the… ┆ 2      ┆ 2          ┆ ["These results suggest that t… │
└─────────────────────────────────┴────────┴────────────┴─────────────────────────────────┘

yes, there are actually quite many near duplicates. shall be also merged

In [22]:
# 2) Create a new merged claim_id based on claim_key
tmp = tmp.with_columns(
    claim_id_new=pl.col("claim_key").rank(method="dense").cast(pl.Int64)
)

# 3) Merge rows safely and keep your column order
#    - choose a canonical claim_plain (first seen)
#    - merge gene_id as union joined by ","
claim_cleaned = (
    tmp
    .group_by([
        "claim_id_new",
        "publication_id",
        "citation_captions",
        "anchor_pos",
        "year",
    ])
    .agg([
        pl.first("claim_plain").alias("claim_plain"),
        pl.first("anchors").alias("anchors"),
        pl.col("gene_id").unique().sort().str.join(",").alias("gene_id"),
    ])
    .select([
        pl.col("claim_id_new").alias("claim_id"),
        "claim_plain",
        "anchors",
        "publication_id",
        "citation_captions",
        "gene_id",
        "anchor_pos",
        "year",
    ])
    .sort(["claim_id", "publication_id", "anchor_pos"])
)

claim_cleaned

shape: (2_636, 8)
┌──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬────────────┬──────┐
│ claim_id ┆ claim_plain ┆ anchors     ┆ publication ┆ citation_c ┆ gene_id    ┆ anchor_pos ┆ year │
│ ---      ┆ ---         ┆ ---         ┆ _id         ┆ aptions    ┆ ---        ┆ ---        ┆ ---  │
│ i64      ┆ str         ┆ list[struct ┆ ---         ┆ ---        ┆ str        ┆ i64        ┆ i32  │
│          ┆             ┆ [2]]        ┆ i64         ┆ str        ┆            ┆            ┆      │
╞══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪════════════╪══════╡
│ 1        ┆ A basic     ┆ [{94,[13954 ┆ 13954       ┆ Brzeska et ┆ DDB_G02891 ┆ 94         ┆ 2014 │
│          ┆ region in   ┆ ]}]         ┆             ┆ al. 2014   ┆ 17         ┆            ┆      │
│          ┆ the tail is ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ …           ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2        ┆ A cDNA      ┆ [{102,[8316 ┆ 8316        ┆ Barklis    ┆ DDB_G02768 ┆ 102        ┆ 1983 │
│          ┆ clone       ┆ ]}]         ┆             ┆ and Lodish ┆ 69         ┆            ┆      │
│          ┆ derived     ┆             ┆             ┆ 1983       ┆            ┆            ┆      │
│          ┆ from psvA…  ┆             ┆             ┆            ┆            ┆            ┆      │
│ 3        ┆ A cDNA      ┆ [{89,[8283] ┆ 8283        ┆ Chisholm   ┆ DDB_G02674 ┆ 89         ┆ 1984 │
│          ┆ clone of    ┆ }]          ┆             ┆ et al.     ┆ 12         ┆            ┆      │
│          ┆ this gene,  ┆             ┆             ┆ 1984       ┆            ┆            ┆      │
│          ┆ D19…        ┆             ┆             ┆            ┆            ┆            ┆      │
│ 4        ┆ A co-immuno ┆ [{158,[1972 ┆ 19729       ┆ Li et al.  ┆ DDB_G02746 ┆ 158        ┆ 2020 │
│          ┆ precipitati ┆ 9]}]        ┆             ┆ 2020       ┆ 07         ┆            ┆      │
│          ┆ on assay…   ┆             ┆             ┆            ┆            ┆            ┆      │
│ 5        ┆ A           ┆ [{185,[1315 ┆ 13151       ┆ Galardi-Ca ┆ DDB_G02689 ┆ 185        ┆ 2013 │
│          ┆ comparison  ┆ 1]}]        ┆             ┆ stilla et  ┆ 20         ┆            ┆      │
│          ┆ of the      ┆             ┆             ┆ al. 2013   ┆            ┆            ┆      │
│          ┆ genes tran… ┆             ┆             ┆            ┆            ┆            ┆      │
│ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …          ┆ …    │
│ 2059     ┆ Yet another ┆ [{131,[4899 ┆ 4899        ┆ Sonnemann  ┆ DDB_G02730 ┆ 131        ┆ 1995 │
│          ┆ role for    ┆ ]}]         ┆             ┆ and Mutzel ┆ 69,DDB_G02 ┆            ┆      │
│          ┆ NDP kinas…  ┆             ┆             ┆ 1995       ┆ 73805      ┆            ┆      │
│ 2060     ┆ zizA null   ┆ [{72,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02750 ┆ 72         ┆ 2012 │
│          ┆ mutant      ┆ ]}]         ┆             ┆ al. 2012   ┆ 35         ┆            ┆      │
│          ┆ cells do    ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ not …       ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2061     ┆ ZizB also   ┆ [{106,[1209 ┆ 12098       ┆ Pakes et   ┆ DDB_G02673 ┆ 106        ┆ 2012 │
│          ┆ interacts   ┆ 8]}]        ┆             ┆ al. 2012   ┆ 74,DDB_G02 ┆            ┆      │
│          ┆ with sever… ┆             ┆             ┆            ┆ 72104      ┆            ┆      │
│ 2062     ┆ zizC is     ┆ [{51,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02752 ┆ 51         ┆ 2012 │
│          ┆ expressed   ┆ ]}]         ┆             ┆ al. 2012   ┆ 39         ┆            ┆      │
│          ┆ throughout  ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ g…          ┆             ┆             ┆            ┆            ┆            ┆      │
│ 2063     ┆ zizD is     ┆ [{51,[12098 ┆ 12098       ┆ Pakes et   ┆ DDB_G02688 ┆ 51         ┆ 2012 │
│          ┆ expressed   ┆ ]}]         ┆             ┆ al. 2012   ┆ 88         ┆            ┆      │
│          ┆ throughout  ┆             ┆             ┆            ┆            ┆            ┆      │
│          ┆ g…          ┆             ┆             ┆            ┆            ┆            ┆      │
└──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴────────────┴──────┘

In [23]:
year_summary = (
    claim_cleaned
    .with_columns(pl.col("year").fill_null(-1).alias("year2"))
    .group_by("year2")
    .agg(pl.len().alias("n"))
    .sort("year2")
    .with_columns(
        pl.when(pl.col("year2") == -1).then(None).otherwise(pl.col("year2")).alias("year")
    )
    .select(["year", "n"])
)

year_summary

shape: (55, 2)
┌──────┬─────┐
│ year ┆ n   │
│ ---  ┆ --- │
│ i32  ┆ u32 │
╞══════╪═════╡
│ null ┆ 7   │
│ 1956 ┆ 1   │
│ 1965 ┆ 1   │
│ 1967 ┆ 3   │
│ 1968 ┆ 1   │
│ …    ┆ …   │
│ 2016 ┆ 76  │
│ 2017 ┆ 58  │
│ 2018 ┆ 81  │
│ 2019 ┆ 85  │
│ 2020 ┆ 34  │
└──────┴─────┘

In [26]:
# claim_cleaned.write_parquet(...)  # intermediate; dropped from output

In [27]:
claim_cleaned.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2063              │
└───────────────────┘

In [28]:
# claim_cleaned TSV export removed (intermediate; dropped from output)

I still see some duplicated claims. There are still a few edge cases. But at this point, I am not gonna trying to “perfectly” clean. I will try to pick up a golden set out of it.

In [29]:
# manual inspection, will pick some golden set maunally later
claim_cleaned_manual = claim_cleaned.filter(pl.col("anchor_pos") != 1)
# claim_cleaned_gold=...

# match pmid

In [30]:
pub_pmid = pl.read_csv(OUTPUT_GOLD_BUILD / "2_publication_id_pmid.csv")
pub_pmid

shape: (4_341, 2)
┌────────────────┬──────────┐
│ publication_id ┆ pmid     │
│ ---            ┆ ---      │
│ i64            ┆ i64      │
╞════════════════╪══════════╡
│ 12             ┆ 21243421 │
│ 13             ┆ 21239624 │
│ 15             ┆ 21235525 │
│ 17             ┆ 20950684 │
│ 20             ┆ 21150268 │
│ …              ┆ …        │
│ 19689          ┆ 32769116 │
│ 19708          ┆ 21551065 │
│ 19728          ┆ 32821814 │
│ 19729          ┆ 32818671 │
│ 19748          ┆ 32850852 │
└────────────────┴──────────┘

In [31]:
# check if all publcation id can be mapped to pmid

# pick the right df names
a = claim_cleaned
b = pub_pmid

# make sure both publication_id columns are the same type (I recommend Int64)
a_ids = a.select(pl.col("publication_id").cast(pl.Int64)).unique()
b_ids = b.select(pl.col("publication_id").cast(pl.Int64)).unique()

# overlap + only-in sets
overlap = a_ids.join(b_ids, on="publication_id", how="inner")
only_a  = a_ids.join(b_ids, on="publication_id", how="anti")
only_b  = b_ids.join(a_ids, on="publication_id", how="anti")

summary = pl.DataFrame({
    "set": ["claim_cleaned", "pub_pmid", "overlap", "only_claim_cleaned", "only_pub_pmid"],
    "unique_count": [a_ids.height, b_ids.height, overlap.height, only_a.height, only_b.height],
})

summary

shape: (5, 2)
┌────────────────────┬──────────────┐
│ set                ┆ unique_count │
│ ---                ┆ ---          │
│ str                ┆ i64          │
╞════════════════════╪══════════════╡
│ claim_cleaned      ┆ 1400         │
│ pub_pmid           ┆ 4341         │
│ overlap            ┆ 1373         │
│ only_claim_cleaned ┆ 27           │
│ only_pub_pmid      ┆ 2968         │
└────────────────────┴──────────────┘

27 ids are not mapped.

In [32]:
claim_cleaned_pmid = (
    claim_cleaned
    .with_columns(pl.col("publication_id").cast(pl.Int64))
    .join(pub_pmid, on="publication_id", how="left")
    .with_columns(
        pl.col("pmid").fill_null("NA")  # or keep as null if you prefer
    )
)

claim_cleaned_pmid

shape: (2_636, 9)
┌──────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ gene_id    ┆ anchor_pos ┆ year ┆ pmid     │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---        ┆ ---        ┆ ---  ┆ ---      │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ str        ┆ i64        ┆ i32  ┆ str      │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆            ┆            ┆      ┆          │
╞══════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 1        ┆ A basic     ┆ [{94,[1395 ┆ 13954      ┆ … ┆ DDB_G02891 ┆ 94         ┆ 2014 ┆ 24747353 │
│          ┆ region in   ┆ 4]}]       ┆            ┆   ┆ 17         ┆            ┆      ┆          │
│          ┆ the tail is ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2        ┆ A cDNA      ┆ [{102,[831 ┆ 8316       ┆ … ┆ DDB_G02768 ┆ 102        ┆ 1983 ┆ 6301681  │
│          ┆ clone       ┆ 6]}]       ┆            ┆   ┆ 69         ┆            ┆      ┆          │
│          ┆ derived     ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ from psvA…  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 3        ┆ A cDNA      ┆ [{89,[8283 ┆ 8283       ┆ … ┆ DDB_G02674 ┆ 89         ┆ 1984 ┆ 6429548  │
│          ┆ clone of    ┆ ]}]        ┆            ┆   ┆ 12         ┆            ┆      ┆          │
│          ┆ this gene,  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ D19…        ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 4        ┆ A co-immuno ┆ [{158,[197 ┆ 19729      ┆ … ┆ DDB_G02746 ┆ 158        ┆ 2020 ┆ 32818671 │
│          ┆ precipitati ┆ 29]}]      ┆            ┆   ┆ 07         ┆            ┆      ┆          │
│          ┆ on assay…   ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 5        ┆ A           ┆ [{185,[131 ┆ 13151      ┆ … ┆ DDB_G02689 ┆ 185        ┆ 2013 ┆ 23577638 │
│          ┆ comparison  ┆ 51]}]      ┆            ┆   ┆ 20         ┆            ┆      ┆          │
│          ┆ of the      ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ genes tran… ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …        │
│ 2059     ┆ Yet another ┆ [{131,[489 ┆ 4899       ┆ … ┆ DDB_G02730 ┆ 131        ┆ 1995 ┆ 7733916  │
│          ┆ role for    ┆ 9]}]       ┆            ┆   ┆ 69,DDB_G02 ┆            ┆      ┆          │
│          ┆ NDP kinas…  ┆            ┆            ┆   ┆ 73805      ┆            ┆      ┆          │
│ 2060     ┆ zizA null   ┆ [{72,[1209 ┆ 12098      ┆ … ┆ DDB_G02750 ┆ 72         ┆ 2012 ┆ 22366457 │
│          ┆ mutant      ┆ 8]}]       ┆            ┆   ┆ 35         ┆            ┆      ┆          │
│          ┆ cells do    ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ not …       ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2061     ┆ ZizB also   ┆ [{106,[120 ┆ 12098      ┆ … ┆ DDB_G02673 ┆ 106        ┆ 2012 ┆ 22366457 │
│          ┆ interacts   ┆ 98]}]      ┆            ┆   ┆ 74,DDB_G02 ┆            ┆      ┆          │
│          ┆ with sever… ┆            ┆            ┆   ┆ 72104      ┆            ┆      ┆          │
│ 2062     ┆ zizC is     ┆ [{51,[1209 ┆ 12098      ┆ … ┆ DDB_G02752 ┆ 51         ┆ 2012 ┆ 22366457 │
│          ┆ expressed   ┆ 8]}]       ┆            ┆   ┆ 39         ┆            ┆      ┆          │
│          ┆ throughout  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ g…          ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 2063     ┆ zizD is     ┆ [{51,[1209 ┆ 12098      ┆ … ┆ DDB_G02688 ┆ 51         ┆ 2012 ┆ 22366457 │
│          ┆ expressed   ┆ 8]}]       ┆            ┆   ┆ 88         ┆            ┆      ┆          │
│          ┆ throughout  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ g…          ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
└──────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

In [33]:
# claim_cleaned_pmid.write_parquet(...)  # intermediate; dropped from output

claim_cleaned_pmid_nonNA = claim_cleaned_pmid.filter(
    pl.col("pmid").is_not_null() & (pl.col("pmid") != "NA")
)

# claim_cleaned_pmid_nonNA.write_parquet(...)  # intermediate; dropped from output

In [34]:
claim_cleaned_pmid_nonNA.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2040              │
└───────────────────┘

In [35]:
claim_cleaned_pmid_nonNA.select(
    pl.col("pmid").n_unique().alias("n_unique_pmid")
)

shape: (1, 1)
┌───────────────┐
│ n_unique_pmid │
│ ---           │
│ u32           │
╞═══════════════╡
│ 1372          │
└───────────────┘

# how many we claims having abstracts on EPMC

In [37]:
EPMC = pl.read_parquet(OUTPUT_GOLD_BUILD / "3_articles_cleaned_abstract.parquet")

In [38]:
EPMC

shape: (20_447, 9)
┌──────────┬────────────┬────────────┬──────┬───┬────────────┬────────────┬────────────┬───────────┐
│ pmid     ┆ pmcid      ┆ doi        ┆ year ┆ … ┆ journal    ┆ authors    ┆ abstract_c ┆ file      │
│ ---      ┆ ---        ┆ ---        ┆ ---  ┆   ┆ ---        ┆ ---        ┆ lean       ┆ ---       │
│ str      ┆ str        ┆ str        ┆ str  ┆   ┆ str        ┆ str        ┆ ---        ┆ str       │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ str        ┆           │
╞══════════╪════════════╪════════════╪══════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 2654141  ┆ PMC2115546 ┆ 10.1083/jc ┆ 1989 ┆ … ┆ The        ┆ Sanders    ┆ Chlamydomo ┆ article_f │
│          ┆            ┆ b.108.5.17 ┆      ┆   ┆ Journal of ┆ MA,        ┆ nas cells  ┆ etching/o │
│          ┆            ┆ 51         ┆      ┆   ┆ cell       ┆ Salisbury  ┆ excise     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ biology    ┆ JL.        ┆ the…       ┆ _cl…      │
│ 39528565 ┆ PMC1155504 ┆ 10.1038/s4 ┆ 2024 ┆ … ┆ Nature com ┆ Lim YJ,    ┆ Plant      ┆ article_f │
│          ┆ 5          ┆ 1467-024-5 ┆      ┆   ┆ munication ┆ Yoon YJ,   ┆ pathogens  ┆ etching/o │
│          ┆            ┆ 4272-4     ┆      ┆   ┆ s          ┆ Lee H,     ┆ secrete    ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Choi G…    ┆ nuclea…    ┆ _cl…      │
│ 6319129  ┆ null       ┆ 10.1111/j. ┆ 1984 ┆ … ┆ European   ┆ Scholübber ┆ The        ┆ article_f │
│          ┆            ┆ 1432-1033. ┆      ┆   ┆ journal of ┆ s HG, van  ┆ ability of ┆ etching/o │
│          ┆            ┆ 1984.tb078 ┆      ┆   ┆ biochemist ┆ Knippenber ┆ 24 systema ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆ …          ┆ …          ┆ tical…     ┆ _cl…      │
│ 28740830 ┆ PMC5502327 ┆ 10.3389/fo ┆ 2017 ┆ … ┆ Frontiers  ┆ Mammucari  ┆ Mitochondr ┆ article_f │
│          ┆            ┆ nc.2017.00 ┆      ┆   ┆ in         ┆ C,         ┆ ial Ca2+   ┆ etching/o │
│          ┆            ┆ 139        ┆      ┆   ┆ oncology   ┆ Gherardi   ┆ uptake     ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ G, Rizzu…  ┆ play…      ┆ _cl…      │
│ 18814278 ┆ null       ┆ 10.1002/cm ┆ 2008 ┆ … ┆ Cell       ┆ Asano Y,   ┆ Chemotaxis ┆ article_f │
│          ┆            ┆ .20314     ┆      ┆   ┆ motility   ┆ Nagasaki   ┆ -deficient ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆ and the    ┆ A, Uyeda   ┆ amiB-null… ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ cytoskel…  ┆ TQ.        ┆            ┆ _cl…      │
│ …        ┆ …          ┆ …          ┆ …    ┆ … ┆ …          ┆ …          ┆ …          ┆ …         │
│ 36543032 ┆ PMC9889102 ┆ 10.1016/j. ┆ 2023 ┆ … ┆ European   ┆ Smith JD,  ┆ Muscle     ┆ article_f │
│          ┆            ┆ ejmech.202 ┆      ┆   ┆ journal of ┆ Brawley J, ┆ myosin     ┆ etching/o │
│          ┆            ┆ 2.115008   ┆      ┆   ┆ medicinal  ┆ Bordenave… ┆ inhibition ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ …          ┆            ┆ could…     ┆ _cl…      │
│ 20023070 ┆ PMC2823002 ┆ 10.1128/ec ┆ 2010 ┆ … ┆ Eukaryotic ┆ Schilde C, ┆ We have    ┆ article_f │
│          ┆            ┆ .00220-09  ┆      ┆   ┆ cell       ┆ Schönemann ┆ identified ┆ etching/o │
│          ┆            ┆            ┆      ┆   ┆            ┆ B, Sehri…  ┆ new        ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆            ┆ synapto…   ┆ _cl…      │
│ 10706824 ┆ null       ┆ 10.1006/sc ┆ 1999 ┆ … ┆ Seminars   ┆ Mohanty S, ┆ The        ┆ article_f │
│          ┆            ┆ db.1999.03 ┆      ┆   ┆ in cell &  ┆ Firtel RA. ┆ spatial    ┆ etching/o │
│          ┆            ┆ 43         ┆      ┆   ┆ developmen ┆            ┆ patterning ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆ t…         ┆            ┆ of pres…   ┆ _cl…      │
│ 39396247 ┆ PMC1148569 ┆ 10.1080/19 ┆ 2024 ┆ … ┆ Gut        ┆ Roy M,     ┆ Metabolic  ┆ article_f │
│          ┆ 4          ┆ 490976.202 ┆      ┆   ┆ microbes   ┆ Dumay A,   ┆ syndrome   ┆ etching/o │
│          ┆            ┆ 4.2409210  ┆      ┆   ┆            ┆ Adiba S,   ┆ (MetS) is  ┆ utput/all │
│          ┆            ┆            ┆      ┆   ┆            ┆ Rozes…     ┆ a…         ┆ _cl…      │
│ 18460092 ┆ PMC2666851 ┆ 10.1111/j. ┆ 2008 ┆ … ┆ Evolution  ┆ Okoruwa    ┆ Prestin    ┆ article_f │
│          ┆            ┆ 1525-142x. ┆      ┆   ┆ & developm ┆ OE, Weston ┆ (SLC26A5)  ┆ etching/o │
│          ┆            ┆ 2008.00239 ┆      ┆   ┆ ent        ┆ MD,        ┆ is the     ┆ utput/all │
│          ┆            ┆ …          ┆      ┆   ┆            ┆ Sanjeev…   ┆ molec…     ┆ _cl…      │
└──────────┴────────────┴────────────┴──────┴───┴────────────┴────────────┴────────────┴───────────┘

In [39]:
a = claim_cleaned_pmid_nonNA.select(pl.col("pmid").cast(pl.Utf8).alias("pmid")).unique()
b = EPMC.select(pl.col("pmid").cast(pl.Utf8).alias("pmid")).unique()

overlap = a.join(b, on="pmid", how="inner")
only_a  = a.join(b, on="pmid", how="anti")
only_b  = b.join(a, on="pmid", how="anti")

summary = pl.DataFrame({
    "set": ["claim_cleaned_pmid_nonNA", "epmc_df", "overlap", "only_claim_cleaned_pmid", "only_epmc_df"],
    "unique_count": [a.height, b.height, overlap.height, only_a.height, only_b.height],
})

summary

shape: (5, 2)
┌──────────────────────────┬──────────────┐
│ set                      ┆ unique_count │
│ ---                      ┆ ---          │
│ str                      ┆ i64          │
╞══════════════════════════╪══════════════╡
│ claim_cleaned_pmid_nonNA ┆ 1372         │
│ epmc_df                  ┆ 20447        │
│ overlap                  ┆ 1340         │
│ only_claim_cleaned_pmid  ┆ 32           │
│ only_epmc_df             ┆ 19107        │
└──────────────────────────┴──────────────┘

In [40]:
only_claim_pmids = only_a.get_column("pmid")

rows_only_claim = claim_cleaned_pmid.filter(
    pl.col("pmid").cast(pl.Utf8).is_in(only_claim_pmids)
)

rows_only_claim

/var/folders/yr/ljjqmpj92wncw9wrv495wq300000gn/T/ipykernel_22397/496506703.py:3: DeprecationWarning: `is_in` with a collection of the same datatype is ambiguous and deprecated.
Please use `implode` to return to previous behavior.

See https://github.com/pola-rs/polars/issues/22149 for more information.
  rows_only_claim = claim_cleaned_pmid.filter(

shape: (43, 9)
┌──────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬──────┬──────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ gene_id    ┆ anchor_pos ┆ year ┆ pmid     │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---        ┆ ---        ┆ ---  ┆ ---      │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ str        ┆ i64        ┆ i32  ┆ str      │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆            ┆            ┆      ┆          │
╞══════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════╪══════════╡
│ 98       ┆ Adenylyl    ┆ [{133,[978 ┆ 9781       ┆ … ┆ DDB_G02815 ┆ 133        ┆ 1977 ┆ 191758   │
│          ┆ cyclase     ┆ 1]}, {136, ┆            ┆   ┆ 45         ┆            ┆      ┆          │
│          ┆ increases   ┆ [10027]},  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ mor…        ┆ …          ┆            ┆   ┆            ┆            ┆      ┆          │
│ 98       ┆ Adenylyl    ┆ [{133,[978 ┆ 10027      ┆ … ┆ DDB_G02815 ┆ 136        ┆ 1976 ┆ 183985   │
│          ┆ cyclase     ┆ 1]}, {136, ┆            ┆   ┆ 45         ┆            ┆      ┆          │
│          ┆ increases   ┆ [10027]},  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ mor…        ┆ …          ┆            ┆   ┆            ┆            ┆      ┆          │
│ 200      ┆ axeB was    ┆ [{139,[102 ┆ 10264      ┆ … ┆ DDB_G03506 ┆ 139        ┆ 1974 ┆ 4474353  │
│          ┆ identified  ┆ 64]}, {142 ┆            ┆   ┆ 52         ┆            ┆      ┆          │
│          ┆ as a mutan… ┆ ,[7409]}]  ┆            ┆   ┆            ┆            ┆      ┆          │
│ 206      ┆ Biochemical ┆ [{114,[107 ┆ 10751      ┆ … ┆ DDB_G02898 ┆ 114        ┆ 1967 ┆ 6067273  │
│          ┆ assays      ┆ 51]}]      ┆            ┆   ┆ 75         ┆            ┆      ┆          │
│          ┆ found a 10  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 207      ┆ Biochemical ┆ [{126,[107 ┆ 10751      ┆ … ┆ DDB_G02778 ┆ 126        ┆ 1967 ┆ 6067273  │
│          ┆ assays      ┆ 51]}]      ┆            ┆   ┆ 79         ┆            ┆      ┆          │
│          ┆ found a 10  ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ …           ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …          ┆ …          ┆ …    ┆ …        │
│ 1661     ┆ The major   ┆ [{172,[938 ┆ 6653       ┆ … ┆ DDB_G02769 ┆ 175        ┆ 1989 ┆ 2587278  │
│          ┆ spore coat  ┆ 7]}, {173, ┆            ┆   ┆ 41         ┆            ┆      ┆          │
│          ┆ proteins,…  ┆ [8541]},   ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆             ┆ ……         ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1661     ┆ The major   ┆ [{172,[938 ┆ 9387       ┆ … ┆ DDB_G02767 ┆ 172        ┆ 1979 ┆ 499661   │
│          ┆ spore coat  ┆ 7]}, {173, ┆            ┆   ┆ 61,DDB_G02 ┆            ┆      ┆          │
│          ┆ proteins,…  ┆ [8541]},   ┆            ┆   ┆ 77141,DDB_ ┆            ┆      ┆          │
│          ┆             ┆ ……         ┆            ┆   ┆ …          ┆            ┆      ┆          │
│ 1783     ┆ The         ┆ [{201,[107 ┆ 10721      ┆ … ┆ DDB_G02676 ┆ 201        ┆ 1967 ┆ 6069170  │
│          ┆ specific    ┆ 21]}, {202 ┆            ┆   ┆ 74         ┆            ┆      ┆          │
│          ┆ activity of ┆ ,[9996]}]  ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ glyco…      ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1787     ┆ The         ┆ [{117,[666 ┆ 6662       ┆ … ┆ DDB_G02762 ┆ 117        ┆ 1989 ┆ 2546676  │
│          ┆ subunits    ┆ 2]}, {118, ┆            ┆   ┆ 67         ┆            ┆      ┆          │
│          ┆ interact    ┆ [5414]},   ┆            ┆   ┆            ┆            ┆      ┆          │
│          ┆ with dow…   ┆ ……         ┆            ┆   ┆            ┆            ┆      ┆          │
│ 1801     ┆ The WASH    ┆ [{36,[1772 ┆ 17728      ┆ … ┆ DDB_G02885 ┆ 36         ┆ 2013 ┆ 23993425 │
│          ┆ complex is  ┆ 8]}]       ┆            ┆   ┆ 69         ┆            ┆      ┆          │
│          ┆ highly con… ┆            ┆            ┆   ┆            ┆            ┆      ┆          │
└──────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴──────┴──────────┘

Some claims are not covered. It seems that most of them are old paper that there are no abstract available. So I remove those and merge title and abstract to the claim table

In [41]:
epmc_small = EPMC.select([
    pl.col("pmid").cast(pl.Utf8).alias("pmid"),
    pl.col("title").alias("title"),
    pl.col("abstract_clean").alias("abstract_clean"),
])

claim_small = claim_cleaned_pmid_nonNA.with_columns(
    pl.col("pmid").cast(pl.Utf8).alias("pmid")
)

# inner join = ignore only-claim PMIDs
claim_cleaned_pmid_nonNA_abstract = claim_small.join(epmc_small, on="pmid", how="inner")

claim_cleaned_pmid_nonNA_abstract

shape: (2_561, 11)
┌──────────┬─────────────┬────────────┬────────────┬───┬──────┬──────────┬────────────┬────────────┐
│ claim_id ┆ claim_plain ┆ anchors    ┆ publicatio ┆ … ┆ year ┆ pmid     ┆ title      ┆ abstract_c │
│ ---      ┆ ---         ┆ ---        ┆ n_id       ┆   ┆ ---  ┆ ---      ┆ ---        ┆ lean       │
│ i64      ┆ str         ┆ list[struc ┆ ---        ┆   ┆ i32  ┆ str      ┆ str        ┆ ---        │
│          ┆             ┆ t[2]]      ┆ i64        ┆   ┆      ┆          ┆            ┆ str        │
╞══════════╪═════════════╪════════════╪════════════╪═══╪══════╪══════════╪════════════╪════════════╡
│ 1878     ┆ These       ┆ [{175,[162 ┆ 16288      ┆ … ┆ 2017 ┆ 28413119 ┆ The two    ┆ Autophagy  │
│          ┆ results     ┆ 88]}]      ┆            ┆   ┆      ┆          ┆ Dictyostel ┆ is a       │
│          ┆ suggest     ┆            ┆            ┆   ┆      ┆          ┆ ium        ┆ highly     │
│          ┆ that Atg…   ┆            ┆            ┆   ┆      ┆          ┆ discoide…  ┆ conserve…  │
│ 403      ┆ Disruption  ┆ [{103,[663 ┆ 6630       ┆ … ┆ 1989 ┆ 2515990  ┆ Selective  ┆ The        │
│          ┆ of csaA     ┆ 0]}]       ┆            ┆   ┆      ┆          ┆ eliminatio ┆ contact    │
│          ┆ results in  ┆            ┆            ┆   ┆      ┆          ┆ n of the   ┆ site A gly │
│          ┆ …           ┆            ┆            ┆   ┆      ┆          ┆ c…         ┆ coprotei…  │
│ 1105     ┆ MyoB is non ┆ [{163,[660 ┆ 12097      ┆ … ┆ 2012 ┆ 22367211 ┆ Molecular  ┆ Class I    │
│          ┆ -filamentou ┆ 8]}, {164, ┆            ┆   ┆      ┆          ┆ basis of   ┆ myosins    │
│          ┆ s and co…   ┆ [6857]},   ┆            ┆   ┆      ┆          ┆ dynamic    ┆ have a     │
│          ┆             ┆ {…         ┆            ┆   ┆      ┆          ┆ rel…       ┆ single …   │
│ 1196     ┆ pestis      ┆ [{235,[171 ┆ 17146      ┆ … ┆ 2018 ┆ 29350155 ┆ Yersinia   ┆ Plague     │
│          ┆ recruits    ┆ 46]}]      ┆            ┆   ┆      ┆          ┆ pestis     ┆ ecology is │
│          ┆ host Rab1B  ┆            ┆            ┆   ┆      ┆          ┆ Survival   ┆ characteri │
│          ┆ pro…        ┆            ┆            ┆   ┆      ┆          ┆ and R…     ┆ ze…        │
│ 582      ┆ FspA        ┆ [{122,[135 ┆ 13550      ┆ … ┆ 2013 ┆ 24128258 ┆ Two        ┆ Recognitio │
│          ┆ protein is  ┆ 50]}]      ┆            ┆   ┆      ┆          ┆ distinct   ┆ n of       │
│          ┆ an          ┆            ┆            ┆   ┆      ┆          ┆ sensing    ┆ bacteria   │
│          ┆ essential   ┆            ┆            ┆   ┆      ┆          ┆ pathways … ┆ by met…    │
│          ┆ c…          ┆            ┆            ┆   ┆      ┆          ┆            ┆            │
│ …        ┆ …           ┆ …          ┆ …          ┆ … ┆ …    ┆ …        ┆ …          ┆ …          │
│ 439      ┆ Dominant    ┆ [{174,[174 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ negative    ┆ 91]}]      ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ rabS cells  ┆            ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆ d…          ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 1309     ┆ Rab2A is    ┆ [{83,[1542 ┆ 17491      ┆ … ┆ 2018 ┆ 29843387 ┆ The Effect ┆ Rab        │
│          ┆ associated  ┆ 2]}, {136, ┆            ┆   ┆      ┆          ┆ of Overexp ┆ GTPases    │
│          ┆ with both … ┆ [17491]}]  ┆            ┆   ┆      ┆          ┆ ressed Dd… ┆ are        │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ essential  │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆            ┆ regu…      │
│ 516      ┆ Expression  ┆ [{169,[116 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ of cotE is  ┆ 02]}]      ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ dependen…   ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆             ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 536      ┆ extended    ┆ [{0,[11602 ┆ 11602      ┆ … ┆ 2011 ┆ 21810415 ┆ BzpF is a  ┆ The cAMP   │
│          ┆ these       ┆ ]}]        ┆            ┆   ┆      ┆          ┆ CREB-like  ┆ response   │
│          ┆ findings    ┆            ┆            ┆   ┆      ┆          ┆ transcript ┆ element-bi │
│          ┆ and de…     ┆            ┆            ┆   ┆      ┆          ┆ …          ┆ nd…        │
│ 2040     ┆ When        ┆ [{155,[107 ┆ 1071       ┆ … ┆ 2005 ┆ 15689527 ┆ Evolutiona ┆ In eukaryo │
│          ┆ activity is ┆ 1]}]       ┆            ┆   ┆      ┆          ┆ ry diversi ┆ tes, C5-cy │
│          ┆ observed,   ┆            ┆            ┆   ┆      ┆          ┆ fication   ┆ tosine     │
│          ┆ it …        ┆            ┆            ┆   ┆      ┆          ┆ o…         ┆ met…       │
└──────────┴─────────────┴────────────┴────────────┴───┴──────┴──────────┴────────────┴────────────┘

In [42]:
# claim_cleaned_pmid_nonNA_abstract.write_parquet(...)  # intermediate; dropped from output

In [43]:
claim_cleaned_pmid_nonNA_abstract.select(
    pl.col("claim_id").n_unique().alias("n_unique_claim_id")
)

shape: (1, 1)
┌───────────────────┐
│ n_unique_claim_id │
│ ---               │
│ u32               │
╞═══════════════════╡
│ 2020              │
└───────────────────┘

In [44]:
claim_cleaned_pmid_nonNA_abstract.select(
    pl.col("pmid").n_unique().alias("n_unique_pmid")
)

shape: (1, 1)
┌───────────────┐
│ n_unique_pmid │
│ ---           │
│ u32           │
╞═══════════════╡
│ 1340          │
└───────────────┘

# clean up even more and help for narrow down to a golden set

In [45]:
claims_u = (
    claim_cleaned_pmid_nonNA_abstract.select(["claim_id", "claim_plain"])
        .unique(subset=["claim_id"])
        .sort("claim_id")
)
claims_u.height

2020

In [46]:
claims_u = claims_u.with_columns(
    claim_sim=(
        pl.col("claim_plain")
        # remove bracket chars
        .str.replace_all(r"[()\[\]{}]", "")
        # ; -> ,
        .str.replace_all(r";", ",")
        # collapse obvious runs
        .str.replace_all(r"\.{2,}", ".")
        .str.replace_all(r",(\s*,)+", ",")
        # fix mixed combos
        .str.replace_all(r",\s*\.", ".")
        .str.replace_all(r"\.\s*,", ".")
        # spacing rules
        .str.replace_all(r"\s+([,.])", r"$1")          # no space before , .
        .str.replace_all(r",([A-Za-z0-9])", r", $1")   # space after comma
        .str.replace_all(r"\.([A-Za-z])", r". $1")     # space after dot only before letters (avoids 3.14 -> 3. 14)
        # final whitespace cleanup
        .str.replace_all(r"\s+", " ")
        .str.strip_chars()
    )
)

In [47]:
# # take a look
# (
#     claims_u
#     .write_csv("tmp/claims_u.tsv", separator="\t")
# )

Cluster near-duplicates with TF-IDF char ngrams

In [48]:
texts = claims_u.get_column("claim_sim").to_list()
ids   = claims_u.get_column("claim_id").to_list()
n = len(ids)

# --- TF-IDF (char ngrams) ---
vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=1)
X = vec.fit_transform(texts)

# --- Nearest neighbors (candidate pairs) ---
k = 30  #  <-----------lower value might miss pairs, larger values might slow down
nn = NearestNeighbors(n_neighbors=min(k, n), metric="cosine").fit(X)
dist, idx = nn.kneighbors(X, return_distance=True)

# --- Build candidate pair list with similarities ---
# (we'll inspect these, and also use them for clustering)
pairs = []
for i in range(n):
    for d, j in zip(dist[i], idx[i]):
        if j <= i:
            continue
        sim = 1.0 - float(d)
        pairs.append((i, j, sim))

pairs.sort(key=lambda x: x[2], reverse=True)

# Inspect top similar pairs (e.g. top 100)
topN = 10                               # <-------------------change here for look longer list
pairs_df = pl.DataFrame(
    {
        "i": [p[0] for p in pairs[:topN]],
        "j": [p[1] for p in pairs[:topN]],
        "sim": [p[2] for p in pairs[:topN]],
        "claim_id_i": [ids[p[0]] for p in pairs[:topN]],
        "claim_id_j": [ids[p[1]] for p in pairs[:topN]],
        "text_i": [texts[p[0]] for p in pairs[:topN]],
        "text_j": [texts[p[1]] for p in pairs[:topN]],
    }
).sort("sim", descending=True)

with pl.Config(fmt_str_lengths=500, tbl_rows=topN, tbl_cols=20):
    display(pairs_df)

shape: (10, 7)
┌──────┬──────┬──────────┬────────────┬────────────┬───────────────────────┬───────────────────────┐
│ i    ┆ j    ┆ sim      ┆ claim_id_i ┆ claim_id_j ┆ text_i                ┆ text_j                │
│ ---  ┆ ---  ┆ ---      ┆ ---        ┆ ---        ┆ ---                   ┆ ---                   │
│ i64  ┆ i64  ┆ f64      ┆ i64        ┆ i64        ┆ str                   ┆ str                   │
╞══════╪══════╪══════════╪════════════╪════════════╪═══════════════════════╪═══════════════════════╡
│ 371  ┆ 372  ┆ 0.995934 ┆ 381        ┆ 382        ┆ Dictyostelium has 71  ┆ Dictyostelium has 71  │
│      ┆      ┆          ┆            ┆            ┆ ABC transporters      ┆ ABC transporters      │
│      ┆      ┆          ┆            ┆            ┆ including one on the  ┆ including one on the  │
│      ┆      ┆          ┆            ┆            ┆ chromosome 2          ┆ chromosome 2          │
│      ┆      ┆          ┆            ┆            ┆ duplication and 11    ┆ duplication,          │
│      ┆      ┆          ┆            ┆            ┆ ABCA family members:  ┆ including 11 ABCA     │
│      ┆      ┆          ┆            ┆            ┆ abcA1, abcA2, abcA3,  ┆ family members:       │
│      ┆      ┆          ┆            ┆            ┆ abcA4, abcA5, abcA6,  ┆ abcA1, abcA2, abcA3,  │
│      ┆      ┆          ┆            ┆            ┆ abcA7, abcA8, abcA9,  ┆ abcA4, abcA5, abcA6,  │
│      ┆      ┆          ┆            ┆            ┆ abcA10, and abcA11,   ┆ abcA7, abcA8, abcA9,  │
│      ┆      ┆          ┆            ┆            ┆ One of the defining   ┆ abcA10, and abcA11,   │
│      ┆      ┆          ┆            ┆            ┆ characteristics of    ┆ One of the defining   │
│      ┆      ┆          ┆            ┆            ┆ the A family is the   ┆ characteristics of    │
│      ┆      ┆          ┆            ┆            ┆ presence of a         ┆ the A family is the   │
│      ┆      ┆          ┆            ┆            ┆ regulatory domain     ┆ presence of a         │
│      ┆      ┆          ┆            ┆            ┆ with multiple sites   ┆ regulatory domain     │
│      ┆      ┆          ┆            ┆            ┆ for phosphorylation   ┆ with multiple sites   │
│      ┆      ┆          ┆            ┆            ┆ by various protein    ┆ for phosphorylation   │
│      ┆      ┆          ┆            ┆            ┆ kinases in the region ┆ by various protein    │
│      ┆      ┆          ┆            ┆            ┆ after the first ABC   ┆ kinases in the region │
│      ┆      ┆          ┆            ┆            ┆ domain.               ┆ after the first ABC   │
│      ┆      ┆          ┆            ┆            ┆                       ┆ domain.               │
│ 1966 ┆ 1967 ┆ 0.992799 ┆ 2008       ┆ 2009       ┆ Triple mutant cells   ┆ Triple mutants cells  │
│      ┆      ┆          ┆            ┆            ┆ lacking myoD, myoE    ┆ lacking myoD, myoE    │
│      ┆      ┆          ┆            ┆            ┆ and myoF are          ┆ and myoF are          │
│      ┆      ┆          ┆            ┆            ┆ defective in          ┆ defective in          │
│      ┆      ┆          ┆            ┆            ┆ chemotaxis to cAMP,   ┆ chemotaxis to cAMP,   │
│      ┆      ┆          ┆            ┆            ┆ chemoattractant-stimu ┆ chemoattractant-stimu │
│      ┆      ┆          ┆            ┆            ┆ lated actin           ┆ lated actin           │
│      ┆      ┆          ┆            ┆            ┆ polymerization and    ┆ polymerization and    │
│      ┆      ┆          ┆            ┆            ┆ phagocytosis.         ┆ phagocytosis.         │
│ 1105 ┆ 1186 ┆ 0.992057 ┆ 1132       ┆ 1215       ┆ NapA and PirA         ┆ PirA and NapA also    │
│      ┆      ┆          ┆            ┆            ┆ interact to form an   ┆ interact to form an   │
│      ┆      ┆          ┆            ┆            ┆ independent           ┆ independent           │
│      ┆      ┆          ┆            ┆            ┆ heterodimeric         ┆ heterodimeric         │
│      ┆      ┆          ┆            ┆            ┆ subcomplex prior to   ┆ subcomplex prior to   │
│      ┆      ┆          ┆            ┆            ┆ formation of the      ┆ formation of the      │
│      ┆      ┆          ┆            ┆            ┆ mature Scar/WAVE      ┆ mature Scar/WAVE      │
│      ┆      ┆          ┆            ┆            ┆ complex.              ┆ complex.              │
│ 347  ┆ 546  ┆ 0.989565 ┆ 357        ┆ 563        ┆ demonstrate two       ┆ For pstA-specific     │
│      ┆      ┆          ┆            ┆            ┆ distinct signaling    ┆ genes, demonstrate    │
│      ┆      ┆          ┆            ┆            ┆ pathways for          ┆ two distinct          │
│      ┆      ┆          ┆            ┆            ┆ pstA-specific genes   ┆ signaling pathways    │
│      ┆      ┆          ┆            ┆            ┆ downstream of STATa:  ┆ downstream of STATa:  │
│      ┆      ┆          ┆            ┆            ┆ CudA-dependent and    ┆ CudA-dependent and    │
│      ┆      ┆          ┆            ┆            ┆ CudA-independent.     ┆ CudA-independent.     │
│ 474  ┆ 475  ┆ 0.984793 ┆ 491        ┆ 492        ┆ Endosomes are         ┆ Endosomes are         │
│      ┆      ┆          ┆            ┆            ┆ transported along     ┆ transported along     │
│      ┆      ┆          ┆            ┆            ┆ microtubules with     ┆ microtubules with     │
│      ┆      ┆          ┆            ┆            ┆ frequent reversals in ┆ frequent reversals in │
│      ┆      ┆          ┆            ┆            ┆ direction due to a    ┆ direction due to a    │
│      ┆      ┆          ┆            ┆            ┆ tug-of-war between    ┆ tug-of-war between    │
│      ┆      ┆          ┆            ┆            ┆ dynein pulling to the ┆ kinesin kif1 pulling  │
│      ┆      ┆          ┆            ┆            ┆ minus-end and kinesin ┆ to the plus-end and   │
│      ┆      ┆          ┆            ┆            ┆ kif1 pulling to the   ┆ dynein dhcA pulling   │
│      ┆      ┆          ┆            ┆            ┆ plus-end.             ┆ to the minus-end.     │
│ 236  ┆ 1535 ┆ 0.981453 ┆ 245        ┆ 1568       ┆ CARMIL localizes in   ┆ The CARMIL complex    │
│      ┆      ┆          ┆            ┆            ┆ dynamic actin-rich    ┆ localizes in dynamic  │
│      ┆      ┆          ┆            ┆            ┆ cellular extensions,  ┆ actin-rich cellular   │
│      ┆      ┆          ┆            ┆            ┆ including the leading ┆ extensions, including │
│      ┆      ┆          ┆            ┆            ┆ edge of chemotaxing   ┆ the leading edge of   │
│      ┆      ┆          ┆            ┆            ┆ cells and             ┆ chemotaxing cells and │
│      ┆      ┆          ┆            ┆            ┆ macropinocytic        ┆ macropinocytic        │
│      ┆      ┆          ┆            ┆            ┆ extensions.           ┆ extensions.           │
│ 129  ┆ 133  ┆ 0.980474 ┆ 135        ┆ 139        ┆ An analysis of        ┆ An analysis of        │
│      ┆      ┆          ┆            ┆            ┆ Dictyostelium ras     ┆ Dictyostelium ras     │
│      ┆      ┆          ┆            ┆            ┆ family genes reveals  ┆ family genes reveals  │
│      ┆      ┆          ┆            ┆            ┆ that rasU rasU, rasV  ┆ that rasU, rasV rasV, │
│      ┆      ┆          ┆            ┆            ┆ rasV, rasW rasW, rasX ┆ rasW rasW, rasX rasX, │
│      ┆      ┆          ┆            ┆            ┆ rasX, rasY rasY and   ┆ rasY rasY and rasZ    │
│      ┆      ┆          ┆            ┆            ┆ rasZ form a separate  ┆ rasZ form a separate  │
│      ┆      ┆          ┆            ┆            ┆ phylogenetic clade.   ┆ phylogenetic clade.   │
│ 129  ┆ 131  ┆ 0.980153 ┆ 135        ┆ 137        ┆ An analysis of        ┆ An analysis of        │
│      ┆      ┆          ┆            ┆            ┆ Dictyostelium ras     ┆ Dictyostelium ras     │
│      ┆      ┆          ┆            ┆            ┆ family genes reveals  ┆ family genes reveals  │
│      ┆      ┆          ┆            ┆            ┆ that rasU rasU, rasV  ┆ that rasU rasU, rasV  │
│      ┆      ┆          ┆            ┆            ┆ rasV, rasW rasW, rasX ┆ rasV, rasW, rasX      │
│      ┆      ┆          ┆            ┆            ┆ rasX, rasY rasY and   ┆ rasX, rasY rasY and   │
│      ┆      ┆          ┆            ┆            ┆ rasZ form a separate  ┆ rasZ rasZ form a      │
│      ┆      ┆          ┆            ┆            ┆ phylogenetic clade.   ┆ separate phylogenetic │
│      ┆      ┆          ┆            ┆            ┆                       ┆ clade.                │
│ 129  ┆ 132  ┆ 0.980153 ┆ 135        ┆ 138        ┆ An analysis of        ┆ An analysis of        │
│      ┆      ┆          ┆            ┆            ┆ Dictyostelium ras     ┆ Dictyostelium ras     │
│      ┆      ┆          ┆            ┆            ┆ family genes reveals  ┆ family genes reveals  │
│      ┆      ┆          ┆            ┆            ┆ that rasU rasU, rasV  ┆ that rasU rasU, rasV, │
│      ┆      ┆          ┆            ┆            ┆ rasV, rasW rasW, rasX ┆ rasW rasW, rasX rasX, │
│      ┆      ┆          ┆            ┆            ┆ rasX, rasY rasY and   ┆ rasY rasY and rasZ    │
│      ┆      ┆          ┆            ┆            ┆ rasZ form a separate  ┆ rasZ form a separate  │
│      ┆      ┆          ┆            ┆            ┆ phylogenetic clade.   ┆ phylogenetic clade.   │
│ 129  ┆ 130  ┆ 0.980153 ┆ 135        ┆ 136        ┆ An analysis of        ┆ An analysis of        │
│      ┆      ┆          ┆            ┆            ┆ Dictyostelium ras     ┆ Dictyostelium ras     │
│      ┆      ┆          ┆            ┆            ┆ family genes reveals  ┆ family genes reveals  │
│      ┆      ┆          ┆            ┆            ┆ that rasU rasU, rasV  ┆ that rasU rasU, rasV  │
│      ┆      ┆          ┆            ┆            ┆ rasV, rasW rasW, rasX ┆ rasV, rasW rasW,      │
│      ┆      ┆          ┆            ┆            ┆ rasX, rasY rasY and   ┆ rasX, rasY rasY and   │
│      ┆      ┆          ┆            ┆            ┆ rasZ form a separate  ┆ rasZ rasZ form a      │
│      ┆      ┆          ┆            ┆            ┆ phylogenetic clade.   ┆ separate phylogenetic │
│      ┆      ┆          ┆            ┆            ┆                       ┆ clade.                │
└──────┴──────┴──────────┴────────────┴────────────┴───────────────────────┴───────────────────────┘

I manually look at around the top 2000 results and a threshold of 
sim_th = 0.65
shall be fine

In [49]:
# -------------------------
# 1) CLUSTERING (union-find)
# -------------------------
sim_th = 0.6 #<------------I decided after maual inspection and iterate with later process in #4

parent = list(range(n))

def find(x):
    while parent[x] != x:
        parent[x] = parent[parent[x]]
        x = parent[x]
    return x

def union(a, b):
    ra, rb = find(a), find(b)
    if ra != rb:
        parent[rb] = ra

# union candidate pairs above threshold
for i, j, sim in pairs:
    if sim >= sim_th:
        union(i, j)

# assign group ids (1..K)
roots = [find(i) for i in range(n)]
root_to_gid = {}
gids = []
for r in roots:
    if r not in root_to_gid:
        root_to_gid[r] = len(root_to_gid) + 1
    gids.append(root_to_gid[r])

claim_group_map = pl.DataFrame({
    "claim_id": ids,
    "group_claim_id": gids,
})

# quick cluster size stats
cluster_sizes = claim_group_map.group_by("group_claim_id").len().sort("len", descending=True)
display(cluster_sizes.head(30))

shape: (30, 2)
┌────────────────┬─────┐
│ group_claim_id ┆ len │
│ ---            ┆ --- │
│ i64            ┆ u32 │
╞════════════════╪═════╡
│ 147            ┆ 29  │
│ 16             ┆ 25  │
│ 457            ┆ 16  │
│ 445            ┆ 13  │
│ 62             ┆ 9   │
│ …              ┆ …   │
│ 54             ┆ 3   │
│ 623            ┆ 3   │
│ 882            ┆ 3   │
│ 376            ┆ 3   │
│ 1070           ┆ 3   │
└────────────────┴─────┘

In [51]:
# (4a_claim_groups.parquet is written after `rep` is defined — includes claim text + genes + canonical query.)

In [476]:
# ---------------------------------------------
# 2) TABLE: each group with variants in one row
# ---------------------------------------------
# Put variant claim_ids + variant texts into a list (for manual check)
group_variants = (
    claim_group_map
    .join(claims_u.select(["claim_id", "claim_plain", "claim_sim"]), on="claim_id", how="left")
    .group_by("group_claim_id")
    .agg([
        pl.col("claim_id").sort().alias("variant_claim_ids"),
        pl.col("claim_plain").alias("variant_claim_plain"),
        pl.col("claim_sim").alias("variant_claim_sim"),
        pl.len().alias("n_variants"),
    ])
    .sort(["n_variants", "group_claim_id"], descending=[True, False])
)

# Save for manual inspection
# TSV cannot store nested lists cleanly, so we stringify lists with join separators
group_variants_flat = (
    group_variants
    .with_columns([
        pl.col("variant_claim_ids")
          .list.eval(pl.element().cast(pl.Utf8)).list.join(",")
          .alias("variant_claim_ids"),
        pl.col("variant_claim_plain")
          .list.join(" ||| ")
          .alias("variant_claim_plain"),
        pl.col("variant_claim_sim")
          .list.join(" ||| ")
          .alias("variant_claim_sim"),
    ])
)

# group_variants_flat.write_csv("../tmp/group_variants.tsv", separator="\t")  # tmp/ removed
print("Wrote: tmp/group_variants.tsv")

Wrote: tmp/group_variants.tsv

In [477]:
# ------------------------------------------------------
# 3) Build a canonical representative text per group
#    (for downstream golden set + second TF-IDF peek)
# ------------------------------------------------------
# Choose canonical as the longest claim_plain (often most complete)
group_canon = (
    claim_group_map
    .join(claims_u.select(["claim_id", "claim_plain", "claim_sim"]), on="claim_id", how="left")
    .with_columns(pl.col("claim_plain").str.len_chars().alias("nchar"))
    .sort(["group_claim_id", "nchar"], descending=[False, True])
    .group_by("group_claim_id")
    .agg([
        pl.first("claim_plain").alias("canon_claim_plain"),
        pl.first("claim_sim").alias("canon_claim_sim"),
        pl.col("claim_id").sort().alias("variant_claim_ids"),
        pl.len().alias("n_variants"),
    ])
    .sort(["n_variants", "group_claim_id"], descending=[True, False])
)

# Save canonical table (flat)
group_canon_flat = group_canon.with_columns(
    pl.col("variant_claim_ids").list.eval(pl.element().cast(pl.Utf8)).list.join(",").alias("variant_claim_ids")
)
# group_canon_flat.write_csv("../tmp/group_canonical.tsv", separator="\t")  # tmp/ removed
print("Wrote: tmp/group_canonical.tsv")

Wrote: tmp/group_canonical.tsv

In [484]:
# ---------------------------------------------------------
# 4) PEEK #2: run TF-IDF again on canonical group texts
# ---------------------------------------------------------
group_texts = group_canon.get_column("canon_claim_sim").to_list()
group_ids   = group_canon.get_column("group_claim_id").to_list()
g = len(group_ids)

vec2 = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=1)
X2 = vec2.fit_transform(group_texts)

k2 = 15
nn2 = NearestNeighbors(n_neighbors=min(k2, g), metric="cosine").fit(X2)
dist2, idx2 = nn2.kneighbors(X2, return_distance=True)

pairs2 = []
for i in range(g):
    for d, j in zip(dist2[i], idx2[i]):
        if j <= i:
            continue
        sim = 1.0 - float(d)
        pairs2.append((i, j, sim))
pairs2.sort(key=lambda x: x[2], reverse=True)

topN2 = 10
pairs2_df = pl.DataFrame({
    "i": [p[0] for p in pairs2[:topN2]],
    "j": [p[1] for p in pairs2[:topN2]],
    "sim": [p[2] for p in pairs2[:topN2]],
    "group_id_i": [group_ids[p[0]] for p in pairs2[:topN2]],
    "group_id_j": [group_ids[p[1]] for p in pairs2[:topN2]],
    "text_i": [group_texts[p[0]] for p in pairs2[:topN2]],
    "text_j": [group_texts[p[1]] for p in pairs2[:topN2]],
}).sort("sim", descending=True)

with pl.Config(fmt_str_lengths=500, tbl_rows=topN2, tbl_cols=20):
    display(pairs2_df)

# pairs2_df.write_csv("../tmp/group_pairwise_peek.tsv", separator="\t")  # tmp/ removed
print("Wrote: tmp/group_pairwise_peek.tsv")

shape: (10, 7)
┌──────┬──────┬──────────┬────────────┬────────────┬───────────────────────┬───────────────────────┐
│ i    ┆ j    ┆ sim      ┆ group_id_i ┆ group_id_j ┆ text_i                ┆ text_j                │
│ ---  ┆ ---  ┆ ---      ┆ ---        ┆ ---        ┆ ---                   ┆ ---                   │
│ i64  ┆ i64  ┆ f64      ┆ i64        ┆ i64        ┆ str                   ┆ str                   │
╞══════╪══════╪══════════╪════════════╪════════════╪═══════════════════════╪═══════════════════════╡
│ 389  ┆ 390  ┆ 0.597185 ┆ 275        ┆ 276        ┆ cotA encodes SP96     ┆ cotB encodes SP70     │
│      ┆      ┆          ┆            ┆            ┆ which is fucosylated  ┆ which is glycosylated │
│      ┆      ┆          ┆            ┆            ┆ before exocytosis     ┆ before being released │
│      ┆      ┆          ┆            ┆            ┆ from the PSVs and     ┆ and positioned in the │
│      ┆      ┆          ┆            ┆            ┆ positioning in the    ┆ outer layer of the    │
│      ┆      ┆          ┆            ┆            ┆ outer layer of the    ┆ spore coats.          │
│      ┆      ┆          ┆            ┆            ┆ spore coats.          ┆                       │
│ 24   ┆ 867  ┆ 0.591388 ┆ 83         ┆ 813        ┆ aif downregulation    ┆ Knockdown of DJ-1     │
│      ┆      ┆          ┆            ┆            ┆ also resulted in      ┆ also causes a small   │
│      ┆      ┆          ┆            ┆            ┆ increased             ┆ but significant       │
│      ┆      ┆          ┆            ┆            ┆ mitochondrial fission ┆ activation of         │
│      ┆      ┆          ┆            ┆            ┆ and defects in        ┆ mitochondrial         │
│      ┆      ┆          ┆            ┆            ┆ mitochondrial         ┆ respiratory function, │
│      ┆      ┆          ┆            ┆            ┆ structure, further    ┆ while overexpression  │
│      ┆      ┆          ┆            ┆            ┆ revealing the role of ┆ inhibits              │
│      ┆      ┆          ┆            ┆            ┆ aif in mitochondrial  ┆ mitochondrial         │
│      ┆      ┆          ┆            ┆            ┆ organization and      ┆ activity, revealing   │
│      ┆      ┆          ┆            ┆            ┆ homeostasis.          ┆ that reduced levels   │
│      ┆      ┆          ┆            ┆            ┆                       ┆ of deeJ do not        │
│      ┆      ┆          ┆            ┆            ┆                       ┆ phenocopy             │
│      ┆      ┆          ┆            ┆            ┆                       ┆ mitochondrial         │
│      ┆      ┆          ┆            ┆            ┆                       ┆ dysfunction.          │
│ 1482 ┆ 1483 ┆ 0.590647 ┆ 1477       ┆ 1478       ┆ The X-ray structure   ┆ The X-ray structure   │
│      ┆      ┆          ┆            ┆            ┆ of nucleoside         ┆ of wild type and      │
│      ┆      ┆          ┆            ┆            ┆ diphosphate kinase    ┆ several mutants       │
│      ┆      ┆          ┆            ┆            ┆ NDP kinase from       ┆ nucleoside            │
│      ┆      ┆          ┆            ┆            ┆ Dictyostelium         ┆ diphosphate kinase    │
│      ┆      ┆          ┆            ┆            ┆ discoideum has been   ┆ bound to substrates,  │
│      ┆      ┆          ┆            ┆            ┆ determined.           ┆ co-factors and        │
│      ┆      ┆          ┆            ┆            ┆                       ┆ inhibitors has also   │
│      ┆      ┆          ┆            ┆            ┆                       ┆ been determined.      │
│ 113  ┆ 608  ┆ 0.584258 ┆ 870        ┆ 529        ┆ mRNA levels of racI   ┆ gefB expression also  │
│      ┆      ┆          ┆            ┆            ┆ increase during       ┆ increases during      │
│      ┆      ┆          ┆            ┆            ┆ sexual development,   ┆ sexual development.   │
│      ┆      ┆          ┆            ┆            ┆ suggesting that racI  ┆                       │
│      ┆      ┆          ┆            ┆            ┆ may function in       ┆                       │
│      ┆      ┆          ┆            ┆            ┆ sexual development.   ┆                       │
│ 364  ┆ 1491 ┆ 0.578504 ┆ 249        ┆ 1487       ┆ Characterization of   ┆ There is a second     │
│      ┆      ┆          ┆            ┆            ┆ cDNA and genomic      ┆ gene encoding         │
│      ┆      ┆          ┆            ┆            ┆ clones of uppA showed ┆ UDP-glucose           │
│      ┆      ┆          ┆            ┆            ┆ that it encodes       ┆ pyrophosphorylase,    │
│      ┆      ┆          ┆            ┆            ┆ UDP-glucose           ┆ uppA uppA.            │
│      ┆      ┆          ┆            ┆            ┆ pyrophosphorylase.    ┆                       │
│ 638  ┆ 639  ┆ 0.577355 ┆ 564        ┆ 565        ┆ gpaA encodes G-alpha  ┆ gpaB encodes one of   │
│      ┆      ┆          ┆            ┆            ┆ 1, one of the dozen   ┆ the dozen G alpha     │
│      ┆      ┆          ┆            ┆            ┆ alpha subunits that   ┆ subunits in           │
│      ┆      ┆          ┆            ┆            ┆ associate with the    ┆ Dictyostelium,        │
│      ┆      ┆          ┆            ┆            ┆ unique G-beta and     ┆ Galpha2, which        │
│      ┆      ┆          ┆            ┆            ┆ G-gamma subunits      ┆ associates with Gbeta │
│      ┆      ┆          ┆            ┆            ┆ gpbA, gpgA.           ┆ and Ggamma subunits   │
│      ┆      ┆          ┆            ┆            ┆                       ┆ gpbA, gpgA to form    │
│      ┆      ┆          ┆            ┆            ┆                       ┆ the G protein that    │
│      ┆      ┆          ┆            ┆            ┆                       ┆ binds to the cAMP     │
│      ┆      ┆          ┆            ┆            ┆                       ┆ receptor CAR1 carA-1, │
│      ┆      ┆          ┆            ┆            ┆                       ┆ carA-2..              │
│ 800  ┆ 1142 ┆ 0.577282 ┆ 740        ┆ 1117       ┆ In response to cAMP,  ┆ RasG activation is    │
│      ┆      ┆          ┆            ┆            ┆ RasG activation was   ┆ reduced in gefR gefR  │
│      ┆      ┆          ┆            ┆            ┆ greatly reduced in a  ┆ and gflB gflB null    │
│      ┆      ┆          ┆            ┆            ┆ gefR null mutant,     ┆ mutant strains,       │
│      ┆      ┆          ┆            ┆            ┆ indicating that GefR  ┆ indicating that these │
│      ┆      ┆          ┆            ┆            ┆ has GEF activity      ┆ rasGEFs activate      │
│      ┆      ┆          ┆            ┆            ┆ towards RasG.         ┆ rasG..                │
│ 170  ┆ 1410 ┆ 0.577016 ┆ 20         ┆ 1398       ┆ A histidine moeity in ┆ The phosphate on RdeA │
│      ┆      ┆          ┆            ┆            ┆ the 28 kDa RdeA       ┆ is in equilibrium     │
│      ┆      ┆          ┆            ┆            ┆ protein accepts a     ┆ with phosphate on an  │
│      ┆      ┆          ┆            ┆            ┆ phosphate from an     ┆ aspartate in the      │
│      ┆      ┆          ┆            ┆            ┆ aspartate in          ┆ response regulator    │
│      ┆      ┆          ┆            ┆            ┆ histidine kinases,    ┆ region of the cAMP    │
│      ┆      ┆          ┆            ┆            ┆ and relays it to an   ┆ phosphodiesterase     │
│      ┆      ┆          ┆            ┆            ┆ aspartate in the      ┆ RegA regA.            │
│      ┆      ┆          ┆            ┆            ┆ response regulator    ┆                       │
│      ┆      ┆          ┆            ┆            ┆ region of the cAMP    ┆                       │
│      ┆      ┆          ┆            ┆            ┆ phosophodiesterase    ┆                       │
│      ┆      ┆          ┆            ┆            ┆ RegA regA.            ┆                       │
│ 137  ┆ 510  ┆ 0.574659 ┆ 1258       ┆ 414        ┆ The adaptor protein   ┆ ElmoE elmoE           │
│      ┆      ┆          ┆            ┆            ┆ ElmoE elmoE           ┆ associates with the   │
│      ┆      ┆          ┆            ┆            ┆ associates with the   ┆ Gbeta/Ggamma subunits │
│      ┆      ┆          ┆            ┆            ┆ Rho GTPase RacB racB  ┆ and interacts with    │
│      ┆      ┆          ┆            ┆            ┆ as well as with both  ┆ Dock-like proteins    │
│      ┆      ┆          ┆            ┆            ┆ ZizA and DocC docC,   ┆ DocC docC and         │
│      ┆      ┆          ┆            ┆            ┆ suggesting that       ┆ possibly ZizA zizA to │
│      ┆      ┆          ┆            ┆            ┆ ElmoE, DocC, and ZizA ┆ activate the small    │
│      ┆      ┆          ┆            ┆            ┆ may form an           ┆ GTPase RacB racB and  │
│      ┆      ┆          ┆            ┆            ┆ evolutionarily        ┆ promote actin         │
│      ┆      ┆          ┆            ┆            ┆ conserved Elmo/Dock   ┆ polymerization in the │
│      ┆      ┆          ┆            ┆            ┆ complex to serve as a ┆ leading edge of       │
│      ┆      ┆          ┆            ┆            ┆ GEF for RacB.         ┆ migrating cells.      │
│ 1246 ┆ 1256 ┆ 0.573274 ┆ 1224       ┆ 1234       ┆ Taken together, these ┆ Taken together, these │
│      ┆      ┆          ┆            ┆            ┆ results suggest       ┆ results suggest that  │
│      ┆      ┆          ┆            ┆            ┆ likely functional     ┆ MEGAP1 is a likely    │
│      ┆      ┆          ┆            ┆            ┆ redundancy between    ┆ downstream effector   │
│      ┆      ┆          ┆            ┆            ┆ MEGAP family members  ┆ of Rho GTPases and an │
│      ┆      ┆          ┆            ┆            ┆ and that MEGAP2 may   ┆ important regulator   │
│      ┆      ┆          ┆            ┆            ┆ play a role in slug   ┆ of the contractile    │
│      ┆      ┆          ┆            ┆            ┆ development and in    ┆ vacuole network.      │
│      ┆      ┆          ┆            ┆            ┆ regulation of the     ┆                       │
│      ┆      ┆          ┆            ┆            ┆ contractile vacuole   ┆                       │
│      ┆      ┆          ┆            ┆            ┆ network.              ┆                       │
└──────┴──────┴──────────┴────────────┴────────────┴───────────────────────┴───────────────────────┘

Wrote: tmp/group_pairwise_peek.tsv

In [485]:
claim_group_map.select(pl.col("group_claim_id").n_unique().alias("n_group_claim_id"))

shape: (1, 1)
┌──────────────────┐
│ n_group_claim_id │
│ ---              │
│ u32              │
╞══════════════════╡
│ 1705             │
└──────────────────┘

we still have 1705 claims. This is nice

let us get our golden set

In [523]:
# --- 1) attach group ids to the long evidence table ---
gold_long = (
    claim_cleaned_pmid_nonNA_abstract
    .join(claim_group_map, on="claim_id", how="left")
    .join(claims_u.select(["claim_id", "claim_sim"]), on="claim_id", how="left")
)

In [524]:
# --- 2) pick one canonical query per group (longest claim_sim) ---
# canon_query = (
#     gold_long
#     .select(["group_claim_id", "claim_id", "claim_sim"])
#     .unique(subset=["group_claim_id", "claim_id"])
#     .with_columns(pl.col("claim_sim").str.len_chars().alias("nchar"))
#     .sort(["group_claim_id", "nchar"], descending=[False, True])
#     .group_by("group_claim_id")
#     .agg(pl.first("claim_sim").alias("query"))
# )
rep = (
    gold_long
    .select(["group_claim_id", "claim_id", "claim_sim"])
    .unique(subset=["group_claim_id", "claim_id"])   # one per variant
    .with_columns(pl.col("claim_sim").str.len_chars().alias("nchar"))
    .sort(["group_claim_id", "nchar"], descending=[False, True])
    .group_by("group_claim_id")
    .agg([
        pl.first("claim_id").alias("rep_claim_id"),
        pl.first("claim_sim").alias("query"),
    ])
)
rep

shape: (1_705, 3)
┌────────────────┬──────────────┬─────────────────────────────────┐
│ group_claim_id ┆ rep_claim_id ┆ query                           │
│ ---            ┆ ---          ┆ ---                             │
│ i64            ┆ i64          ┆ str                             │
╞════════════════╪══════════════╪═════════════════════════════════╡
│ 1              ┆ 1            ┆ A basic region in the tail is … │
│ 2              ┆ 2            ┆ A cDNA clone derived from psvA… │
│ 3              ┆ 3            ┆ A cDNA clone of this gene, D19… │
│ 4              ┆ 4            ┆ A co-immunoprecipitation assay… │
│ 5              ┆ 5            ┆ A comparison of the genes tran… │
│ 6              ┆ 7            ┆ A DDB_G0269670 null mutant is … │
│ 7              ┆ 11           ┆ A Dictyostelium homolog of Vps… │
│ 8              ┆ 756          ┆ However, a double carA / carC … │
│ 9              ┆ 13           ┆ A double mutant in disgorgin a… │
│ 10             ┆ 14           ┆ A double mutant of gapA / rgaA… │
│ …              ┆ …            ┆ …                               │
│ 1696           ┆ 2050         ┆ When the rate of development i… │
│ 1697           ┆ 2051         ┆ When these mutants were analyz… │
│ 1698           ┆ 2053         ┆ While prestalk specific genes … │
│ 1699           ┆ 2054         ┆ While the effects were shown i… │
│ 1700           ┆ 2055         ┆ While the shorter transcript i… │
│ 1701           ┆ 2056         ┆ Wild-type cells in a chimaera … │
│ 1702           ┆ 2058         ┆ Yersinia pestis YopE blocks th… │
│ 1703           ┆ 2059         ┆ Yet another role for NDP kinas… │
│ 1704           ┆ 2060         ┆ zizA null mutant cells do not … │
│ 1705           ┆ 2061         ┆ ZizB also interacts with sever… │
└────────────────┴──────────────┴─────────────────────────────────┘

In [ ]:
gene_by_claim = (
    claim_cleaned_pmid_nonNA_abstract
    .group_by("claim_id")
    .agg(
        pl.col("gene_id").unique().sort().str.join(",").alias("gene_id"),
    )
)
claim_groups_detail = (
    claim_group_map
    .join(claims_u, on="claim_id", how="left")
    .join(gene_by_claim, on="claim_id", how="left")
    .join(
        rep.select(["group_claim_id", "rep_claim_id", "query"]).rename({"query": "canonical_query"}),
        on="group_claim_id",
        how="left",
    )
    .with_columns(
        (pl.col("claim_id") == pl.col("rep_claim_id")).alias("is_representative_claim"),
    )
)
claim_groups_detail.write_parquet(OUTPUT_GOLD_BUILD / "4a_claim_groups.parquet")

In [525]:
# 3) Count variants (metadata) — from the mapping, not from citations
variant_counts = (
    claim_group_map
    .group_by("group_claim_id")
    .agg(pl.len().alias("n_variants"))
)

# 4) Keep ONLY the representative claim’s citations + anchors, then build golden set
rep_long = (
    gold_long
    .join(rep.select(["group_claim_id", "rep_claim_id"]), on="group_claim_id", how="inner")
    .filter(pl.col("claim_id") == pl.col("rep_claim_id"))
)

# 5) doc-level info (includes anchor_pos + citation_captions) for the representative query only
docs = (
    rep_long
    .group_by(["group_claim_id", "publication_id", "pmid", "title", "abstract_clean", "year"])
    .agg([
        pl.col("anchor_pos").drop_nulls().unique().sort().alias("anchor_pos"),
        pl.col("citation_captions").drop_nulls().unique().sort().alias("citation_captions"),
    ])
    .group_by("group_claim_id")
    .agg([
        pl.struct([
            "publication_id", "pmid", "title", "abstract_clean", "year",
            "anchor_pos", "citation_captions"
        ]).alias("docs"),
        pl.col("year").drop_nulls().unique().sort().alias("years"),   # years for THIS rep query only
    ])
)

gold = (
    rep
    .join(variant_counts, on="group_claim_id", how="left")
    .join(docs, on="group_claim_id", how="left")
    .with_columns([
        pl.col("docs").list.len().alias("n_citations"),
        pl.col("query").str.count_matches(r"\S+").alias("query_n_words"),
    ])
    .select([
        "group_claim_id",
        "rep_claim_id",
        "query",
        "n_variants",
        "n_citations",
        "query_n_words",
        "years",
        "docs",
    ])
)

gold.head(2)

shape: (2, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ group_clai ┆ rep_claim_ ┆ query      ┆ n_variant ┆ n_citatio ┆ query_n_w ┆ years     ┆ docs      │
│ m_id       ┆ id         ┆ ---        ┆ s         ┆ ns        ┆ ords      ┆ ---       ┆ ---       │
│ ---        ┆ ---        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ list[i32] ┆ list[stru │
│ i64        ┆ i64        ┆            ┆ u32       ┆ u32       ┆ u32       ┆           ┆ ct[7]]    │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1          ┆ 1          ┆ A basic    ┆ 1         ┆ 1         ┆ 17        ┆ [2014]    ┆ [{13954," │
│            ┆            ┆ region in  ┆           ┆           ┆           ┆           ┆ 24747353" │
│            ┆            ┆ the tail   ┆           ┆           ┆           ┆           ┆ ,"The     │
│            ┆            ┆ is …       ┆           ┆           ┆           ┆           ┆ associ…   │
│ 2          ┆ 2          ┆ A cDNA     ┆ 1         ┆ 1         ┆ 19        ┆ [1983]    ┆ [{8316,"6 │
│            ┆            ┆ clone      ┆           ┆           ┆           ┆           ┆ 301681"," │
│            ┆            ┆ derived    ┆           ┆           ┆           ┆           ┆ Regulatio │
│            ┆            ┆ from psvA… ┆           ┆           ┆           ┆           ┆ n o…      │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [526]:
gold.write_parquet(OUTPUT_GOLD_BUILD / "4b_golden_grouped.parquet")

In [527]:
gold_flat = (
    gold
    .explode("docs")
    .unnest("docs")
    .select([
        "group_claim_id",
        "query",
        "n_variants",
        "n_citations",
        "publication_id",
        "pmid",
        "title",
        "abstract_clean",
        "year",
    ])
)

# gold_flat.write_csv("../tmp/golden_flat.tsv", separator="\t")  # tmp/ removed
print("Wrote: tmp/golden_flat.tsv")

Wrote: tmp/golden_flat.tsv

let us check out query statistics

In [528]:
# number of the citation a query have
cit_dist = gold.group_by("n_citations").len().sort("n_citations")
cit_dist

shape: (8, 2)
┌─────────────┬──────┐
│ n_citations ┆ len  │
│ ---         ┆ ---  │
│ u32         ┆ u32  │
╞═════════════╪══════╡
│ 1           ┆ 1390 │
│ 2           ┆ 248  │
│ 3           ┆ 51   │
│ 4           ┆ 11   │
│ 5           ┆ 2    │
│ 7           ┆ 1    │
│ 9           ┆ 1    │
│ 10          ┆ 1    │
└─────────────┴──────┘

In [529]:
many_cit = gold.filter(pl.col("n_citations") > 5).select([
    "group_claim_id",
    "n_citations",
    "n_variants",
    "query",
])

with pl.Config(fmt_str_lengths=10_000, tbl_rows=500, tbl_cols=20):
    display(many_cit.sort("n_citations", descending=True))

shape: (3, 4)
┌────────────────┬─────────────┬────────────┬──────────────────────────────────────────────────────┐
│ group_claim_id ┆ n_citations ┆ n_variants ┆ query                                                │
│ ---            ┆ ---         ┆ ---        ┆ ---                                                  │
│ i64            ┆ u32         ┆ u32        ┆ str                                                  │
╞════════════════╪═════════════╪════════════╪══════════════════════════════════════════════════════╡
│ 511            ┆ 10          ┆ 1          ┆ G boxes are found in the promoters of several        │
│                ┆             ┆            ┆ postaggregative and cell-type-specific genes,        │
│                ┆             ┆            ┆ including carC, cotB, cotC, cprA, cprB, and ecmB.    │
│                ┆             ┆            ┆ Consistent with these data, analysis of the gbfA     │
│                ┆             ┆            ┆ -null cell line provided additional evidence that    │
│                ┆             ┆            ┆ GBF is a key component of the development switch     │
│                ┆             ┆            ┆ between aggregation and multicellular                │
│                ┆             ┆            ┆ differentiation as a general inducer of              │
│                ┆             ┆            ┆ postaggregative and cell-type-specific gene          │
│                ┆             ┆            ┆ expression multicellular organismal development.     │
│ 183            ┆ 9           ┆ 1          ┆ Ca++/calmodulin binds to many Dictyostelium proteins │
│                ┆             ┆            ┆ including a ribosomal protein L19 rpl19,             │
│                ┆             ┆            ┆ cyclin-dependent kinase cdk5 and nucleomorphin numA  │
│                ┆             ┆            ┆ among others.                                        │
│ 1071           ┆ 7           ┆ 6          ┆ These include: the protein kinase PakA pakA, PakC    │
│                ┆             ┆            ┆ pakC, Lissencephaly-related protein LIS1 lis1,       │
│                ┆             ┆            ┆ diaphanous-related formin H forH, the myosin heavy   │
│                ┆             ┆            ┆ chain kinase PakB pakB pakB, coronin A corA and WASP │
│                ┆             ┆            ┆ wasA.                                                │
└────────────────┴─────────────┴────────────┴──────────────────────────────────────────────────────┘

In [530]:
rep.filter(pl.col("group_claim_id") == 1071).select(["group_claim_id", "rep_claim_id", "query"])
gene = (
    claim_cleaned_pmid_nonNA_abstract
    .filter(pl.col("claim_id") == 1835)
    .select(pl.col("gene_id").unique())
)

gene

shape: (1, 1)
┌──────────────┐
│ gene_id      │
│ ---          │
│ str          │
╞══════════════╡
│ DDB_G0277869 │
└──────────────┘

Looked at http://dictybase.org/gene/DDB_G0277869, it is fine.

In [531]:
len_dist = (
    gold.with_columns(
        pl.when(pl.col("query_n_words") < 10).then(pl.lit("<10"))
          .when(pl.col("query_n_words") < 20).then(pl.lit("10-19"))
          .when(pl.col("query_n_words") < 40).then(pl.lit("20-39"))
          .otherwise(pl.lit("40+"))
          .alias("len_bucket")
    )
    .group_by("len_bucket")
    .len()
    .sort("len_bucket")
)
len_dist

shape: (4, 2)
┌────────────┬─────┐
│ len_bucket ┆ len │
│ ---        ┆ --- │
│ str        ┆ u32 │
╞════════════╪═════╡
│ 10-19      ┆ 686 │
│ 20-39      ┆ 872 │
│ 40+        ┆ 77  │
│ <10        ┆ 70  │
└────────────┴─────┘

In [532]:
var_dist = (
    gold.with_columns(
        pl.when(pl.col("n_variants") == 1).then(pl.lit("1"))
          .when(pl.col("n_variants") <= 3).then(pl.lit("2-3"))
          .when(pl.col("n_variants") <= 10).then(pl.lit("4-10"))
          .otherwise(pl.lit("11+"))
          .alias("variant_bucket")
    )
    .group_by("variant_bucket")
    .len()
    .sort("variant_bucket")
)

var_dist

shape: (4, 2)
┌────────────────┬──────┐
│ variant_bucket ┆ len  │
│ ---            ┆ ---  │
│ str            ┆ u32  │
╞════════════════╪══════╡
│ 1              ┆ 1549 │
│ 11+            ┆ 4    │
│ 2-3            ┆ 135  │
│ 4-10           ┆ 17   │
└────────────────┴──────┘

In [535]:
# year
year_dist = (
    gold
    .select(["group_claim_id", "years"])
    .explode("years")
    .group_by("years")
    .len()
    .sort("years")
)
year_dist

shape: (47, 2)
┌───────┬─────┐
│ years ┆ len │
│ ---   ┆ --- │
│ i32   ┆ u32 │
╞═══════╪═════╡
│ null  ┆ 3   │
│ 1969  ┆ 4   │
│ 1970  ┆ 2   │
│ 1973  ┆ 1   │
│ 1976  ┆ 8   │
│ 1978  ┆ 3   │
│ 1979  ┆ 1   │
│ 1981  ┆ 3   │
│ 1982  ┆ 1   │
│ 1983  ┆ 5   │
│ …     ┆ …   │
│ 2011  ┆ 66  │
│ 2012  ┆ 75  │
│ 2013  ┆ 82  │
│ 2014  ┆ 64  │
│ 2015  ┆ 76  │
│ 2016  ┆ 66  │
│ 2017  ┆ 39  │
│ 2018  ┆ 67  │
│ 2019  ┆ 60  │
│ 2020  ┆ 27  │
└───────┴─────┘

conclusion of thses statistics:
- 1-citation queries is domindated.
- sentence length looks fine.
- there are some big  vairant groups

Thoughts:
- This could be a good automatic dataset
- If we should have a second track to manually pick a smaller gold subset
    - this need to be very accurate
    - in this case we shall keep oversample multi-citation groups, i.e those n_citations>1
- those big variant_bucket might be helpful for stress testing / hard negatives (they are similar but different citations), for now variant_bucket is merged